# 2.4 CNN Model

### Import Libraries & Data

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import time
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.multiclass import type_of_target
import tensorflow as tf
from numpy import unique
from numpy import reshape
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score
from tensorflow.keras.layers import Input, Conv1D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from scikeras.wrappers import KerasClassifier  # Use scikeras for scikit-learn compatibility
from math import floor
from bayes_opt import BayesianOptimization
from tensorflow.keras.layers import LeakyReLU  # Use tensorflow.keras instead of keras
LeakyReLU = LeakyReLU(negative_slope=0.1)
import warnings

In [5]:
# Set display options to show all columns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
# Set path
path = r"C:\Users\cschw\OneDrive\Desktop\Machine Learning"

In [7]:
# Load unscaled data
unscaled= pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-weather-prediction-dataset-processed.csv'))

In [8]:
# Check head
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,8,0.91,0.00,0,0.8,-0.3,1.6,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,3,2.6,0.73,1.0152,7.1,7.8,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,3.8,0.76,1.0169,1.54,0.44,10.0,7.8,12.2,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,8,0.93,0.08,0,1.6,0.9,2.2,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,3,2.6,0.73,1.0152,7.1,12.2,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,3.8,0.76,1.0169,1.54,0.71,9.5,7.0,12.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.94,0.15,0,0.7,0.4,1.7,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,3,2.6,0.73,1.0152,7.1,10.2,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,3.8,0.76,1.0169,1.54,0.10,10.3,9.0,11.6,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,7,0.91,0.00,0,-0.1,-0.9,2.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,3,2.6,0.73,1.0152,7.1,10.8,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,3.8,0.76,1.0169,1.54,0.10,11.2,9.9,12.6,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,7,0.94,0.17,0,0.4,-1.7,1.5,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,3,2.6,0.73,1.0152,7.1,9.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3.8,0.76,1.0169,1.54,0.00,11.4,10.7,12.0,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [9]:
# Load pleasant weather predictions
prediction= pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

In [10]:
# Check head
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [11]:
# check shape of unscaled
unscaled.shape

(22950, 170)

In [12]:
# check shape of prediction
prediction.shape

(22950, 16)

### Data Wrangling

In [14]:
# Remove weather stations not included in "pleasant weather" answers
unscaled = unscaled.drop(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max',
                        'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean',
                        'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'], axis=1)

In [15]:
# check shape to confirm
unscaled.shape

(22950, 149)

In [16]:
# check for null values
unscaled.isnull().sum()

DATE                           0
MONTH                          0
BASEL_cloud_cover              0
BASEL_wind_speed               0
BASEL_humidity                 0
BASEL_pressure                 0
BASEL_global_radiation         0
BASEL_precipitation            0
BASEL_snow_depth               0
BASEL_sunshine                 0
BASEL_temp_mean                0
BASEL_temp_min                 0
BASEL_temp_max                 0
BELGRADE_cloud_cover           0
BELGRADE_humidity              0
BELGRADE_pressure              0
BELGRADE_global_radiation      0
BELGRADE_precipitation         0
BELGRADE_sunshine              0
BELGRADE_temp_mean             0
BELGRADE_temp_min              0
BELGRADE_temp_max              0
BUDAPEST_cloud_cover           0
BUDAPEST_humidity              0
BUDAPEST_pressure              0
BUDAPEST_global_radiation      0
BUDAPEST_precipitation         0
BUDAPEST_sunshine              0
BUDAPEST_temp_mean             0
BUDAPEST_temp_min              0
BUDAPEST_temp_max              0
DEBILT_cloud_cover             0
DEBILT_wind_speed              0
DEBILT_humidity                0
DEBILT_pressure                0
DEBILT_global_radiation        0
DEBILT_precipitation           0
DEBILT_sunshine                0
DEBILT_temp_mean               0
DEBILT_temp_min                0
DEBILT_temp_max                0
DUSSELDORF_cloud_cover         0
DUSSELDORF_wind_speed          0
DUSSELDORF_humidity            0
DUSSELDORF_pressure            0
DUSSELDORF_global_radiation    0
DUSSELDORF_precipitation       0
DUSSELDORF_snow_depth          0
DUSSELDORF_sunshine            0
DUSSELDORF_temp_mean           0
DUSSELDORF_temp_min            0
DUSSELDORF_temp_max            0
HEATHROW_cloud_cover           0
HEATHROW_humidity              0
HEATHROW_pressure              0
HEATHROW_global_radiation      0
HEATHROW_precipitation         0
HEATHROW_snow_depth            0
HEATHROW_sunshine              0
HEATHROW_temp_mean             0
HEATHROW_temp_min              0
HEATHROW_temp_max              0
KASSEL_wind_speed              0
KASSEL_humidity                0
KASSEL_pressure                0
KASSEL_global_radiation        0
KASSEL_precipitation           0
KASSEL_sunshine                0
KASSEL_temp_mean               0
KASSEL_temp_min                0
KASSEL_temp_max                0
LJUBLJANA_cloud_cover          0
LJUBLJANA_wind_speed           0
LJUBLJANA_humidity             0
LJUBLJANA_pressure             0
LJUBLJANA_global_radiation     0
LJUBLJANA_precipitation        0
LJUBLJANA_sunshine             0
LJUBLJANA_temp_mean            0
LJUBLJANA_temp_min             0
LJUBLJANA_temp_max             0
MAASTRICHT_cloud_cover         0
MAASTRICHT_wind_speed          0
MAASTRICHT_humidity            0
MAASTRICHT_pressure            0
MAASTRICHT_global_radiation    0
MAASTRICHT_precipitation       0
MAASTRICHT_sunshine            0
MAASTRICHT_temp_mean           0
MAASTRICHT_temp_min            0
MAASTRICHT_temp_max            0
MADRID_cloud_cover             0
MADRID_wind_speed              0
MADRID_humidity                0
MADRID_pressure                0
MADRID_global_radiation        0
MADRID_precipitation           0
MADRID_sunshine                0
MADRID_temp_mean               0
MADRID_temp_min                0
MADRID_temp_max                0
MUNCHENB_cloud_cover           0
MUNCHENB_humidity              0
MUNCHENB_global_radiation      0
MUNCHENB_precipitation         0
MUNCHENB_snow_depth            0
MUNCHENB_sunshine              0
MUNCHENB_temp_mean             0
MUNCHENB_temp_min              0
MUNCHENB_temp_max              0
OSLO_cloud_cover               0
OSLO_wind_speed                0
OSLO_humidity                  0
OSLO_pressure                  0
OSLO_global_radiation          0
OSLO_precipitation             0
OSLO_snow_depth                0
OSLO_sunshine                  0
OSLO_temp_mean                 0
OSLO_temp_min                  0
OSLO_temp_max                  0
SONNBLICK_cloud_cover          0
SONNBLICK_wind_speed           0
SONNBLICK_humidity             0
SONNBLICK_pressure             0
SONNBLICK_global_radiation     0
SONNBLICK_precipitation        0
SONNBLICK_sunshine             0
SONNBLICK_temp_mean            0
SONNBLICK_temp_min             0
SONNBLICK_temp_max             0
STOCKHOLM_cloud_cover          0
STOCKHOLM_pressure             0
STOCKHOLM_global_radiation     0
STOCKHOLM_precipitation        0
STOCKHOLM_sunshine             0
STOCKHOLM_temp_mean            0
STOCKHOLM_temp_min             0
STOCKHOLM_temp_max             0
VALENTIA_cloud_cover           0
VALENTIA_humidity              0
VALENTIA_pressure              0
VALENTIA_global_radiation      0
VALENTIA_precipitation         0
VALENTIA_snow_depth            0
VALENTIA_sunshine              0
VALENTIA_temp_mean             0
VALENTIA_temp_min              0
VALENTIA_temp_max              0
dtype: int64

In [17]:
# Extract the different observation types

observation_types = ['cloud_cover', 'wind_speed', 'humidity', 'pressure',
                     'global_radiation', 'precipitation', 'snow_depth', 
                     'sunshine', 'temp_mean', 'temp_min', 'temp_max']

In [18]:
# Create a dictionary to store the count of stations for each observation type
station_counts = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Count the number of stations (i.e., the number of columns) for the current observation type
    station_counts[obs] = len(columns)

# Print the count of stations for each observation type
print("Number of stations covered by each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Number of stations covered by each observation type:
cloud_cover: 14 stations
wind_speed: 9 stations
humidity: 14 stations
pressure: 14 stations
global_radiation: 15 stations
precipitation: 15 stations
snow_depth: 6 stations
sunshine: 15 stations
temp_mean: 15 stations
temp_min: 15 stations
temp_max: 15 stations

In [19]:
# Get a list of columns containing 'wind_speed' or 'snow_depth'
cols_to_drop = [col for col in unscaled.columns if '_wind_speed' in col or '_snow_depth' in col]

# Drop the columns
unscaled = unscaled.drop(cols_to_drop, axis=1)

In [20]:
unscaled.shape # Expecation is to have 15 columns less

(22950, 134)

In [21]:
# Find the stations with the above entries missing
# Get all column names
all_columns = unscaled.columns.tolist()
# Exclude 'DATE' and 'MONTH' columns
all_columns = [col for col in all_columns if col not in ['DATE', 'MONTH']]  
# Extract unique weather station names
weather_stations = set()  # Use a set to automatically store only unique values
for col in all_columns:
    station_name = col.split('_')[0]  # Split the column name at the underscore and take the first part
    weather_stations.add(station_name)

# Print the list of weather stations
print(weather_stations)

{'BUDAPEST', 'DUSSELDORF', 'MADRID', 'MUNCHENB', 'MAASTRICHT', 'SONNBLICK', 'STOCKHOLM', 'VALENTIA', 'BELGRADE', 'HEATHROW', 'DEBILT', 'OSLO', 'BASEL', 'LJUBLJANA', 'KASSEL'}

In [22]:
# Find stations missing observation types
observation_types = ['cloud_cover', 'humidity', 'pressure']

missing_stations_by_observation = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Extract station names by removing the observation type from the column names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identify stations that are in all_stations but missing from the current observation type
    missing_stations = weather_stations - station_names
    
    # Store the missing station names in the dictionary
    missing_stations_by_observation[obs] = missing_stations

# Print the missing station names for each observation type
for obs, missing_stations in missing_stations_by_observation.items():
    print(f"\nStations missing from {obs}:")
    if missing_stations:
        for station in missing_stations:
            print(station)
    else:
        print("None")

Stations missing from cloud_cover:
KASSEL

Stations missing from humidity:
STOCKHOLM

Stations missing from pressure:
MUNCHENB

In [23]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [24]:
# Cloud cover is the start of a stations data, Kassel is next to Heathrow, find the position of Heathrow_temp_max for the insertion of Kassel_cloud_cover
unscaled.columns.get_loc('HEATHROW_temp_max')

55

In [25]:
# Find the position for insertion of Stockholm humidity
unscaled.columns.get_loc('STOCKHOLM_cloud_cover') #humidity is 1 after cloud cover so (result +1)

117

In [26]:
# Find position for Munchenb pressure
unscaled.columns.get_loc('MUNCHENB_cloud_cover') # pressure is 2 after cloud cover so (result +2)

91

In [27]:
# Insert new columns into "unscaled" at specific positions.
# The data for these new columns is taken from weather stations they are close to

unscaled.insert(56,'KASSEL_cloud_cover', unscaled['DUSSELDORF_cloud_cover'])
unscaled.insert(119, 'STOCKHOLM_humidity', unscaled['OSLO_humidity'])
unscaled.insert(94,'MUNCHENB_pressure',unscaled['BASEL_pressure'])

In [28]:
unscaled.columns.tolist()

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_cloud_cover',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_pressure',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_humidity',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [29]:
unscaled.shape

(22950, 137)

In [30]:
# Export cleaned dataset with date & month columns
unscaled.to_csv(os.path.join(path, 'Data Sets', 'weather_cleaned_with_date.csv'), index=False)

In [31]:
# Drop unnecessary columns
unscaled.drop(['DATE', 'MONTH'], axis=1, inplace=True)

In [32]:
# confirm drop
unscaled.shape

(22950, 135)

In [33]:

prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
# drop unneeded column from second dataset
prediction.drop(columns = 'DATE', inplace = True)

In [35]:
prediction.shape

(22950, 15)

In [36]:
# Export cleaned dataset
unscaled.to_csv(os.path.join(path, 'Data Sets', 'weather_cleaned.csv'), index=False)

### Data Reshaping

In [38]:
# Turn X and answers from a df to arrays

X = np.array(unscaled)
y = np.array(prediction)

In [39]:
X = X.reshape(-1,15,9)

In [40]:
# Use argmax to transform y

y =  np.argmax(y, axis = 1)
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
y.shape

(22950,)

In [42]:
# Verify Shape
X.shape

(22950, 15, 9)

In [43]:
# Verify Shape
y.shape

(22950,)

In [44]:
# Check y layout

from sklearn.utils.multiclass import type_of_target
type_of_target(y)

'multiclass'

### Data Split

In [46]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [47]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212,)
(5738, 15, 9) (5738,)

## Hyperparameter Optimization

### Bayesian

In [50]:
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15 # Number of weather stations
# Make scorer accuracy
score_acc = make_scorer(accuracy_score)

In [51]:
# Create function

def bay_area(neurons, activation, kernel, optimizer, learning_rate, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','SGD']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]  #optimizerD[optimizerL[round(optimizer)]]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def cnn_model():
        model = Sequential()
        model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(timesteps, input_dim)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(MaxPooling1D())
        model.add(Flatten())
        model.add(Dense(n_classes, activation='softmax')) #sigmoid softmax
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=cnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
    score = cross_val_score(nn, X_train, y_train, scoring=score_acc, cv=kfold, params={'callbacks':[es]}).mean()
    return score

In [52]:
start = time.time()
params ={
    'neurons': (10, 100),
    'kernel': (1, 3),
    'activation':(0, 9), 
    'optimizer':(0,7),
    'learning_rate':(0.01, 1),
    'batch_size': (200, 1000), 
    'epochs':(20, 50),
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}
# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=42)
nn_opt.maximize(init_points=15, n_iter=4) 
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   | activa... | batch_... |  dropout  | dropou... |  epochs   |  kernel   |  layers1  |  layers2  | learni... |  neurons  | normal... | optimizer |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Epoch 1/25

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 3s - 204ms/step - accuracy: 0.5985 - loss: 2.7134
Epoch 2/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6971
Epoch 4/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6942
Epoch 5/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6917
Epoch 6/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6894
Epoch 7/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6873
Epoch 8/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6853
Epoch 9/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6834
Epoch 10/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6816
Epoch 11/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6799
Epoch 12/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6783
Epoch 13/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6767
Epoch 14/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6751
Epoch 15/25
15/15 - 1s - 45ms/step - accuracy: 0.6440 - loss: 2.6736
Epoch 16/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6722
Epoch 17/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6707
Epoch 18/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6692
Epoch 19/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6678
Epoch 20/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6664
Epoch 21/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6650
Epoch 22/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6635
Epoch 23/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6621
Epoch 24/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6606
Epoch 25/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6592
4/4 - 0s - 40ms/step
Epoch 1/25

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 137ms/step - accuracy: 0.6012 - loss: 2.7103
Epoch 2/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6970
Epoch 4/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6941
Epoch 5/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6916
Epoch 6/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6893
Epoch 7/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6871
Epoch 8/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6851
Epoch 9/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6832
Epoch 10/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6814
Epoch 11/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6797
Epoch 12/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6780
Epoch 13/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6763
Epoch 14/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6747
Epoch 15/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6732
Epoch 16/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6716
Epoch 17/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6701
Epoch 18/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6686
Epoch 19/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6671
Epoch 20/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6656
Epoch 21/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6641
Epoch 22/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6625
Epoch 23/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6610
Epoch 24/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.6594
Epoch 25/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6578
4/4 - 0s - 48ms/step
Epoch 1/25

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 142ms/step - accuracy: 0.5993 - loss: 2.7093
Epoch 2/25
15/15 - 0s - 29ms/step - accuracy: 0.6439 - loss: 2.7004
Epoch 3/25
15/15 - 0s - 29ms/step - accuracy: 0.6439 - loss: 2.6970
Epoch 4/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6942
Epoch 5/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6917
Epoch 6/25
15/15 - 0s - 33ms/step - accuracy: 0.6439 - loss: 2.6894
Epoch 7/25
15/15 - 1s - 35ms/step - accuracy: 0.6439 - loss: 2.6873
Epoch 8/25
15/15 - 1s - 36ms/step - accuracy: 0.6439 - loss: 2.6853
Epoch 9/25
15/15 - 1s - 35ms/step - accuracy: 0.6439 - loss: 2.6835
Epoch 10/25
15/15 - 1s - 36ms/step - accuracy: 0.6439 - loss: 2.6817
Epoch 11/25
15/15 - 1s - 35ms/step - accuracy: 0.6439 - loss: 2.6800
Epoch 12/25
15/15 - 1s - 36ms/step - accuracy: 0.6439 - loss: 2.6784
Epoch 13/25
15/15 - 1s - 36ms/step - accuracy: 0.6439 - loss: 2.6768
Epoch 14/25
15/15 - 1s - 35ms/step - accuracy: 0.6439 - loss: 2.6753
Epoch 15/25
15/15 - 1s - 34ms/step - accuracy: 0.6439 - loss: 2.6738
Epoch 16/25
15/15 - 1s - 36ms/step - accuracy: 0.6439 - loss: 2.6723
Epoch 17/25
15/15 - 1s - 35ms/step - accuracy: 0.6439 - loss: 2.6709
Epoch 18/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6695
Epoch 19/25
15/15 - 1s - 46ms/step - accuracy: 0.6439 - loss: 2.6681
Epoch 20/25
15/15 - 0s - 32ms/step - accuracy: 0.6439 - loss: 2.6667
Epoch 21/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6653
Epoch 22/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6639
Epoch 23/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6625
Epoch 24/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6611
Epoch 25/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6596
WARNING:tensorflow:5 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000022FC10D2520> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 12 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000022FC10D2520> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
4/4 - 0s - 46ms/step
Epoch 1/25

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 135ms/step - accuracy: 0.6005 - loss: 2.7133
Epoch 2/25
15/15 - 0s - 29ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6971
Epoch 4/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6943
Epoch 5/25
15/15 - 0s - 31ms/step - accuracy: 0.6440 - loss: 2.6918
Epoch 6/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6895
Epoch 7/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6874
Epoch 8/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6855
Epoch 9/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6836
Epoch 10/25
15/15 - 1s - 34ms/step - accuracy: 0.6440 - loss: 2.6819
Epoch 11/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6802
Epoch 12/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6786
Epoch 13/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6771
Epoch 14/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6756
Epoch 15/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6741
Epoch 16/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6727
Epoch 17/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6713
Epoch 18/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6700
Epoch 19/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6686
Epoch 20/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6673
Epoch 21/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6660
Epoch 22/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6648
Epoch 23/25
15/15 - 0s - 33ms/step - accuracy: 0.6440 - loss: 2.6635
Epoch 24/25
15/15 - 0s - 32ms/step - accuracy: 0.6440 - loss: 2.6622
Epoch 25/25
15/15 - 0s - 30ms/step - accuracy: 0.6440 - loss: 2.6609
4/4 - 0s - 41ms/step
Epoch 1/25

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 2s - 138ms/step - accuracy: 0.5999 - loss: 2.7151
Epoch 2/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.7004
Epoch 3/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6971
Epoch 4/25
15/15 - 0s - 33ms/step - accuracy: 0.6439 - loss: 2.6943
Epoch 5/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6918
Epoch 6/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6895
Epoch 7/25
15/15 - 0s - 29ms/step - accuracy: 0.6439 - loss: 2.6874
Epoch 8/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6855
Epoch 9/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6836
Epoch 10/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6819
Epoch 11/25
15/15 - 0s - 29ms/step - accuracy: 0.6439 - loss: 2.6802
Epoch 12/25
15/15 - 0s - 29ms/step - accuracy: 0.6439 - loss: 2.6786
Epoch 13/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6771
Epoch 14/25
15/15 - 0s - 30ms/step - accuracy: 0.6439 - loss: 2.6756
Epoch 15/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6741
Epoch 16/25
15/15 - 1s - 34ms/step - accuracy: 0.6439 - loss: 2.6727
Epoch 17/25
15/15 - 1s - 33ms/step - accuracy: 0.6439 - loss: 2.6714
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6700
Epoch 19/25
15/15 - 1s - 34ms/step - accuracy: 0.6439 - loss: 2.6687
Epoch 20/25
15/15 - 0s - 32ms/step - accuracy: 0.6439 - loss: 2.6674
Epoch 21/25
15/15 - 0s - 32ms/step - accuracy: 0.6439 - loss: 2.6661
Epoch 22/25
15/15 - 0s - 32ms/step - accuracy: 0.6439 - loss: 2.6649
Epoch 23/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6636
Epoch 24/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6623
Epoch 25/25
15/15 - 0s - 31ms/step - accuracy: 0.6439 - loss: 2.6611
4/4 - 0s - 52ms/step
| 1         | 0.644     | 3.371     | 960.6     | 0.732     | 0.1796    | 24.68     | 1.312     | 1.116     | 2.732     | 0.6051    | 73.73     | 0.02058   | 6.789     |
Epoch 1/29

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 1s - 36ms/step - accuracy: 0.6278 - loss: nan
Epoch 2/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 15ms/step
Epoch 1/29

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 2s - 40ms/step - accuracy: 0.6282 - loss: nan
Epoch 2/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 14ms/step
Epoch 1/29

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 1s - 35ms/step - accuracy: 0.6326 - loss: nan
Epoch 2/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/29
38/38 - 0s - 6ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/29
38/38 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/29
38/38 - 0s - 4ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/29
38/38 - 0s - 4ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/29
38/38 - 0s - 4ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/29
38/38 - 0s - 4ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/29
38/38 - 0s - 6ms/step - accuracy: 0.6439 - loss: nan
Epoch 28/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 29/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
10/10 - 0s - 15ms/step
Epoch 1/29

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 2s - 42ms/step - accuracy: 0.6275 - loss: nan
Epoch 2/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 7ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 6ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 19ms/step
Epoch 1/29

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 2s - 46ms/step - accuracy: 0.6267 - loss: nan
Epoch 2/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/29
38/38 - 0s - 6ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/29
38/38 - 0s - 7ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 28/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
Epoch 29/29
38/38 - 0s - 5ms/step - accuracy: 0.6439 - loss: nan
10/10 - 0s - 17ms/step
| 2         | 0.644     | 7.492     | 369.9     | 0.1818    | 0.05502   | 29.13     | 2.05      | 1.864     | 1.582     | 0.6157    | 22.55     | 0.2921    | 2.565     |
Epoch 1/38

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 177ms/step - accuracy: 0.6064 - loss: 1.3386
Epoch 2/38
17/17 - 1s - 38ms/step - accuracy: 0.6958 - loss: 0.8920
Epoch 3/38
17/17 - 1s - 33ms/step - accuracy: 0.7288 - loss: 0.7978
Epoch 4/38
17/17 - 1s - 38ms/step - accuracy: 0.7529 - loss: 0.7353
Epoch 5/38
17/17 - 1s - 38ms/step - accuracy: 0.7704 - loss: 0.6850
Epoch 6/38
17/17 - 1s - 40ms/step - accuracy: 0.7854 - loss: 0.6408
Epoch 7/38
17/17 - 1s - 36ms/step - accuracy: 0.8014 - loss: 0.5974
Epoch 8/38
17/17 - 1s - 41ms/step - accuracy: 0.8104 - loss: 0.5583
Epoch 9/38
17/17 - 1s - 44ms/step - accuracy: 0.8200 - loss: 0.5237
Epoch 10/38
17/17 - 1s - 48ms/step - accuracy: 0.8293 - loss: 0.4959
Epoch 11/38
17/17 - 1s - 40ms/step - accuracy: 0.8404 - loss: 0.4653
Epoch 12/38
17/17 - 1s - 38ms/step - accuracy: 0.8485 - loss: 0.4376
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8586 - loss: 0.4121
Epoch 14/38
17/17 - 1s - 45ms/step - accuracy: 0.8664 - loss: 0.3920
Epoch 15/38
17/17 - 1s - 35ms/step - accuracy: 0.8680 - loss: 0.3766
Epoch 16/38
17/17 - 1s - 37ms/step - accuracy: 0.8795 - loss: 0.3577
Epoch 17/38
17/17 - 1s - 35ms/step - accuracy: 0.8821 - loss: 0.3433
Epoch 18/38
17/17 - 1s - 42ms/step - accuracy: 0.8912 - loss: 0.3256
Epoch 19/38
17/17 - 1s - 44ms/step - accuracy: 0.8928 - loss: 0.3152
Epoch 20/38
17/17 - 1s - 45ms/step - accuracy: 0.8999 - loss: 0.2962
Epoch 21/38
17/17 - 1s - 45ms/step - accuracy: 0.8988 - loss: 0.2991
Epoch 22/38
17/17 - 1s - 42ms/step - accuracy: 0.9051 - loss: 0.2836
Epoch 23/38
17/17 - 1s - 36ms/step - accuracy: 0.9097 - loss: 0.2738
Epoch 24/38
17/17 - 1s - 35ms/step - accuracy: 0.9117 - loss: 0.2665
Epoch 25/38
17/17 - 1s - 34ms/step - accuracy: 0.9171 - loss: 0.2527
Epoch 26/38
17/17 - 1s - 46ms/step - accuracy: 0.9049 - loss: 0.2812
Epoch 27/38
17/17 - 1s - 44ms/step - accuracy: 0.9188 - loss: 0.2464
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9210 - loss: 0.2392
Epoch 29/38
17/17 - 1s - 35ms/step - accuracy: 0.9221 - loss: 0.2326
Epoch 30/38
17/17 - 1s - 37ms/step - accuracy: 0.9231 - loss: 0.2296
Epoch 31/38
17/17 - 1s - 38ms/step - accuracy: 0.9291 - loss: 0.2143
Epoch 32/38
17/17 - 1s - 46ms/step - accuracy: 0.9259 - loss: 0.2239
Epoch 33/38
17/17 - 1s - 44ms/step - accuracy: 0.9311 - loss: 0.2114
Epoch 34/38
17/17 - 1s - 37ms/step - accuracy: 0.9333 - loss: 0.2039
Epoch 35/38
17/17 - 1s - 40ms/step - accuracy: 0.9345 - loss: 0.2017
Epoch 36/38
17/17 - 1s - 47ms/step - accuracy: 0.9234 - loss: 0.2257
Epoch 37/38
17/17 - 1s - 38ms/step - accuracy: 0.9336 - loss: 0.1965
Epoch 38/38
17/17 - 1s - 37ms/step - accuracy: 0.9396 - loss: 0.1860
5/5 - 0s - 42ms/step
Epoch 1/38

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 176ms/step - accuracy: 0.5768 - loss: 1.4456
Epoch 2/38
17/17 - 1s - 37ms/step - accuracy: 0.7089 - loss: 0.8689
Epoch 3/38
17/17 - 1s - 36ms/step - accuracy: 0.7408 - loss: 0.7735
Epoch 4/38
17/17 - 1s - 34ms/step - accuracy: 0.7618 - loss: 0.7098
Epoch 5/38
17/17 - 1s - 38ms/step - accuracy: 0.7766 - loss: 0.6638
Epoch 6/38
17/17 - 1s - 34ms/step - accuracy: 0.7868 - loss: 0.6264
Epoch 7/38
17/17 - 1s - 33ms/step - accuracy: 0.7980 - loss: 0.5911
Epoch 8/38
17/17 - 1s - 33ms/step - accuracy: 0.8086 - loss: 0.5571
Epoch 9/38
17/17 - 1s - 36ms/step - accuracy: 0.8197 - loss: 0.5225
Epoch 10/38
17/17 - 1s - 37ms/step - accuracy: 0.8292 - loss: 0.4942
Epoch 11/38
17/17 - 1s - 37ms/step - accuracy: 0.8377 - loss: 0.4671
Epoch 12/38
17/17 - 1s - 36ms/step - accuracy: 0.8461 - loss: 0.4435
Epoch 13/38
17/17 - 1s - 40ms/step - accuracy: 0.8555 - loss: 0.4186
Epoch 14/38
17/17 - 1s - 44ms/step - accuracy: 0.8632 - loss: 0.3977
Epoch 15/38
17/17 - 1s - 39ms/step - accuracy: 0.8698 - loss: 0.3775
Epoch 16/38
17/17 - 1s - 42ms/step - accuracy: 0.8783 - loss: 0.3605
Epoch 17/38
17/17 - 1s - 41ms/step - accuracy: 0.8813 - loss: 0.3466
Epoch 18/38
17/17 - 1s - 41ms/step - accuracy: 0.8852 - loss: 0.3357
Epoch 19/38
17/17 - 1s - 39ms/step - accuracy: 0.8870 - loss: 0.3280
Epoch 20/38
17/17 - 1s - 45ms/step - accuracy: 0.8994 - loss: 0.3033
Epoch 21/38
17/17 - 1s - 36ms/step - accuracy: 0.8919 - loss: 0.3118
Epoch 22/38
17/17 - 1s - 37ms/step - accuracy: 0.8898 - loss: 0.3142
Epoch 23/38
17/17 - 1s - 37ms/step - accuracy: 0.8985 - loss: 0.2951
Epoch 24/38
17/17 - 1s - 37ms/step - accuracy: 0.9004 - loss: 0.2907
Epoch 25/38
17/17 - 1s - 39ms/step - accuracy: 0.9078 - loss: 0.2686
Epoch 26/38
17/17 - 1s - 35ms/step - accuracy: 0.9098 - loss: 0.2659
Epoch 27/38
17/17 - 1s - 36ms/step - accuracy: 0.9110 - loss: 0.2606
Epoch 28/38
17/17 - 1s - 34ms/step - accuracy: 0.9089 - loss: 0.2645
Epoch 29/38
17/17 - 1s - 34ms/step - accuracy: 0.9139 - loss: 0.2511
Epoch 30/38
17/17 - 1s - 38ms/step - accuracy: 0.9170 - loss: 0.2470
Epoch 31/38
17/17 - 1s - 39ms/step - accuracy: 0.9147 - loss: 0.2499
Epoch 32/38
17/17 - 1s - 38ms/step - accuracy: 0.9174 - loss: 0.2362
Epoch 33/38
17/17 - 1s - 37ms/step - accuracy: 0.9259 - loss: 0.2237
Epoch 34/38
17/17 - 1s - 41ms/step - accuracy: 0.9242 - loss: 0.2303
Epoch 35/38
17/17 - 1s - 35ms/step - accuracy: 0.9255 - loss: 0.2214
Epoch 36/38
17/17 - 1s - 39ms/step - accuracy: 0.9257 - loss: 0.2168
Epoch 37/38
17/17 - 1s - 35ms/step - accuracy: 0.9273 - loss: 0.2145
Epoch 38/38
17/17 - 1s - 37ms/step - accuracy: 0.9343 - loss: 0.1998
5/5 - 0s - 58ms/step
Epoch 1/38

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 163ms/step - accuracy: 0.5562 - loss: 1.4955
Epoch 2/38
17/17 - 1s - 33ms/step - accuracy: 0.6941 - loss: 0.9016
Epoch 3/38
17/17 - 1s - 35ms/step - accuracy: 0.7239 - loss: 0.8060
Epoch 4/38
17/17 - 1s - 41ms/step - accuracy: 0.7481 - loss: 0.7428
Epoch 5/38
17/17 - 1s - 44ms/step - accuracy: 0.7651 - loss: 0.6897
Epoch 6/38
17/17 - 1s - 47ms/step - accuracy: 0.7842 - loss: 0.6389
Epoch 7/38
17/17 - 1s - 38ms/step - accuracy: 0.7956 - loss: 0.5956
Epoch 8/38
17/17 - 1s - 38ms/step - accuracy: 0.8078 - loss: 0.5545
Epoch 9/38
17/17 - 1s - 36ms/step - accuracy: 0.8207 - loss: 0.5188
Epoch 10/38
17/17 - 1s - 34ms/step - accuracy: 0.8305 - loss: 0.4873
Epoch 11/38
17/17 - 1s - 40ms/step - accuracy: 0.8424 - loss: 0.4603
Epoch 12/38
17/17 - 1s - 36ms/step - accuracy: 0.8482 - loss: 0.4374
Epoch 13/38
17/17 - 1s - 38ms/step - accuracy: 0.8596 - loss: 0.4101
Epoch 14/38
17/17 - 1s - 36ms/step - accuracy: 0.8627 - loss: 0.3948
Epoch 15/38
17/17 - 1s - 38ms/step - accuracy: 0.8696 - loss: 0.3767
Epoch 16/38
17/17 - 1s - 34ms/step - accuracy: 0.8785 - loss: 0.3572
Epoch 17/38
17/17 - 1s - 39ms/step - accuracy: 0.8815 - loss: 0.3460
Epoch 18/38
17/17 - 1s - 38ms/step - accuracy: 0.8813 - loss: 0.3418
Epoch 19/38
17/17 - 1s - 37ms/step - accuracy: 0.8891 - loss: 0.3235
Epoch 20/38
17/17 - 1s - 36ms/step - accuracy: 0.8926 - loss: 0.3119
Epoch 21/38
17/17 - 1s - 36ms/step - accuracy: 0.8958 - loss: 0.3029
Epoch 22/38
17/17 - 1s - 37ms/step - accuracy: 0.9009 - loss: 0.2889
Epoch 23/38
17/17 - 1s - 40ms/step - accuracy: 0.8991 - loss: 0.2949
Epoch 24/38
17/17 - 1s - 40ms/step - accuracy: 0.9058 - loss: 0.2756
Epoch 25/38
17/17 - 1s - 38ms/step - accuracy: 0.9044 - loss: 0.2811
Epoch 26/38
17/17 - 1s - 38ms/step - accuracy: 0.9074 - loss: 0.2686
Epoch 27/38
17/17 - 1s - 41ms/step - accuracy: 0.9147 - loss: 0.2528
Epoch 28/38
17/17 - 1s - 36ms/step - accuracy: 0.9159 - loss: 0.2528
Epoch 29/38
17/17 - 1s - 37ms/step - accuracy: 0.9150 - loss: 0.2511
Epoch 30/38
17/17 - 1s - 46ms/step - accuracy: 0.9142 - loss: 0.2511
Epoch 31/38
17/17 - 1s - 39ms/step - accuracy: 0.9248 - loss: 0.2259
Epoch 32/38
17/17 - 1s - 38ms/step - accuracy: 0.9245 - loss: 0.2287
Epoch 33/38
17/17 - 1s - 44ms/step - accuracy: 0.9232 - loss: 0.2261
Epoch 34/38
17/17 - 1s - 36ms/step - accuracy: 0.9227 - loss: 0.2288
Epoch 35/38
17/17 - 1s - 44ms/step - accuracy: 0.9274 - loss: 0.2158
Epoch 36/38
17/17 - 1s - 41ms/step - accuracy: 0.9294 - loss: 0.2109
Epoch 37/38
17/17 - 1s - 45ms/step - accuracy: 0.9294 - loss: 0.2080
Epoch 38/38
17/17 - 1s - 38ms/step - accuracy: 0.9312 - loss: 0.2052
5/5 - 0s - 39ms/step
Epoch 1/38

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 4s - 207ms/step - accuracy: 0.5722 - loss: 1.4616
Epoch 2/38
17/17 - 1s - 34ms/step - accuracy: 0.6982 - loss: 0.8941
Epoch 3/38
17/17 - 1s - 31ms/step - accuracy: 0.7338 - loss: 0.7915
Epoch 4/38
17/17 - 1s - 37ms/step - accuracy: 0.7562 - loss: 0.7271
Epoch 5/38
17/17 - 1s - 36ms/step - accuracy: 0.7709 - loss: 0.6844
Epoch 6/38
17/17 - 1s - 36ms/step - accuracy: 0.7819 - loss: 0.6488
Epoch 7/38
17/17 - 1s - 36ms/step - accuracy: 0.7883 - loss: 0.6178
Epoch 8/38
17/17 - 1s - 38ms/step - accuracy: 0.7962 - loss: 0.5864
Epoch 9/38
17/17 - 1s - 34ms/step - accuracy: 0.8073 - loss: 0.5553
Epoch 10/38
17/17 - 1s - 33ms/step - accuracy: 0.8180 - loss: 0.5210
Epoch 11/38
17/17 - 1s - 36ms/step - accuracy: 0.8269 - loss: 0.4882
Epoch 12/38
17/17 - 1s - 37ms/step - accuracy: 0.8355 - loss: 0.4642
Epoch 13/38
17/17 - 1s - 38ms/step - accuracy: 0.8450 - loss: 0.4366
Epoch 14/38
17/17 - 1s - 43ms/step - accuracy: 0.8557 - loss: 0.4092
Epoch 15/38
17/17 - 1s - 47ms/step - accuracy: 0.8659 - loss: 0.3888
Epoch 16/38
17/17 - 1s - 46ms/step - accuracy: 0.8701 - loss: 0.3740
Epoch 17/38
17/17 - 1s - 38ms/step - accuracy: 0.8747 - loss: 0.3553
Epoch 18/38
17/17 - 1s - 34ms/step - accuracy: 0.8806 - loss: 0.3458
Epoch 19/38
17/17 - 1s - 40ms/step - accuracy: 0.8879 - loss: 0.3325
Epoch 20/38
17/17 - 1s - 46ms/step - accuracy: 0.8901 - loss: 0.3207
Epoch 21/38
17/17 - 1s - 46ms/step - accuracy: 0.8951 - loss: 0.3052
Epoch 22/38
17/17 - 1s - 46ms/step - accuracy: 0.8992 - loss: 0.2914
Epoch 23/38
17/17 - 1s - 35ms/step - accuracy: 0.9054 - loss: 0.2827
Epoch 24/38
17/17 - 1s - 47ms/step - accuracy: 0.9076 - loss: 0.2798
Epoch 25/38
17/17 - 1s - 46ms/step - accuracy: 0.9070 - loss: 0.2706
Epoch 26/38
17/17 - 1s - 38ms/step - accuracy: 0.9062 - loss: 0.2749
Epoch 27/38
17/17 - 1s - 33ms/step - accuracy: 0.9168 - loss: 0.2484
Epoch 28/38
17/17 - 1s - 37ms/step - accuracy: 0.9165 - loss: 0.2457
Epoch 29/38
17/17 - 1s - 40ms/step - accuracy: 0.9211 - loss: 0.2377
Epoch 30/38
17/17 - 1s - 36ms/step - accuracy: 0.9155 - loss: 0.2474
Epoch 31/38
17/17 - 1s - 35ms/step - accuracy: 0.9243 - loss: 0.2256
Epoch 32/38
17/17 - 1s - 38ms/step - accuracy: 0.9190 - loss: 0.2425
Epoch 33/38
17/17 - 1s - 35ms/step - accuracy: 0.9238 - loss: 0.2303
Epoch 34/38
17/17 - 1s - 34ms/step - accuracy: 0.9290 - loss: 0.2186
Epoch 35/38
17/17 - 1s - 34ms/step - accuracy: 0.9302 - loss: 0.2071
Epoch 36/38
17/17 - 1s - 43ms/step - accuracy: 0.9335 - loss: 0.2003
Epoch 37/38
17/17 - 1s - 38ms/step - accuracy: 0.9321 - loss: 0.2036
Epoch 38/38
17/17 - 1s - 34ms/step - accuracy: 0.9351 - loss: 0.1973
5/5 - 0s - 46ms/step
Epoch 1/38

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 178ms/step - accuracy: 0.5269 - loss: 1.5742
Epoch 2/38
17/17 - 1s - 37ms/step - accuracy: 0.6829 - loss: 0.9241
Epoch 3/38
17/17 - 1s - 37ms/step - accuracy: 0.7214 - loss: 0.8191
Epoch 4/38
17/17 - 1s - 47ms/step - accuracy: 0.7418 - loss: 0.7551
Epoch 5/38
17/17 - 1s - 47ms/step - accuracy: 0.7587 - loss: 0.7063
Epoch 6/38
17/17 - 1s - 40ms/step - accuracy: 0.7730 - loss: 0.6668
Epoch 7/38
17/17 - 1s - 35ms/step - accuracy: 0.7804 - loss: 0.6319
Epoch 8/38
17/17 - 1s - 43ms/step - accuracy: 0.7900 - loss: 0.5982
Epoch 9/38
17/17 - 1s - 40ms/step - accuracy: 0.8027 - loss: 0.5642
Epoch 10/38
17/17 - 1s - 39ms/step - accuracy: 0.8105 - loss: 0.5330
Epoch 11/38
17/17 - 1s - 44ms/step - accuracy: 0.8232 - loss: 0.5015
Epoch 12/38
17/17 - 1s - 39ms/step - accuracy: 0.8306 - loss: 0.4767
Epoch 13/38
17/17 - 1s - 38ms/step - accuracy: 0.8375 - loss: 0.4534
Epoch 14/38
17/17 - 1s - 40ms/step - accuracy: 0.8492 - loss: 0.4254
Epoch 15/38
17/17 - 1s - 40ms/step - accuracy: 0.8568 - loss: 0.4066
Epoch 16/38
17/17 - 1s - 39ms/step - accuracy: 0.8634 - loss: 0.3876
Epoch 17/38
17/17 - 1s - 35ms/step - accuracy: 0.8696 - loss: 0.3712
Epoch 18/38
17/17 - 1s - 35ms/step - accuracy: 0.8773 - loss: 0.3494
Epoch 19/38
17/17 - 1s - 39ms/step - accuracy: 0.8781 - loss: 0.3453
Epoch 20/38
17/17 - 1s - 47ms/step - accuracy: 0.8832 - loss: 0.3315
Epoch 21/38
17/17 - 1s - 46ms/step - accuracy: 0.8895 - loss: 0.3170
Epoch 22/38
17/17 - 1s - 38ms/step - accuracy: 0.8957 - loss: 0.3046
Epoch 23/38
17/17 - 1s - 37ms/step - accuracy: 0.9038 - loss: 0.2870
Epoch 24/38
17/17 - 1s - 37ms/step - accuracy: 0.9046 - loss: 0.2797
Epoch 25/38
17/17 - 1s - 38ms/step - accuracy: 0.9033 - loss: 0.2861
Epoch 26/38
17/17 - 1s - 34ms/step - accuracy: 0.9132 - loss: 0.2609
Epoch 27/38
17/17 - 1s - 43ms/step - accuracy: 0.9071 - loss: 0.2719
Epoch 28/38
17/17 - 1s - 35ms/step - accuracy: 0.9140 - loss: 0.2529
Epoch 29/38
17/17 - 1s - 45ms/step - accuracy: 0.9194 - loss: 0.2424
Epoch 30/38
17/17 - 1s - 45ms/step - accuracy: 0.9195 - loss: 0.2396
Epoch 31/38
17/17 - 1s - 34ms/step - accuracy: 0.9189 - loss: 0.2397
Epoch 32/38
17/17 - 1s - 36ms/step - accuracy: 0.9243 - loss: 0.2266
Epoch 33/38
17/17 - 1s - 36ms/step - accuracy: 0.9200 - loss: 0.2408
Epoch 34/38
17/17 - 1s - 35ms/step - accuracy: 0.9237 - loss: 0.2254
Epoch 35/38
17/17 - 1s - 35ms/step - accuracy: 0.9261 - loss: 0.2171
Epoch 36/38
17/17 - 1s - 35ms/step - accuracy: 0.9322 - loss: 0.2025
Epoch 37/38
17/17 - 1s - 35ms/step - accuracy: 0.9316 - loss: 0.2016
Epoch 38/38
17/17 - 1s - 38ms/step - accuracy: 0.9227 - loss: 0.2254
5/5 - 0s - 43ms/step
| 3         | 0.8324    | 4.105     | 828.1     | 0.1997    | 0.1543    | 37.77     | 1.093     | 2.215     | 1.341     | 0.0744    | 95.4      | 0.9656    | 5.659     |
Epoch 1/24

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 2s - 32ms/step - accuracy: 0.5901 - loss: 2.2747
Epoch 2/24
50/50 - 1s - 13ms/step - accuracy: 0.6415 - loss: 1.8095
Epoch 3/24
50/50 - 1s - 13ms/step - accuracy: 0.6436 - loss: 1.5367
Epoch 4/24
50/50 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.3896
Epoch 5/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.3069
Epoch 6/24
50/50 - 1s - 13ms/step - accuracy: 0.6440 - loss: 1.2547
Epoch 7/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.2205
Epoch 8/24
50/50 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1970
Epoch 9/24
50/50 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1780
Epoch 10/24
50/50 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1630
Epoch 11/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1506
Epoch 12/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1405
Epoch 13/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1314
Epoch 14/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1232
Epoch 15/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1162
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1102
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1036
Epoch 18/24
50/50 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.0987
Epoch 19/24
50/50 - 1s - 12ms/step - accuracy: 0.6442 - loss: 1.0944
Epoch 20/24
50/50 - 1s - 12ms/step - accuracy: 0.6441 - loss: 1.0896
Epoch 21/24
50/50 - 1s - 12ms/step - accuracy: 0.6446 - loss: 1.0860
Epoch 22/24
50/50 - 1s - 13ms/step - accuracy: 0.6443 - loss: 1.0818
Epoch 23/24
50/50 - 1s - 13ms/step - accuracy: 0.6445 - loss: 1.0781
Epoch 24/24
50/50 - 1s - 12ms/step - accuracy: 0.6449 - loss: 1.0751
13/13 - 0s - 17ms/step
Epoch 1/24

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 2s - 34ms/step - accuracy: 0.4174 - loss: 2.3990
Epoch 2/24
50/50 - 1s - 13ms/step - accuracy: 0.6422 - loss: 1.8780
Epoch 3/24
50/50 - 0s - 10ms/step - accuracy: 0.6432 - loss: 1.5643
Epoch 4/24
50/50 - 0s - 9ms/step - accuracy: 0.6434 - loss: 1.3928
Epoch 5/24
50/50 - 0s - 9ms/step - accuracy: 0.6438 - loss: 1.3006
Epoch 6/24
50/50 - 0s - 9ms/step - accuracy: 0.6437 - loss: 1.2465
Epoch 7/24
50/50 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.2103
Epoch 8/24
50/50 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1861
Epoch 9/24
50/50 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1677
Epoch 10/24
50/50 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1527
Epoch 11/24
50/50 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1410
Epoch 12/24
50/50 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1315
Epoch 13/24
50/50 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1230
Epoch 14/24
50/50 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1155
Epoch 15/24
50/50 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1085
Epoch 16/24
50/50 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1031
Epoch 17/24
50/50 - 0s - 10ms/step - accuracy: 0.6441 - loss: 1.0979
Epoch 18/24
50/50 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.0932
Epoch 19/24
50/50 - 1s - 11ms/step - accuracy: 0.6445 - loss: 1.0890
Epoch 20/24
50/50 - 1s - 14ms/step - accuracy: 0.6444 - loss: 1.0849
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6449 - loss: 1.0811
Epoch 22/24
50/50 - 1s - 14ms/step - accuracy: 0.6443 - loss: 1.0778
Epoch 23/24
50/50 - 1s - 10ms/step - accuracy: 0.6443 - loss: 1.0747
Epoch 24/24
50/50 - 1s - 14ms/step - accuracy: 0.6449 - loss: 1.0705
13/13 - 0s - 15ms/step
Epoch 1/24

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 2s - 38ms/step - accuracy: 0.5068 - loss: 2.3698
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6418 - loss: 1.8719
Epoch 3/24
50/50 - 1s - 12ms/step - accuracy: 0.6435 - loss: 1.5495
Epoch 4/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.3824
Epoch 5/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.2971
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.2482
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.2168
Epoch 8/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1942
Epoch 9/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1769
Epoch 10/24
50/50 - 1s - 13ms/step - accuracy: 0.6439 - loss: 1.1630
Epoch 11/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1519
Epoch 12/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1416
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1336
Epoch 14/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1264
Epoch 15/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1200
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1137
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1087
Epoch 18/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1038
Epoch 19/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.0999
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.0960
Epoch 21/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.0919
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.0887
Epoch 23/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.0854
Epoch 24/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.0824
13/13 - 0s - 16ms/step
Epoch 1/24

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 27ms/step - accuracy: 0.3247 - loss: 2.5456
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6285 - loss: 2.0600
Epoch 3/24
50/50 - 1s - 14ms/step - accuracy: 0.6390 - loss: 1.7164
Epoch 4/24
50/50 - 1s - 13ms/step - accuracy: 0.6427 - loss: 1.5071
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6436 - loss: 1.3894
Epoch 6/24
50/50 - 1s - 14ms/step - accuracy: 0.6439 - loss: 1.3186
Epoch 7/24
50/50 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.2708
Epoch 8/24
50/50 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.2364
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.2118
Epoch 10/24
50/50 - 1s - 14ms/step - accuracy: 0.6440 - loss: 1.1920
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1751
Epoch 12/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1615
Epoch 13/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1502
Epoch 14/24
50/50 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.1402
Epoch 15/24
50/50 - 1s - 13ms/step - accuracy: 0.6440 - loss: 1.1313
Epoch 16/24
50/50 - 1s - 13ms/step - accuracy: 0.6440 - loss: 1.1236
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1167
Epoch 18/24
50/50 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1104
Epoch 19/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1044
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0997
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0946
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.0898
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0856
Epoch 24/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.0816
13/13 - 0s - 15ms/step
Epoch 1/24

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 2s - 31ms/step - accuracy: 0.4078 - loss: 2.4674
Epoch 2/24
50/50 - 1s - 13ms/step - accuracy: 0.6383 - loss: 1.9615
Epoch 3/24
50/50 - 1s - 12ms/step - accuracy: 0.6414 - loss: 1.6531
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6428 - loss: 1.4736
Epoch 5/24
50/50 - 1s - 10ms/step - accuracy: 0.6435 - loss: 1.3694
Epoch 6/24
50/50 - 1s - 12ms/step - accuracy: 0.6438 - loss: 1.3035
Epoch 7/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.2582
Epoch 8/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.2254
Epoch 9/24
50/50 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.2004
Epoch 10/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1808
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1648
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1510
Epoch 13/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1405
Epoch 14/24
50/50 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.1310
Epoch 15/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1226
Epoch 16/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1158
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1097
Epoch 18/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1039
Epoch 19/24
50/50 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.0991
Epoch 20/24
50/50 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.0941
Epoch 21/24
50/50 - 1s - 13ms/step - accuracy: 0.6439 - loss: 1.0906
Epoch 22/24
50/50 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.0863
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.0830
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0799
13/13 - 0s - 21ms/step
| 4         | 0.6452    | 2.742     | 278.1     | 0.6842    | 0.132     | 23.66     | 1.99      | 1.069     | 2.819     | 0.2662    | 69.63     | 0.3117    | 3.64      |
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 2s - 38ms/step - accuracy: 0.5825 - loss: 1.3541
Epoch 2/48
40/40 - 0s - 7ms/step - accuracy: 0.6730 - loss: 0.9572
Epoch 3/48
40/40 - 0s - 7ms/step - accuracy: 0.6964 - loss: 0.8697
Epoch 4/48
40/40 - 0s - 7ms/step - accuracy: 0.7231 - loss: 0.8008
Epoch 5/48
40/40 - 0s - 7ms/step - accuracy: 0.7342 - loss: 0.7584
Epoch 6/48
40/40 - 0s - 7ms/step - accuracy: 0.7463 - loss: 0.7252
Epoch 7/48
40/40 - 0s - 8ms/step - accuracy: 0.7515 - loss: 0.6951
Epoch 8/48
40/40 - 0s - 8ms/step - accuracy: 0.7621 - loss: 0.6755
Epoch 9/48
40/40 - 0s - 7ms/step - accuracy: 0.7665 - loss: 0.6603
Epoch 10/48
40/40 - 0s - 7ms/step - accuracy: 0.7725 - loss: 0.6356
Epoch 11/48
40/40 - 0s - 7ms/step - accuracy: 0.7788 - loss: 0.6209
Epoch 12/48
40/40 - 0s - 6ms/step - accuracy: 0.7764 - loss: 0.6172
Epoch 13/48
40/40 - 0s - 7ms/step - accuracy: 0.7830 - loss: 0.6009
Epoch 14/48
40/40 - 0s - 7ms/step - accuracy: 0.7899 - loss: 0.5913
Epoch 15/48
40/40 - 0s - 8ms/step - accuracy: 0.7900 - loss: 0.5868
Epoch 16/48
40/40 - 0s - 7ms/step - accuracy: 0.7911 - loss: 0.5784
Epoch 17/48
40/40 - 0s - 7ms/step - accuracy: 0.7944 - loss: 0.5704
Epoch 18/48
40/40 - 0s - 7ms/step - accuracy: 0.7977 - loss: 0.5607
Epoch 19/48
40/40 - 0s - 7ms/step - accuracy: 0.8015 - loss: 0.5514
Epoch 20/48
40/40 - 0s - 8ms/step - accuracy: 0.7995 - loss: 0.5475
Epoch 21/48
40/40 - 0s - 7ms/step - accuracy: 0.8038 - loss: 0.5385
Epoch 22/48
40/40 - 0s - 7ms/step - accuracy: 0.8056 - loss: 0.5336
Epoch 23/48
40/40 - 0s - 7ms/step - accuracy: 0.8081 - loss: 0.5278
Epoch 24/48
40/40 - 0s - 7ms/step - accuracy: 0.8107 - loss: 0.5210
Epoch 25/48
40/40 - 0s - 7ms/step - accuracy: 0.8142 - loss: 0.5074
Epoch 26/48
40/40 - 0s - 7ms/step - accuracy: 0.8167 - loss: 0.5063
Epoch 27/48
40/40 - 0s - 7ms/step - accuracy: 0.8164 - loss: 0.5013
Epoch 28/48
40/40 - 0s - 7ms/step - accuracy: 0.8193 - loss: 0.4932
Epoch 29/48
40/40 - 0s - 7ms/step - accuracy: 0.8210 - loss: 0.4882
Epoch 30/48
40/40 - 0s - 7ms/step - accuracy: 0.8258 - loss: 0.4782
Epoch 31/48
40/40 - 0s - 7ms/step - accuracy: 0.8300 - loss: 0.4708
Epoch 32/48
40/40 - 0s - 7ms/step - accuracy: 0.8284 - loss: 0.4691
Epoch 33/48
40/40 - 0s - 7ms/step - accuracy: 0.8335 - loss: 0.4601
Epoch 34/48
40/40 - 0s - 7ms/step - accuracy: 0.8333 - loss: 0.4560
Epoch 35/48
40/40 - 0s - 7ms/step - accuracy: 0.8346 - loss: 0.4508
Epoch 36/48
40/40 - 0s - 7ms/step - accuracy: 0.8369 - loss: 0.4513
Epoch 37/48
40/40 - 0s - 7ms/step - accuracy: 0.8393 - loss: 0.4434
Epoch 38/48
40/40 - 0s - 7ms/step - accuracy: 0.8418 - loss: 0.4373
Epoch 39/48
40/40 - 0s - 7ms/step - accuracy: 0.8436 - loss: 0.4362
Epoch 40/48
40/40 - 0s - 7ms/step - accuracy: 0.8448 - loss: 0.4252
Epoch 41/48
40/40 - 0s - 7ms/step - accuracy: 0.8471 - loss: 0.4240
Epoch 42/48
40/40 - 0s - 7ms/step - accuracy: 0.8533 - loss: 0.4103
Epoch 43/48
40/40 - 0s - 7ms/step - accuracy: 0.8508 - loss: 0.4149
Epoch 44/48
40/40 - 0s - 9ms/step - accuracy: 0.8489 - loss: 0.4171
Epoch 45/48
40/40 - 0s - 8ms/step - accuracy: 0.8516 - loss: 0.4045
Epoch 46/48
40/40 - 0s - 8ms/step - accuracy: 0.8556 - loss: 0.4037
Epoch 47/48
40/40 - 0s - 8ms/step - accuracy: 0.8498 - loss: 0.4088
Epoch 48/48
40/40 - 0s - 8ms/step - accuracy: 0.8589 - loss: 0.3925
10/10 - 1s - 57ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 2s - 38ms/step - accuracy: 0.5797 - loss: 1.3545
Epoch 2/48
40/40 - 0s - 8ms/step - accuracy: 0.6631 - loss: 0.9777
Epoch 3/48
40/40 - 0s - 8ms/step - accuracy: 0.6999 - loss: 0.8768
Epoch 4/48
40/40 - 0s - 7ms/step - accuracy: 0.7154 - loss: 0.8256
Epoch 5/48
40/40 - 0s - 8ms/step - accuracy: 0.7285 - loss: 0.7845
Epoch 6/48
40/40 - 0s - 8ms/step - accuracy: 0.7391 - loss: 0.7488
Epoch 7/48
40/40 - 0s - 8ms/step - accuracy: 0.7499 - loss: 0.7149
Epoch 8/48
40/40 - 0s - 7ms/step - accuracy: 0.7523 - loss: 0.6985
Epoch 9/48
40/40 - 0s - 8ms/step - accuracy: 0.7631 - loss: 0.6719
Epoch 10/48
40/40 - 0s - 8ms/step - accuracy: 0.7682 - loss: 0.6577
Epoch 11/48
40/40 - 0s - 8ms/step - accuracy: 0.7694 - loss: 0.6482
Epoch 12/48
40/40 - 0s - 9ms/step - accuracy: 0.7762 - loss: 0.6307
Epoch 13/48
40/40 - 0s - 8ms/step - accuracy: 0.7751 - loss: 0.6181
Epoch 14/48
40/40 - 0s - 8ms/step - accuracy: 0.7829 - loss: 0.6034
Epoch 15/48
40/40 - 0s - 7ms/step - accuracy: 0.7844 - loss: 0.5943
Epoch 16/48
40/40 - 0s - 7ms/step - accuracy: 0.7929 - loss: 0.5862
Epoch 17/48
40/40 - 0s - 7ms/step - accuracy: 0.7888 - loss: 0.5816
Epoch 18/48
40/40 - 0s - 7ms/step - accuracy: 0.7928 - loss: 0.5711
Epoch 19/48
40/40 - 0s - 7ms/step - accuracy: 0.7962 - loss: 0.5659
Epoch 20/48
40/40 - 0s - 6ms/step - accuracy: 0.7958 - loss: 0.5585
Epoch 21/48
40/40 - 0s - 6ms/step - accuracy: 0.8019 - loss: 0.5510
Epoch 22/48
40/40 - 0s - 7ms/step - accuracy: 0.8028 - loss: 0.5421
Epoch 23/48
40/40 - 0s - 7ms/step - accuracy: 0.8060 - loss: 0.5379
Epoch 24/48
40/40 - 0s - 6ms/step - accuracy: 0.8087 - loss: 0.5304
Epoch 25/48
40/40 - 0s - 6ms/step - accuracy: 0.8141 - loss: 0.5216
Epoch 26/48
40/40 - 0s - 7ms/step - accuracy: 0.8129 - loss: 0.5143
Epoch 27/48
40/40 - 0s - 7ms/step - accuracy: 0.8152 - loss: 0.5093
Epoch 28/48
40/40 - 0s - 6ms/step - accuracy: 0.8165 - loss: 0.5059
Epoch 29/48
40/40 - 0s - 6ms/step - accuracy: 0.8204 - loss: 0.4954
Epoch 30/48
40/40 - 0s - 7ms/step - accuracy: 0.8196 - loss: 0.4912
Epoch 31/48
40/40 - 0s - 6ms/step - accuracy: 0.8215 - loss: 0.4887
Epoch 32/48
40/40 - 0s - 6ms/step - accuracy: 0.8232 - loss: 0.4847
Epoch 33/48
40/40 - 0s - 6ms/step - accuracy: 0.8247 - loss: 0.4784
Epoch 34/48
40/40 - 0s - 7ms/step - accuracy: 0.8280 - loss: 0.4735
Epoch 35/48
40/40 - 0s - 6ms/step - accuracy: 0.8300 - loss: 0.4623
Epoch 36/48
40/40 - 0s - 6ms/step - accuracy: 0.8279 - loss: 0.4630
Epoch 37/48
40/40 - 0s - 6ms/step - accuracy: 0.8366 - loss: 0.4528
Epoch 38/48
40/40 - 0s - 8ms/step - accuracy: 0.8346 - loss: 0.4546
Epoch 39/48
40/40 - 0s - 6ms/step - accuracy: 0.8368 - loss: 0.4421
Epoch 40/48
40/40 - 0s - 6ms/step - accuracy: 0.8386 - loss: 0.4411
Epoch 41/48
40/40 - 0s - 6ms/step - accuracy: 0.8409 - loss: 0.4357
Epoch 42/48
40/40 - 0s - 6ms/step - accuracy: 0.8407 - loss: 0.4326
Epoch 43/48
40/40 - 0s - 6ms/step - accuracy: 0.8449 - loss: 0.4285
Epoch 44/48
40/40 - 0s - 5ms/step - accuracy: 0.8465 - loss: 0.4251
Epoch 45/48
40/40 - 0s - 5ms/step - accuracy: 0.8462 - loss: 0.4215
Epoch 46/48
40/40 - 0s - 6ms/step - accuracy: 0.8516 - loss: 0.4100
Epoch 47/48
40/40 - 0s - 6ms/step - accuracy: 0.8503 - loss: 0.4124
Epoch 48/48
40/40 - 0s - 6ms/step - accuracy: 0.8519 - loss: 0.4052
10/10 - 0s - 25ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 1s - 34ms/step - accuracy: 0.5747 - loss: 1.4678
Epoch 2/48
40/40 - 0s - 6ms/step - accuracy: 0.6651 - loss: 0.9763
Epoch 3/48
40/40 - 0s - 6ms/step - accuracy: 0.6986 - loss: 0.8570
Epoch 4/48
40/40 - 0s - 6ms/step - accuracy: 0.7071 - loss: 0.8097
Epoch 5/48
40/40 - 0s - 7ms/step - accuracy: 0.7211 - loss: 0.7691
Epoch 6/48
40/40 - 0s - 7ms/step - accuracy: 0.7328 - loss: 0.7389
Epoch 7/48
40/40 - 0s - 6ms/step - accuracy: 0.7405 - loss: 0.7083
Epoch 8/48
40/40 - 0s - 6ms/step - accuracy: 0.7500 - loss: 0.6908
Epoch 9/48
40/40 - 0s - 6ms/step - accuracy: 0.7527 - loss: 0.6732
Epoch 10/48
40/40 - 0s - 7ms/step - accuracy: 0.7613 - loss: 0.6601
Epoch 11/48
40/40 - 0s - 7ms/step - accuracy: 0.7662 - loss: 0.6435
Epoch 12/48
40/40 - 0s - 6ms/step - accuracy: 0.7691 - loss: 0.6314
Epoch 13/48
40/40 - 0s - 6ms/step - accuracy: 0.7793 - loss: 0.6193
Epoch 14/48
40/40 - 0s - 6ms/step - accuracy: 0.7831 - loss: 0.6076
Epoch 15/48
40/40 - 0s - 7ms/step - accuracy: 0.7849 - loss: 0.5995
Epoch 16/48
40/40 - 0s - 7ms/step - accuracy: 0.7827 - loss: 0.5989
Epoch 17/48
40/40 - 0s - 8ms/step - accuracy: 0.7879 - loss: 0.5879
Epoch 18/48
40/40 - 0s - 8ms/step - accuracy: 0.7922 - loss: 0.5781
Epoch 19/48
40/40 - 0s - 7ms/step - accuracy: 0.7967 - loss: 0.5744
Epoch 20/48
40/40 - 0s - 7ms/step - accuracy: 0.7954 - loss: 0.5652
Epoch 21/48
40/40 - 0s - 6ms/step - accuracy: 0.7975 - loss: 0.5566
Epoch 22/48
40/40 - 0s - 8ms/step - accuracy: 0.8023 - loss: 0.5482
Epoch 23/48
40/40 - 0s - 7ms/step - accuracy: 0.8015 - loss: 0.5498
Epoch 24/48
40/40 - 0s - 8ms/step - accuracy: 0.8017 - loss: 0.5435
Epoch 25/48
40/40 - 0s - 7ms/step - accuracy: 0.8064 - loss: 0.5316
Epoch 26/48
40/40 - 0s - 7ms/step - accuracy: 0.8067 - loss: 0.5269
Epoch 27/48
40/40 - 0s - 6ms/step - accuracy: 0.8123 - loss: 0.5204
Epoch 28/48
40/40 - 0s - 7ms/step - accuracy: 0.8158 - loss: 0.5095
Epoch 29/48
40/40 - 0s - 7ms/step - accuracy: 0.8175 - loss: 0.5092
Epoch 30/48
40/40 - 0s - 7ms/step - accuracy: 0.8189 - loss: 0.5055
Epoch 31/48
40/40 - 0s - 6ms/step - accuracy: 0.8200 - loss: 0.4962
Epoch 32/48
40/40 - 0s - 7ms/step - accuracy: 0.8208 - loss: 0.4974
Epoch 33/48
40/40 - 0s - 7ms/step - accuracy: 0.8246 - loss: 0.4807
Epoch 34/48
40/40 - 0s - 6ms/step - accuracy: 0.8202 - loss: 0.4933
Epoch 35/48
40/40 - 0s - 6ms/step - accuracy: 0.8256 - loss: 0.4790
Epoch 36/48
40/40 - 0s - 6ms/step - accuracy: 0.8273 - loss: 0.4751
Epoch 37/48
40/40 - 0s - 6ms/step - accuracy: 0.8270 - loss: 0.4677
Epoch 38/48
40/40 - 0s - 6ms/step - accuracy: 0.8277 - loss: 0.4745
Epoch 39/48
40/40 - 0s - 6ms/step - accuracy: 0.8303 - loss: 0.4667
Epoch 40/48
40/40 - 0s - 7ms/step - accuracy: 0.8320 - loss: 0.4603
Epoch 41/48
40/40 - 0s - 7ms/step - accuracy: 0.8355 - loss: 0.4501
Epoch 42/48
40/40 - 0s - 6ms/step - accuracy: 0.8367 - loss: 0.4482
Epoch 43/48
40/40 - 0s - 6ms/step - accuracy: 0.8407 - loss: 0.4451
Epoch 44/48
40/40 - 0s - 6ms/step - accuracy: 0.8382 - loss: 0.4410
Epoch 45/48
40/40 - 0s - 6ms/step - accuracy: 0.8391 - loss: 0.4406
Epoch 46/48
40/40 - 0s - 7ms/step - accuracy: 0.8413 - loss: 0.4348
Epoch 47/48
40/40 - 0s - 6ms/step - accuracy: 0.8432 - loss: 0.4272
Epoch 48/48
40/40 - 0s - 7ms/step - accuracy: 0.8458 - loss: 0.4267
10/10 - 0s - 17ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 2s - 51ms/step - accuracy: 0.5991 - loss: 1.3216
Epoch 2/48
40/40 - 0s - 9ms/step - accuracy: 0.6558 - loss: 1.0046
Epoch 3/48
40/40 - 0s - 9ms/step - accuracy: 0.6808 - loss: 0.9027
Epoch 4/48
40/40 - 0s - 7ms/step - accuracy: 0.7044 - loss: 0.8295
Epoch 5/48
40/40 - 0s - 7ms/step - accuracy: 0.7211 - loss: 0.7844
Epoch 6/48
40/40 - 0s - 6ms/step - accuracy: 0.7367 - loss: 0.7354
Epoch 7/48
40/40 - 0s - 6ms/step - accuracy: 0.7449 - loss: 0.7124
Epoch 8/48
40/40 - 0s - 7ms/step - accuracy: 0.7563 - loss: 0.6813
Epoch 9/48
40/40 - 0s - 6ms/step - accuracy: 0.7601 - loss: 0.6669
Epoch 10/48
40/40 - 0s - 6ms/step - accuracy: 0.7626 - loss: 0.6504
Epoch 11/48
40/40 - 0s - 7ms/step - accuracy: 0.7698 - loss: 0.6348
Epoch 12/48
40/40 - 0s - 7ms/step - accuracy: 0.7713 - loss: 0.6258
Epoch 13/48
40/40 - 0s - 6ms/step - accuracy: 0.7821 - loss: 0.6105
Epoch 14/48
40/40 - 0s - 7ms/step - accuracy: 0.7842 - loss: 0.6014
Epoch 15/48
40/40 - 0s - 6ms/step - accuracy: 0.7863 - loss: 0.5950
Epoch 16/48
40/40 - 0s - 7ms/step - accuracy: 0.7895 - loss: 0.5770
Epoch 17/48
40/40 - 0s - 6ms/step - accuracy: 0.7927 - loss: 0.5773
Epoch 18/48
40/40 - 0s - 6ms/step - accuracy: 0.7940 - loss: 0.5654
Epoch 19/48
40/40 - 0s - 7ms/step - accuracy: 0.7949 - loss: 0.5603
Epoch 20/48
40/40 - 0s - 7ms/step - accuracy: 0.8025 - loss: 0.5472
Epoch 21/48
40/40 - 0s - 6ms/step - accuracy: 0.8007 - loss: 0.5455
Epoch 22/48
40/40 - 0s - 7ms/step - accuracy: 0.8057 - loss: 0.5377
Epoch 23/48
40/40 - 0s - 7ms/step - accuracy: 0.8092 - loss: 0.5323
Epoch 24/48
40/40 - 0s - 6ms/step - accuracy: 0.8073 - loss: 0.5271
Epoch 25/48
40/40 - 0s - 6ms/step - accuracy: 0.8130 - loss: 0.5190
Epoch 26/48
40/40 - 0s - 6ms/step - accuracy: 0.8134 - loss: 0.5133
Epoch 27/48
40/40 - 0s - 7ms/step - accuracy: 0.8137 - loss: 0.5104
Epoch 28/48
40/40 - 0s - 6ms/step - accuracy: 0.8169 - loss: 0.5028
Epoch 29/48
40/40 - 0s - 7ms/step - accuracy: 0.8182 - loss: 0.5033
Epoch 30/48
40/40 - 0s - 7ms/step - accuracy: 0.8216 - loss: 0.4897
Epoch 31/48
40/40 - 0s - 7ms/step - accuracy: 0.8223 - loss: 0.4885
Epoch 32/48
40/40 - 0s - 6ms/step - accuracy: 0.8227 - loss: 0.4838
Epoch 33/48
40/40 - 0s - 7ms/step - accuracy: 0.8253 - loss: 0.4788
Epoch 34/48
40/40 - 0s - 7ms/step - accuracy: 0.8261 - loss: 0.4756
Epoch 35/48
40/40 - 0s - 7ms/step - accuracy: 0.8253 - loss: 0.4692
Epoch 36/48
40/40 - 0s - 8ms/step - accuracy: 0.8285 - loss: 0.4664
Epoch 37/48
40/40 - 0s - 6ms/step - accuracy: 0.8329 - loss: 0.4541
Epoch 38/48
40/40 - 0s - 6ms/step - accuracy: 0.8363 - loss: 0.4506
Epoch 39/48
40/40 - 0s - 6ms/step - accuracy: 0.8376 - loss: 0.4486
Epoch 40/48
40/40 - 0s - 6ms/step - accuracy: 0.8376 - loss: 0.4429
Epoch 41/48
40/40 - 0s - 6ms/step - accuracy: 0.8407 - loss: 0.4363
Epoch 42/48
40/40 - 0s - 7ms/step - accuracy: 0.8399 - loss: 0.4358
Epoch 43/48
40/40 - 0s - 7ms/step - accuracy: 0.8427 - loss: 0.4324
Epoch 44/48
40/40 - 0s - 7ms/step - accuracy: 0.8450 - loss: 0.4277
Epoch 45/48
40/40 - 0s - 7ms/step - accuracy: 0.8435 - loss: 0.4253
Epoch 46/48
40/40 - 0s - 6ms/step - accuracy: 0.8459 - loss: 0.4225
Epoch 47/48
40/40 - 0s - 6ms/step - accuracy: 0.8451 - loss: 0.4186
Epoch 48/48
40/40 - 0s - 6ms/step - accuracy: 0.8508 - loss: 0.4040
10/10 - 0s - 18ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 2s - 41ms/step - accuracy: 0.6259 - loss: 1.2744
Epoch 2/48
40/40 - 0s - 10ms/step - accuracy: 0.6943 - loss: 0.9560
Epoch 3/48
40/40 - 0s - 9ms/step - accuracy: 0.7158 - loss: 0.8720
Epoch 4/48
40/40 - 0s - 9ms/step - accuracy: 0.7306 - loss: 0.8169
Epoch 5/48
40/40 - 0s - 8ms/step - accuracy: 0.7407 - loss: 0.7738
Epoch 6/48
40/40 - 0s - 9ms/step - accuracy: 0.7429 - loss: 0.7487
Epoch 7/48
40/40 - 0s - 10ms/step - accuracy: 0.7526 - loss: 0.7120
Epoch 8/48
40/40 - 0s - 9ms/step - accuracy: 0.7630 - loss: 0.6905
Epoch 9/48
40/40 - 0s - 8ms/step - accuracy: 0.7665 - loss: 0.6681
Epoch 10/48
40/40 - 0s - 8ms/step - accuracy: 0.7689 - loss: 0.6543
Epoch 11/48
40/40 - 0s - 9ms/step - accuracy: 0.7751 - loss: 0.6428
Epoch 12/48
40/40 - 0s - 9ms/step - accuracy: 0.7774 - loss: 0.6266
Epoch 13/48
40/40 - 0s - 8ms/step - accuracy: 0.7814 - loss: 0.6152
Epoch 14/48
40/40 - 0s - 7ms/step - accuracy: 0.7844 - loss: 0.6078
Epoch 15/48
40/40 - 0s - 7ms/step - accuracy: 0.7904 - loss: 0.5917
Epoch 16/48
40/40 - 0s - 7ms/step - accuracy: 0.7896 - loss: 0.5880
Epoch 17/48
40/40 - 0s - 7ms/step - accuracy: 0.7926 - loss: 0.5763
Epoch 18/48
40/40 - 0s - 7ms/step - accuracy: 0.7947 - loss: 0.5673
Epoch 19/48
40/40 - 0s - 7ms/step - accuracy: 0.7980 - loss: 0.5629
Epoch 20/48
40/40 - 0s - 6ms/step - accuracy: 0.8001 - loss: 0.5539
Epoch 21/48
40/40 - 0s - 7ms/step - accuracy: 0.8026 - loss: 0.5456
Epoch 22/48
40/40 - 0s - 6ms/step - accuracy: 0.8031 - loss: 0.5421
Epoch 23/48
40/40 - 0s - 6ms/step - accuracy: 0.8065 - loss: 0.5338
Epoch 24/48
40/40 - 0s - 6ms/step - accuracy: 0.8078 - loss: 0.5254
Epoch 25/48
40/40 - 0s - 6ms/step - accuracy: 0.8114 - loss: 0.5200
Epoch 26/48
40/40 - 0s - 6ms/step - accuracy: 0.8165 - loss: 0.5161
Epoch 27/48
40/40 - 0s - 7ms/step - accuracy: 0.8136 - loss: 0.5141
Epoch 28/48
40/40 - 0s - 6ms/step - accuracy: 0.8137 - loss: 0.5080
Epoch 29/48
40/40 - 0s - 7ms/step - accuracy: 0.8208 - loss: 0.4981
Epoch 30/48
40/40 - 0s - 7ms/step - accuracy: 0.8160 - loss: 0.5020
Epoch 31/48
40/40 - 0s - 7ms/step - accuracy: 0.8222 - loss: 0.4914
Epoch 32/48
40/40 - 0s - 7ms/step - accuracy: 0.8218 - loss: 0.4887
Epoch 33/48
40/40 - 0s - 7ms/step - accuracy: 0.8216 - loss: 0.4849
Epoch 34/48
40/40 - 0s - 7ms/step - accuracy: 0.8231 - loss: 0.4835
Epoch 35/48
40/40 - 0s - 7ms/step - accuracy: 0.8277 - loss: 0.4746
Epoch 36/48
40/40 - 0s - 7ms/step - accuracy: 0.8272 - loss: 0.4703
Epoch 37/48
40/40 - 0s - 6ms/step - accuracy: 0.8293 - loss: 0.4642
Epoch 38/48
40/40 - 0s - 6ms/step - accuracy: 0.8304 - loss: 0.4632
Epoch 39/48
40/40 - 0s - 7ms/step - accuracy: 0.8300 - loss: 0.4618
Epoch 40/48
40/40 - 0s - 7ms/step - accuracy: 0.8339 - loss: 0.4564
Epoch 41/48
40/40 - 0s - 7ms/step - accuracy: 0.8328 - loss: 0.4489
Epoch 42/48
40/40 - 0s - 7ms/step - accuracy: 0.8366 - loss: 0.4491
Epoch 43/48
40/40 - 0s - 7ms/step - accuracy: 0.8394 - loss: 0.4355
Epoch 44/48
40/40 - 0s - 7ms/step - accuracy: 0.8334 - loss: 0.4465
Epoch 45/48
40/40 - 0s - 7ms/step - accuracy: 0.8407 - loss: 0.4348
Epoch 46/48
40/40 - 0s - 7ms/step - accuracy: 0.8408 - loss: 0.4385
Epoch 47/48
40/40 - 0s - 7ms/step - accuracy: 0.8412 - loss: 0.4325
Epoch 48/48
40/40 - 0s - 6ms/step - accuracy: 0.8426 - loss: 0.4275
10/10 - 0s - 20ms/step
| 5         | 0.8439    | 4.92      | 347.9     | 0.9696    | 0.2325    | 48.18     | 2.79      | 2.196     | 2.844     | 0.09761   | 27.64     | 0.04523   | 2.277     |
Epoch 1/28

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 3s - 79ms/step - accuracy: 0.6076 - loss: 1.3274
Epoch 2/28
34/34 - 1s - 27ms/step - accuracy: 0.6991 - loss: 0.8825
Epoch 3/28
34/34 - 1s - 28ms/step - accuracy: 0.7347 - loss: 0.7692
Epoch 4/28
34/34 - 1s - 30ms/step - accuracy: 0.7603 - loss: 0.7037
Epoch 5/28
34/34 - 1s - 30ms/step - accuracy: 0.7742 - loss: 0.6570
Epoch 6/28
34/34 - 1s - 28ms/step - accuracy: 0.7889 - loss: 0.6186
Epoch 7/28
34/34 - 1s - 26ms/step - accuracy: 0.8000 - loss: 0.5783
Epoch 8/28
34/34 - 1s - 25ms/step - accuracy: 0.7976 - loss: 0.5738
Epoch 9/28
34/34 - 1s - 25ms/step - accuracy: 0.8102 - loss: 0.5449
Epoch 10/28
34/34 - 1s - 26ms/step - accuracy: 0.8137 - loss: 0.5263
Epoch 11/28
34/34 - 1s - 26ms/step - accuracy: 0.8131 - loss: 0.5203
Epoch 12/28
34/34 - 1s - 27ms/step - accuracy: 0.8247 - loss: 0.4921
Epoch 13/28
34/34 - 1s - 25ms/step - accuracy: 0.8314 - loss: 0.4770
Epoch 14/28
34/34 - 1s - 26ms/step - accuracy: 0.8340 - loss: 0.4632
Epoch 15/28
34/34 - 1s - 25ms/step - accuracy: 0.8395 - loss: 0.4587
Epoch 16/28
34/34 - 1s - 25ms/step - accuracy: 0.8446 - loss: 0.4319
Epoch 17/28
34/34 - 1s - 25ms/step - accuracy: 0.8485 - loss: 0.4292
Epoch 18/28
34/34 - 1s - 25ms/step - accuracy: 0.8492 - loss: 0.4181
Epoch 19/28
34/34 - 1s - 26ms/step - accuracy: 0.8462 - loss: 0.4334
Epoch 20/28
34/34 - 1s - 26ms/step - accuracy: 0.8675 - loss: 0.3785
Epoch 21/28
34/34 - 1s - 27ms/step - accuracy: 0.8709 - loss: 0.3654
Epoch 22/28
34/34 - 1s - 29ms/step - accuracy: 0.8696 - loss: 0.3650
Epoch 23/28
34/34 - 1s - 27ms/step - accuracy: 0.8682 - loss: 0.3654
Epoch 24/28
34/34 - 1s - 31ms/step - accuracy: 0.8688 - loss: 0.3708
Epoch 25/28
34/34 - 1s - 28ms/step - accuracy: 0.8810 - loss: 0.3388
Epoch 26/28
34/34 - 1s - 25ms/step - accuracy: 0.8792 - loss: 0.3407
Epoch 27/28
34/34 - 1s - 24ms/step - accuracy: 0.8844 - loss: 0.3201
Epoch 28/28
34/34 - 1s - 24ms/step - accuracy: 0.8831 - loss: 0.3260
9/9 - 0s - 28ms/step
Epoch 1/28

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 3s - 81ms/step - accuracy: 0.6045 - loss: 1.3226
Epoch 2/28
34/34 - 1s - 25ms/step - accuracy: 0.7001 - loss: 0.8711
Epoch 3/28
34/34 - 1s - 26ms/step - accuracy: 0.7312 - loss: 0.7789
Epoch 4/28
34/34 - 1s - 25ms/step - accuracy: 0.7490 - loss: 0.7269
Epoch 5/28
34/34 - 1s - 27ms/step - accuracy: 0.7653 - loss: 0.6792
Epoch 6/28
34/34 - 1s - 29ms/step - accuracy: 0.7780 - loss: 0.6350
Epoch 7/28
34/34 - 1s - 29ms/step - accuracy: 0.7941 - loss: 0.5925
Epoch 8/28
34/34 - 1s - 29ms/step - accuracy: 0.8001 - loss: 0.5703
Epoch 9/28
34/34 - 1s - 28ms/step - accuracy: 0.8155 - loss: 0.5262
Epoch 10/28
34/34 - 1s - 29ms/step - accuracy: 0.8263 - loss: 0.4960
Epoch 11/28
34/34 - 1s - 27ms/step - accuracy: 0.8275 - loss: 0.4900
Epoch 12/28
34/34 - 1s - 27ms/step - accuracy: 0.8377 - loss: 0.4636
Epoch 13/28
34/34 - 1s - 27ms/step - accuracy: 0.8350 - loss: 0.4627
Epoch 14/28
34/34 - 1s - 25ms/step - accuracy: 0.8517 - loss: 0.4161
Epoch 15/28
34/34 - 1s - 25ms/step - accuracy: 0.8589 - loss: 0.4029
Epoch 16/28
34/34 - 1s - 24ms/step - accuracy: 0.8584 - loss: 0.4024
Epoch 17/28
34/34 - 1s - 25ms/step - accuracy: 0.8598 - loss: 0.3888
Epoch 18/28
34/34 - 1s - 25ms/step - accuracy: 0.8727 - loss: 0.3568
Epoch 19/28
34/34 - 1s - 25ms/step - accuracy: 0.8662 - loss: 0.3806
Epoch 20/28
34/34 - 1s - 25ms/step - accuracy: 0.8664 - loss: 0.3776
Epoch 21/28
34/34 - 1s - 26ms/step - accuracy: 0.8669 - loss: 0.3724
Epoch 22/28
34/34 - 1s - 27ms/step - accuracy: 0.8868 - loss: 0.3209
Epoch 23/28
34/34 - 1s - 25ms/step - accuracy: 0.8814 - loss: 0.3299
Epoch 24/28
34/34 - 1s - 26ms/step - accuracy: 0.8952 - loss: 0.2958
Epoch 25/28
34/34 - 1s - 26ms/step - accuracy: 0.8921 - loss: 0.3015
Epoch 26/28
34/34 - 1s - 27ms/step - accuracy: 0.8800 - loss: 0.3442
Epoch 27/28
34/34 - 1s - 26ms/step - accuracy: 0.8615 - loss: 0.3900
Epoch 28/28
34/34 - 1s - 28ms/step - accuracy: 0.8970 - loss: 0.2900
9/9 - 0s - 37ms/step
Epoch 1/28

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 2s - 70ms/step - accuracy: 0.6328 - loss: 1.2771
Epoch 2/28
34/34 - 1s - 24ms/step - accuracy: 0.7118 - loss: 0.8369
Epoch 3/28
34/34 - 1s - 24ms/step - accuracy: 0.7359 - loss: 0.7567
Epoch 4/28
34/34 - 1s - 25ms/step - accuracy: 0.7613 - loss: 0.6993
Epoch 5/28
34/34 - 1s - 37ms/step - accuracy: 0.7742 - loss: 0.6517
Epoch 6/28
34/34 - 1s - 26ms/step - accuracy: 0.7787 - loss: 0.6304
Epoch 7/28
34/34 - 1s - 24ms/step - accuracy: 0.8001 - loss: 0.5825
Epoch 8/28
34/34 - 1s - 25ms/step - accuracy: 0.8131 - loss: 0.5400
Epoch 9/28
34/34 - 1s - 25ms/step - accuracy: 0.8179 - loss: 0.5133
Epoch 10/28
34/34 - 1s - 25ms/step - accuracy: 0.8237 - loss: 0.5052
Epoch 11/28
34/34 - 1s - 25ms/step - accuracy: 0.8319 - loss: 0.4702
Epoch 12/28
34/34 - 1s - 26ms/step - accuracy: 0.8452 - loss: 0.4403
Epoch 13/28
34/34 - 1s - 26ms/step - accuracy: 0.8501 - loss: 0.4249
Epoch 14/28
34/34 - 1s - 26ms/step - accuracy: 0.8496 - loss: 0.4281
Epoch 15/28
34/34 - 1s - 26ms/step - accuracy: 0.8606 - loss: 0.4058
Epoch 16/28
34/34 - 1s - 26ms/step - accuracy: 0.8534 - loss: 0.4155
Epoch 17/28
34/34 - 1s - 27ms/step - accuracy: 0.8662 - loss: 0.3754
Epoch 18/28
34/34 - 1s - 25ms/step - accuracy: 0.8733 - loss: 0.3613
Epoch 19/28
34/34 - 1s - 25ms/step - accuracy: 0.8663 - loss: 0.3818
Epoch 20/28
34/34 - 1s - 39ms/step - accuracy: 0.8755 - loss: 0.3490
Epoch 21/28
34/34 - 1s - 26ms/step - accuracy: 0.8780 - loss: 0.3502
Epoch 22/28
34/34 - 1s - 26ms/step - accuracy: 0.8833 - loss: 0.3323
Epoch 23/28
34/34 - 1s - 26ms/step - accuracy: 0.8764 - loss: 0.3448
Epoch 24/28
34/34 - 1s - 26ms/step - accuracy: 0.8894 - loss: 0.3127
Epoch 25/28
34/34 - 1s - 26ms/step - accuracy: 0.8911 - loss: 0.3122
Epoch 26/28
34/34 - 1s - 26ms/step - accuracy: 0.8938 - loss: 0.2981
Epoch 27/28
34/34 - 1s - 26ms/step - accuracy: 0.8956 - loss: 0.3017
Epoch 28/28
34/34 - 1s - 25ms/step - accuracy: 0.8881 - loss: 0.3178
9/9 - 0s - 34ms/step
Epoch 1/28

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 3s - 91ms/step - accuracy: 0.6383 - loss: 1.2464
Epoch 2/28
34/34 - 1s - 24ms/step - accuracy: 0.7107 - loss: 0.8404
Epoch 3/28
34/34 - 1s - 25ms/step - accuracy: 0.7375 - loss: 0.7594
Epoch 4/28
34/34 - 1s - 24ms/step - accuracy: 0.7572 - loss: 0.7049
Epoch 5/28
34/34 - 1s - 24ms/step - accuracy: 0.7720 - loss: 0.6574
Epoch 6/28
34/34 - 1s - 24ms/step - accuracy: 0.7900 - loss: 0.6100
Epoch 7/28
34/34 - 1s - 25ms/step - accuracy: 0.7938 - loss: 0.5892
Epoch 8/28
34/34 - 1s - 24ms/step - accuracy: 0.8070 - loss: 0.5552
Epoch 9/28
34/34 - 1s - 24ms/step - accuracy: 0.8224 - loss: 0.5126
Epoch 10/28
34/34 - 1s - 24ms/step - accuracy: 0.8257 - loss: 0.4972
Epoch 11/28
34/34 - 1s - 25ms/step - accuracy: 0.8319 - loss: 0.4771
Epoch 12/28
34/34 - 1s - 24ms/step - accuracy: 0.8328 - loss: 0.4774
Epoch 13/28
34/34 - 1s - 25ms/step - accuracy: 0.8426 - loss: 0.4421
Epoch 14/28
34/34 - 1s - 25ms/step - accuracy: 0.8468 - loss: 0.4368
Epoch 15/28
34/34 - 1s - 37ms/step - accuracy: 0.8568 - loss: 0.4006
Epoch 16/28
34/34 - 1s - 24ms/step - accuracy: 0.8612 - loss: 0.3953
Epoch 17/28
34/34 - 1s - 26ms/step - accuracy: 0.8533 - loss: 0.4154
Epoch 18/28
34/34 - 1s - 26ms/step - accuracy: 0.8633 - loss: 0.3842
Epoch 19/28
34/34 - 1s - 26ms/step - accuracy: 0.8698 - loss: 0.3681
Epoch 20/28
34/34 - 1s - 26ms/step - accuracy: 0.8829 - loss: 0.3362
Epoch 21/28
34/34 - 1s - 26ms/step - accuracy: 0.8466 - loss: 0.4377
Epoch 22/28
34/34 - 1s - 27ms/step - accuracy: 0.8743 - loss: 0.3613
Epoch 23/28
34/34 - 1s - 26ms/step - accuracy: 0.8784 - loss: 0.3476
Epoch 24/28
34/34 - 1s - 25ms/step - accuracy: 0.8844 - loss: 0.3284
Epoch 25/28
34/34 - 1s - 24ms/step - accuracy: 0.8782 - loss: 0.3386
Epoch 26/28
34/34 - 1s - 25ms/step - accuracy: 0.8890 - loss: 0.3119
Epoch 27/28
34/34 - 1s - 24ms/step - accuracy: 0.9017 - loss: 0.2860
Epoch 28/28
34/34 - 1s - 24ms/step - accuracy: 0.8932 - loss: 0.3146
9/9 - 0s - 26ms/step
Epoch 1/28

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 2s - 70ms/step - accuracy: 0.6253 - loss: 1.2774
Epoch 2/28
34/34 - 1s - 24ms/step - accuracy: 0.7143 - loss: 0.8342
Epoch 3/28
34/34 - 1s - 24ms/step - accuracy: 0.7463 - loss: 0.7440
Epoch 4/28
34/34 - 1s - 25ms/step - accuracy: 0.7635 - loss: 0.6828
Epoch 5/28
34/34 - 1s - 26ms/step - accuracy: 0.7803 - loss: 0.6343
Epoch 6/28
34/34 - 1s - 26ms/step - accuracy: 0.7862 - loss: 0.6112
Epoch 7/28
34/34 - 1s - 26ms/step - accuracy: 0.7925 - loss: 0.6065
Epoch 8/28
34/34 - 1s - 29ms/step - accuracy: 0.8137 - loss: 0.5304
Epoch 9/28
34/34 - 1s - 26ms/step - accuracy: 0.8230 - loss: 0.5075
Epoch 10/28
34/34 - 1s - 26ms/step - accuracy: 0.8344 - loss: 0.4752
Epoch 11/28
34/34 - 1s - 25ms/step - accuracy: 0.8402 - loss: 0.4561
Epoch 12/28
34/34 - 1s - 25ms/step - accuracy: 0.8316 - loss: 0.4770
Epoch 13/28
34/34 - 1s - 25ms/step - accuracy: 0.8420 - loss: 0.4489
Epoch 14/28
34/34 - 1s - 25ms/step - accuracy: 0.8559 - loss: 0.4103
Epoch 15/28
34/34 - 1s - 25ms/step - accuracy: 0.8640 - loss: 0.3900
Epoch 16/28
34/34 - 1s - 25ms/step - accuracy: 0.8664 - loss: 0.3782
Epoch 17/28
34/34 - 1s - 25ms/step - accuracy: 0.8672 - loss: 0.3773
Epoch 18/28
34/34 - 1s - 25ms/step - accuracy: 0.8622 - loss: 0.3881
Epoch 19/28
34/34 - 1s - 25ms/step - accuracy: 0.8721 - loss: 0.3627
Epoch 20/28
34/34 - 1s - 25ms/step - accuracy: 0.8829 - loss: 0.3401
Epoch 21/28
34/34 - 1s - 25ms/step - accuracy: 0.8588 - loss: 0.4032
Epoch 22/28
34/34 - 1s - 25ms/step - accuracy: 0.8817 - loss: 0.3375
Epoch 23/28
34/34 - 1s - 27ms/step - accuracy: 0.8898 - loss: 0.3194
Epoch 24/28
34/34 - 1s - 27ms/step - accuracy: 0.8943 - loss: 0.3044
Epoch 25/28
34/34 - 1s - 29ms/step - accuracy: 0.8961 - loss: 0.2988
Epoch 26/28
34/34 - 1s - 27ms/step - accuracy: 0.8845 - loss: 0.3249
Epoch 27/28
34/34 - 1s - 26ms/step - accuracy: 0.8911 - loss: 0.3052
Epoch 28/28
34/34 - 1s - 28ms/step - accuracy: 0.9028 - loss: 0.2827
9/9 - 0s - 31ms/step
| 6         | 0.8693    | 3.498     | 417.1     | 0.8287    | 0.107     | 28.43     | 2.085     | 1.282     | 2.604     | 0.08381   | 98.82     | 0.7722    | 1.391     |
Epoch 1/43

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 51ms/step - accuracy: 0.5863 - loss: 1.5747
Epoch 2/43
17/17 - 0s - 20ms/step - accuracy: 0.6342 - loss: 1.1565
Epoch 3/43
17/17 - 0s - 20ms/step - accuracy: 0.6479 - loss: 1.0973
Epoch 4/43
17/17 - 0s - 20ms/step - accuracy: 0.6535 - loss: 1.0635
Epoch 5/43
17/17 - 0s - 20ms/step - accuracy: 0.6562 - loss: 1.0428
Epoch 6/43
17/17 - 0s - 20ms/step - accuracy: 0.6654 - loss: 1.0147
Epoch 7/43
17/17 - 0s - 19ms/step - accuracy: 0.6651 - loss: 0.9983
Epoch 8/43
17/17 - 0s - 20ms/step - accuracy: 0.6672 - loss: 0.9894
Epoch 9/43
17/17 - 0s - 21ms/step - accuracy: 0.6730 - loss: 0.9718
Epoch 10/43
17/17 - 0s - 20ms/step - accuracy: 0.6757 - loss: 0.9602
Epoch 11/43
17/17 - 0s - 20ms/step - accuracy: 0.6839 - loss: 0.9436
Epoch 12/43
17/17 - 0s - 21ms/step - accuracy: 0.6859 - loss: 0.9331
Epoch 13/43
17/17 - 0s - 23ms/step - accuracy: 0.6844 - loss: 0.9218
Epoch 14/43
17/17 - 0s - 21ms/step - accuracy: 0.6929 - loss: 0.9110
Epoch 15/43
17/17 - 0s - 20ms/step - accuracy: 0.6988 - loss: 0.8970
Epoch 16/43
17/17 - 0s - 19ms/step - accuracy: 0.6979 - loss: 0.8890
Epoch 17/43
17/17 - 0s - 20ms/step - accuracy: 0.6985 - loss: 0.8891
Epoch 18/43
17/17 - 0s - 20ms/step - accuracy: 0.7027 - loss: 0.8783
Epoch 19/43
17/17 - 0s - 19ms/step - accuracy: 0.7066 - loss: 0.8693
Epoch 20/43
17/17 - 0s - 20ms/step - accuracy: 0.7051 - loss: 0.8648
Epoch 21/43
17/17 - 0s - 20ms/step - accuracy: 0.7071 - loss: 0.8612
Epoch 22/43
17/17 - 0s - 19ms/step - accuracy: 0.7088 - loss: 0.8569
Epoch 23/43
17/17 - 0s - 20ms/step - accuracy: 0.7125 - loss: 0.8514
Epoch 24/43
17/17 - 0s - 19ms/step - accuracy: 0.7104 - loss: 0.8525
Epoch 25/43
17/17 - 0s - 19ms/step - accuracy: 0.7126 - loss: 0.8466
Epoch 26/43
17/17 - 0s - 20ms/step - accuracy: 0.7117 - loss: 0.8447
Epoch 27/43
17/17 - 0s - 19ms/step - accuracy: 0.7151 - loss: 0.8398
Epoch 28/43
17/17 - 0s - 19ms/step - accuracy: 0.7167 - loss: 0.8349
Epoch 29/43
17/17 - 0s - 20ms/step - accuracy: 0.7172 - loss: 0.8279
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7195 - loss: 0.8285
Epoch 31/43
17/17 - 0s - 21ms/step - accuracy: 0.7181 - loss: 0.8255
Epoch 32/43
17/17 - 0s - 21ms/step - accuracy: 0.7200 - loss: 0.8244
Epoch 33/43
17/17 - 0s - 20ms/step - accuracy: 0.7242 - loss: 0.8166
Epoch 34/43
17/17 - 0s - 21ms/step - accuracy: 0.7253 - loss: 0.8182
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7233 - loss: 0.8185
Epoch 36/43
17/17 - 0s - 21ms/step - accuracy: 0.7219 - loss: 0.8184
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7223 - loss: 0.8145
Epoch 38/43
17/17 - 0s - 21ms/step - accuracy: 0.7238 - loss: 0.8105
Epoch 39/43
17/17 - 0s - 21ms/step - accuracy: 0.7279 - loss: 0.8060
Epoch 40/43
17/17 - 0s - 21ms/step - accuracy: 0.7248 - loss: 0.8079
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7289 - loss: 0.8008
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7277 - loss: 0.8008
Epoch 43/43
17/17 - 0s - 21ms/step - accuracy: 0.7280 - loss: 0.8039
5/5 - 0s - 32ms/step
Epoch 1/43

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 47ms/step - accuracy: 0.5708 - loss: 1.5404
Epoch 2/43
17/17 - 0s - 21ms/step - accuracy: 0.6319 - loss: 1.1420
Epoch 3/43
17/17 - 0s - 20ms/step - accuracy: 0.6376 - loss: 1.0924
Epoch 4/43
17/17 - 0s - 19ms/step - accuracy: 0.6465 - loss: 1.0610
Epoch 5/43
17/17 - 0s - 20ms/step - accuracy: 0.6441 - loss: 1.0469
Epoch 6/43
17/17 - 0s - 23ms/step - accuracy: 0.6496 - loss: 1.0339
Epoch 7/43
17/17 - 0s - 20ms/step - accuracy: 0.6542 - loss: 1.0192
Epoch 8/43
17/17 - 0s - 19ms/step - accuracy: 0.6554 - loss: 1.0096
Epoch 9/43
17/17 - 0s - 20ms/step - accuracy: 0.6522 - loss: 1.0018
Epoch 10/43
17/17 - 0s - 20ms/step - accuracy: 0.6582 - loss: 0.9932
Epoch 11/43
17/17 - 0s - 20ms/step - accuracy: 0.6628 - loss: 0.9846
Epoch 12/43
17/17 - 0s - 19ms/step - accuracy: 0.6621 - loss: 0.9852
Epoch 13/43
17/17 - 0s - 19ms/step - accuracy: 0.6651 - loss: 0.9716
Epoch 14/43
17/17 - 0s - 19ms/step - accuracy: 0.6646 - loss: 0.9674
Epoch 15/43
17/17 - 0s - 19ms/step - accuracy: 0.6663 - loss: 0.9673
Epoch 16/43
17/17 - 0s - 18ms/step - accuracy: 0.6711 - loss: 0.9574
Epoch 17/43
17/17 - 0s - 19ms/step - accuracy: 0.6690 - loss: 0.9499
Epoch 18/43
17/17 - 0s - 19ms/step - accuracy: 0.6737 - loss: 0.9434
Epoch 19/43
17/17 - 0s - 20ms/step - accuracy: 0.6747 - loss: 0.9382
Epoch 20/43
17/17 - 0s - 19ms/step - accuracy: 0.6756 - loss: 0.9412
Epoch 21/43
17/17 - 0s - 19ms/step - accuracy: 0.6824 - loss: 0.9251
Epoch 22/43
17/17 - 0s - 19ms/step - accuracy: 0.6796 - loss: 0.9256
Epoch 23/43
17/17 - 0s - 19ms/step - accuracy: 0.6788 - loss: 0.9246
Epoch 24/43
17/17 - 0s - 20ms/step - accuracy: 0.6783 - loss: 0.9278
Epoch 25/43
17/17 - 0s - 20ms/step - accuracy: 0.6856 - loss: 0.9140
Epoch 26/43
17/17 - 0s - 20ms/step - accuracy: 0.6866 - loss: 0.9082
Epoch 27/43
17/17 - 0s - 20ms/step - accuracy: 0.6903 - loss: 0.9026
Epoch 28/43
17/17 - 0s - 19ms/step - accuracy: 0.6893 - loss: 0.8989
Epoch 29/43
17/17 - 0s - 20ms/step - accuracy: 0.6932 - loss: 0.8981
Epoch 30/43
17/17 - 0s - 20ms/step - accuracy: 0.6893 - loss: 0.8946
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.6923 - loss: 0.8903
Epoch 32/43
17/17 - 0s - 21ms/step - accuracy: 0.6998 - loss: 0.8853
Epoch 33/43
17/17 - 0s - 21ms/step - accuracy: 0.6987 - loss: 0.8785
Epoch 34/43
17/17 - 0s - 21ms/step - accuracy: 0.6914 - loss: 0.8901
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7003 - loss: 0.8714
Epoch 36/43
17/17 - 0s - 21ms/step - accuracy: 0.7014 - loss: 0.8704
Epoch 37/43
17/17 - 0s - 22ms/step - accuracy: 0.7026 - loss: 0.8691
Epoch 38/43
17/17 - 0s - 24ms/step - accuracy: 0.7062 - loss: 0.8585
Epoch 39/43
17/17 - 0s - 22ms/step - accuracy: 0.7022 - loss: 0.8640
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7028 - loss: 0.8601
Epoch 41/43
17/17 - 0s - 23ms/step - accuracy: 0.7070 - loss: 0.8527
Epoch 42/43
17/17 - 0s - 23ms/step - accuracy: 0.7060 - loss: 0.8563
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7115 - loss: 0.8520
5/5 - 0s - 35ms/step
Epoch 1/43

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 47ms/step - accuracy: 0.5458 - loss: 1.9064
Epoch 2/43
17/17 - 0s - 19ms/step - accuracy: 0.6399 - loss: 1.1515
Epoch 3/43
17/17 - 0s - 19ms/step - accuracy: 0.6392 - loss: 1.0989
Epoch 4/43
17/17 - 0s - 19ms/step - accuracy: 0.6542 - loss: 1.0532
Epoch 5/43
17/17 - 0s - 20ms/step - accuracy: 0.6619 - loss: 1.0330
Epoch 6/43
17/17 - 0s - 20ms/step - accuracy: 0.6615 - loss: 1.0158
Epoch 7/43
17/17 - 0s - 20ms/step - accuracy: 0.6624 - loss: 0.9982
Epoch 8/43
17/17 - 0s - 21ms/step - accuracy: 0.6650 - loss: 0.9885
Epoch 9/43
17/17 - 0s - 19ms/step - accuracy: 0.6686 - loss: 0.9777
Epoch 10/43
17/17 - 0s - 19ms/step - accuracy: 0.6752 - loss: 0.9638
Epoch 11/43
17/17 - 0s - 19ms/step - accuracy: 0.6764 - loss: 0.9525
Epoch 12/43
17/17 - 0s - 19ms/step - accuracy: 0.6829 - loss: 0.9434
Epoch 13/43
17/17 - 0s - 19ms/step - accuracy: 0.6842 - loss: 0.9343
Epoch 14/43
17/17 - 0s - 19ms/step - accuracy: 0.6824 - loss: 0.9279
Epoch 15/43
17/17 - 0s - 19ms/step - accuracy: 0.6898 - loss: 0.9195
Epoch 16/43
17/17 - 0s - 19ms/step - accuracy: 0.6935 - loss: 0.9136
Epoch 17/43
17/17 - 0s - 19ms/step - accuracy: 0.6896 - loss: 0.9119
Epoch 18/43
17/17 - 0s - 19ms/step - accuracy: 0.6962 - loss: 0.9008
Epoch 19/43
17/17 - 0s - 19ms/step - accuracy: 0.6996 - loss: 0.8881
Epoch 20/43
17/17 - 0s - 20ms/step - accuracy: 0.6983 - loss: 0.8901
Epoch 21/43
17/17 - 0s - 20ms/step - accuracy: 0.7007 - loss: 0.8811
Epoch 22/43
17/17 - 0s - 20ms/step - accuracy: 0.7001 - loss: 0.8785
Epoch 23/43
17/17 - 0s - 20ms/step - accuracy: 0.7028 - loss: 0.8746
Epoch 24/43
17/17 - 0s - 20ms/step - accuracy: 0.7056 - loss: 0.8679
Epoch 25/43
17/17 - 0s - 20ms/step - accuracy: 0.7038 - loss: 0.8679
Epoch 26/43
17/17 - 0s - 20ms/step - accuracy: 0.7009 - loss: 0.8681
Epoch 27/43
17/17 - 0s - 20ms/step - accuracy: 0.7097 - loss: 0.8638
Epoch 28/43
17/17 - 0s - 19ms/step - accuracy: 0.7097 - loss: 0.8583
Epoch 29/43
17/17 - 0s - 20ms/step - accuracy: 0.7129 - loss: 0.8502
Epoch 30/43
17/17 - 0s - 19ms/step - accuracy: 0.7102 - loss: 0.8518
Epoch 31/43
17/17 - 0s - 21ms/step - accuracy: 0.7134 - loss: 0.8454
Epoch 32/43
17/17 - 0s - 21ms/step - accuracy: 0.7103 - loss: 0.8469
Epoch 33/43
17/17 - 0s - 21ms/step - accuracy: 0.7147 - loss: 0.8382
Epoch 34/43
17/17 - 0s - 21ms/step - accuracy: 0.7142 - loss: 0.8387
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7155 - loss: 0.8368
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7163 - loss: 0.8316
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7153 - loss: 0.8326
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7166 - loss: 0.8323
Epoch 39/43
17/17 - 0s - 21ms/step - accuracy: 0.7179 - loss: 0.8257
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7225 - loss: 0.8232
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7236 - loss: 0.8188
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7184 - loss: 0.8202
Epoch 43/43
17/17 - 0s - 23ms/step - accuracy: 0.7224 - loss: 0.8166
5/5 - 0s - 32ms/step
Epoch 1/43

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 66ms/step - accuracy: 0.5345 - loss: 1.7045
Epoch 2/43
17/17 - 0s - 18ms/step - accuracy: 0.6269 - loss: 1.1883
Epoch 3/43
17/17 - 0s - 19ms/step - accuracy: 0.6394 - loss: 1.1048
Epoch 4/43
17/17 - 0s - 19ms/step - accuracy: 0.6515 - loss: 1.0508
Epoch 5/43
17/17 - 0s - 19ms/step - accuracy: 0.6553 - loss: 1.0301
Epoch 6/43
17/17 - 0s - 20ms/step - accuracy: 0.6601 - loss: 1.0066
Epoch 7/43
17/17 - 0s - 19ms/step - accuracy: 0.6642 - loss: 0.9925
Epoch 8/43
17/17 - 0s - 20ms/step - accuracy: 0.6700 - loss: 0.9779
Epoch 9/43
17/17 - 0s - 20ms/step - accuracy: 0.6761 - loss: 0.9619
Epoch 10/43
17/17 - 0s - 21ms/step - accuracy: 0.6763 - loss: 0.9482
Epoch 11/43
17/17 - 0s - 19ms/step - accuracy: 0.6802 - loss: 0.9388
Epoch 12/43
17/17 - 0s - 19ms/step - accuracy: 0.6813 - loss: 0.9338
Epoch 13/43
17/17 - 0s - 19ms/step - accuracy: 0.6899 - loss: 0.9204
Epoch 14/43
17/17 - 0s - 20ms/step - accuracy: 0.6871 - loss: 0.9203
Epoch 15/43
17/17 - 0s - 20ms/step - accuracy: 0.6927 - loss: 0.9079
Epoch 16/43
17/17 - 0s - 20ms/step - accuracy: 0.6956 - loss: 0.8983
Epoch 17/43
17/17 - 0s - 19ms/step - accuracy: 0.6977 - loss: 0.8932
Epoch 18/43
17/17 - 0s - 20ms/step - accuracy: 0.6943 - loss: 0.9014
Epoch 19/43
17/17 - 0s - 20ms/step - accuracy: 0.7017 - loss: 0.8856
Epoch 20/43
17/17 - 0s - 20ms/step - accuracy: 0.7012 - loss: 0.8806
Epoch 21/43
17/17 - 0s - 20ms/step - accuracy: 0.7023 - loss: 0.8817
Epoch 22/43
17/17 - 0s - 20ms/step - accuracy: 0.7067 - loss: 0.8708
Epoch 23/43
17/17 - 0s - 19ms/step - accuracy: 0.7092 - loss: 0.8665
Epoch 24/43
17/17 - 0s - 20ms/step - accuracy: 0.7086 - loss: 0.8618
Epoch 25/43
17/17 - 0s - 20ms/step - accuracy: 0.7113 - loss: 0.8565
Epoch 26/43
17/17 - 0s - 19ms/step - accuracy: 0.7123 - loss: 0.8549
Epoch 27/43
17/17 - 0s - 20ms/step - accuracy: 0.7115 - loss: 0.8553
Epoch 28/43
17/17 - 0s - 20ms/step - accuracy: 0.7139 - loss: 0.8476
Epoch 29/43
17/17 - 0s - 20ms/step - accuracy: 0.7126 - loss: 0.8498
Epoch 30/43
17/17 - 0s - 20ms/step - accuracy: 0.7131 - loss: 0.8452
Epoch 31/43
17/17 - 0s - 21ms/step - accuracy: 0.7141 - loss: 0.8445
Epoch 32/43
17/17 - 0s - 21ms/step - accuracy: 0.7183 - loss: 0.8371
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7143 - loss: 0.8399
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7211 - loss: 0.8317
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7215 - loss: 0.8308
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7194 - loss: 0.8301
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7217 - loss: 0.8258
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7219 - loss: 0.8256
Epoch 39/43
17/17 - 0s - 21ms/step - accuracy: 0.7232 - loss: 0.8204
Epoch 40/43
17/17 - 0s - 21ms/step - accuracy: 0.7238 - loss: 0.8205
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7259 - loss: 0.8151
Epoch 42/43
17/17 - 0s - 24ms/step - accuracy: 0.7221 - loss: 0.8188
Epoch 43/43
17/17 - 0s - 24ms/step - accuracy: 0.7251 - loss: 0.8155
5/5 - 0s - 38ms/step
Epoch 1/43

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 49ms/step - accuracy: 0.5781 - loss: 1.6900
Epoch 2/43
17/17 - 0s - 21ms/step - accuracy: 0.6439 - loss: 1.1290
Epoch 3/43
17/17 - 0s - 22ms/step - accuracy: 0.6482 - loss: 1.0840
Epoch 4/43
17/17 - 0s - 22ms/step - accuracy: 0.6534 - loss: 1.0536
Epoch 5/43
17/17 - 0s - 22ms/step - accuracy: 0.6567 - loss: 1.0287
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6617 - loss: 1.0110
Epoch 7/43
17/17 - 0s - 21ms/step - accuracy: 0.6607 - loss: 0.9973
Epoch 8/43
17/17 - 0s - 19ms/step - accuracy: 0.6647 - loss: 0.9816
Epoch 9/43
17/17 - 0s - 19ms/step - accuracy: 0.6656 - loss: 0.9759
Epoch 10/43
17/17 - 0s - 19ms/step - accuracy: 0.6704 - loss: 0.9555
Epoch 11/43
17/17 - 0s - 19ms/step - accuracy: 0.6781 - loss: 0.9437
Epoch 12/43
17/17 - 0s - 19ms/step - accuracy: 0.6757 - loss: 0.9331
Epoch 13/43
17/17 - 0s - 21ms/step - accuracy: 0.6821 - loss: 0.9265
Epoch 14/43
17/17 - 0s - 20ms/step - accuracy: 0.6805 - loss: 0.9221
Epoch 15/43
17/17 - 0s - 20ms/step - accuracy: 0.6860 - loss: 0.9085
Epoch 16/43
17/17 - 0s - 20ms/step - accuracy: 0.6905 - loss: 0.8986
Epoch 17/43
17/17 - 0s - 19ms/step - accuracy: 0.6929 - loss: 0.8935
Epoch 18/43
17/17 - 0s - 20ms/step - accuracy: 0.6970 - loss: 0.8849
Epoch 19/43
17/17 - 0s - 20ms/step - accuracy: 0.6991 - loss: 0.8740
Epoch 20/43
17/17 - 0s - 19ms/step - accuracy: 0.6993 - loss: 0.8737
Epoch 21/43
17/17 - 0s - 20ms/step - accuracy: 0.7007 - loss: 0.8671
Epoch 22/43
17/17 - 0s - 19ms/step - accuracy: 0.7038 - loss: 0.8627
Epoch 23/43
17/17 - 0s - 19ms/step - accuracy: 0.7062 - loss: 0.8615
Epoch 24/43
17/17 - 0s - 20ms/step - accuracy: 0.7079 - loss: 0.8547
Epoch 25/43
17/17 - 0s - 19ms/step - accuracy: 0.7084 - loss: 0.8505
Epoch 26/43
17/17 - 0s - 20ms/step - accuracy: 0.7054 - loss: 0.8501
Epoch 27/43
17/17 - 0s - 20ms/step - accuracy: 0.7119 - loss: 0.8448
Epoch 28/43
17/17 - 0s - 20ms/step - accuracy: 0.7154 - loss: 0.8347
Epoch 29/43
17/17 - 0s - 19ms/step - accuracy: 0.7088 - loss: 0.8397
Epoch 30/43
17/17 - 0s - 19ms/step - accuracy: 0.7127 - loss: 0.8327
Epoch 31/43
17/17 - 0s - 21ms/step - accuracy: 0.7124 - loss: 0.8315
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7111 - loss: 0.8315
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7182 - loss: 0.8229
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7184 - loss: 0.8203
Epoch 35/43
17/17 - 0s - 22ms/step - accuracy: 0.7182 - loss: 0.8237
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7193 - loss: 0.8221
Epoch 37/43
17/17 - 0s - 22ms/step - accuracy: 0.7229 - loss: 0.8134
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7189 - loss: 0.8161
Epoch 39/43
17/17 - 0s - 23ms/step - accuracy: 0.7229 - loss: 0.8130
Epoch 40/43
17/17 - 0s - 23ms/step - accuracy: 0.7249 - loss: 0.8089
Epoch 41/43
17/17 - 0s - 23ms/step - accuracy: 0.7232 - loss: 0.8067
Epoch 42/43
17/17 - 0s - 23ms/step - accuracy: 0.7197 - loss: 0.8076
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7211 - loss: 0.8066
5/5 - 0s - 31ms/step
| 7         | 0.7196    | 0.0497    | 852.4     | 0.7069    | 0.2187    | 43.14     | 1.148     | 1.717     | 1.232     | 0.8645    | 66.1      | 0.3309    | 0.4449    |
Epoch 1/47

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 56ms/step - accuracy: 0.0800 - loss: 2.6721
Epoch 2/47
30/30 - 0s - 13ms/step - accuracy: 0.0849 - loss: 2.6653
Epoch 3/47
30/30 - 0s - 13ms/step - accuracy: 0.0903 - loss: 2.6585
Epoch 4/47
30/30 - 0s - 13ms/step - accuracy: 0.0966 - loss: 2.6536
Epoch 5/47
30/30 - 0s - 12ms/step - accuracy: 0.1025 - loss: 2.6473
Epoch 6/47
30/30 - 0s - 13ms/step - accuracy: 0.1092 - loss: 2.6404
Epoch 7/47
30/30 - 0s - 13ms/step - accuracy: 0.1131 - loss: 2.6344
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.1219 - loss: 2.6256
Epoch 9/47
30/30 - 0s - 13ms/step - accuracy: 0.1309 - loss: 2.6190
Epoch 10/47
30/30 - 0s - 13ms/step - accuracy: 0.1354 - loss: 2.6113
Epoch 11/47
30/30 - 0s - 13ms/step - accuracy: 0.1449 - loss: 2.6043
Epoch 12/47
30/30 - 0s - 13ms/step - accuracy: 0.1539 - loss: 2.5968
Epoch 13/47
30/30 - 0s - 13ms/step - accuracy: 0.1665 - loss: 2.5886
Epoch 14/47
30/30 - 0s - 13ms/step - accuracy: 0.1755 - loss: 2.5814
Epoch 15/47
30/30 - 0s - 14ms/step - accuracy: 0.1810 - loss: 2.5742
Epoch 16/47
30/30 - 0s - 12ms/step - accuracy: 0.1910 - loss: 2.5656
Epoch 17/47
30/30 - 0s - 12ms/step - accuracy: 0.2097 - loss: 2.5585
Epoch 18/47
30/30 - 0s - 13ms/step - accuracy: 0.2177 - loss: 2.5509
Epoch 19/47
30/30 - 0s - 13ms/step - accuracy: 0.2285 - loss: 2.5424
Epoch 20/47
30/30 - 0s - 13ms/step - accuracy: 0.2422 - loss: 2.5326
Epoch 21/47
30/30 - 0s - 13ms/step - accuracy: 0.2497 - loss: 2.5254
Epoch 22/47
30/30 - 0s - 12ms/step - accuracy: 0.2636 - loss: 2.5169
Epoch 23/47
30/30 - 0s - 13ms/step - accuracy: 0.2771 - loss: 2.5088
Epoch 24/47
30/30 - 0s - 12ms/step - accuracy: 0.2891 - loss: 2.5004
Epoch 25/47
30/30 - 0s - 13ms/step - accuracy: 0.3034 - loss: 2.4922
Epoch 26/47
30/30 - 0s - 13ms/step - accuracy: 0.3170 - loss: 2.4826
Epoch 27/47
30/30 - 0s - 14ms/step - accuracy: 0.3292 - loss: 2.4748
Epoch 28/47
30/30 - 0s - 15ms/step - accuracy: 0.3329 - loss: 2.4678
Epoch 29/47
30/30 - 0s - 14ms/step - accuracy: 0.3525 - loss: 2.4551
Epoch 30/47
30/30 - 0s - 14ms/step - accuracy: 0.3629 - loss: 2.4483
Epoch 31/47
30/30 - 0s - 14ms/step - accuracy: 0.3791 - loss: 2.4369
Epoch 32/47
30/30 - 0s - 14ms/step - accuracy: 0.3911 - loss: 2.4302
Epoch 33/47
30/30 - 0s - 14ms/step - accuracy: 0.3992 - loss: 2.4216
Epoch 34/47
30/30 - 0s - 14ms/step - accuracy: 0.4164 - loss: 2.4113
Epoch 35/47
30/30 - 0s - 13ms/step - accuracy: 0.4238 - loss: 2.4016
Epoch 36/47
30/30 - 0s - 13ms/step - accuracy: 0.4407 - loss: 2.3935
Epoch 37/47
30/30 - 0s - 13ms/step - accuracy: 0.4462 - loss: 2.3827
Epoch 38/47
30/30 - 0s - 13ms/step - accuracy: 0.4522 - loss: 2.3754
Epoch 39/47
30/30 - 0s - 12ms/step - accuracy: 0.4622 - loss: 2.3655
Epoch 40/47
30/30 - 0s - 13ms/step - accuracy: 0.4737 - loss: 2.3569
Epoch 41/47
30/30 - 0s - 12ms/step - accuracy: 0.4853 - loss: 2.3462
Epoch 42/47
30/30 - 0s - 12ms/step - accuracy: 0.4949 - loss: 2.3376
Epoch 43/47
30/30 - 0s - 13ms/step - accuracy: 0.5024 - loss: 2.3273
Epoch 44/47
30/30 - 0s - 13ms/step - accuracy: 0.5137 - loss: 2.3167
Epoch 45/47
30/30 - 0s - 13ms/step - accuracy: 0.5162 - loss: 2.3065
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.5276 - loss: 2.2985
Epoch 47/47
30/30 - 0s - 12ms/step - accuracy: 0.5325 - loss: 2.2887
8/8 - 0s - 24ms/step
Epoch 1/47

C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 56ms/step - accuracy: 0.0760 - loss: 2.6583
Epoch 2/47
30/30 - 0s - 14ms/step - accuracy: 0.0811 - loss: 2.6518
Epoch 3/47
30/30 - 0s - 14ms/step - accuracy: 0.0854 - loss: 2.6459
Epoch 4/47
30/30 - 0s - 13ms/step - accuracy: 0.0912 - loss: 2.6407
Epoch 5/47
30/30 - 0s - 12ms/step - accuracy: 0.0970 - loss: 2.6322
Epoch 6/47
30/30 - 0s - 13ms/step - accuracy: 0.1076 - loss: 2.6248
Epoch 7/47
30/30 - 0s - 13ms/step - accuracy: 0.1150 - loss: 2.6195
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.1201 - loss: 2.6118
Epoch 9/47
30/30 - 0s - 12ms/step - accuracy: 0.1301 - loss: 2.6046
Epoch 10/47
30/30 - 0s - 13ms/step - accuracy: 0.1381 - loss: 2.5982
Epoch 11/47
30/30 - 0s - 13ms/step - accuracy: 0.1482 - loss: 2.5894
Epoch 12/47
30/30 - 0s - 15ms/step - accuracy: 0.1595 - loss: 2.5824
Epoch 13/47
30/30 - 0s - 16ms/step - accuracy: 0.1649 - loss: 2.5752
Epoch 14/47
30/30 - 0s - 14ms/step - accuracy: 0.1787 - loss: 2.5673
Epoch 15/47
30/30 - 0s - 15ms/step - accuracy: 0.1900 - loss: 2.5597
Epoch 16/47
30/30 - 0s - 15ms/step - accuracy: 0.1967 - loss: 2.5542
Epoch 17/47
30/30 - 0s - 14ms/step - accuracy: 0.2204 - loss: 2.5434
Epoch 18/47
30/30 - 0s - 14ms/step - accuracy: 0.2290 - loss: 2.5359
Epoch 19/47
30/30 - 0s - 15ms/step - accuracy: 0.2448 - loss: 2.5272
Epoch 20/47
30/30 - 0s - 14ms/step - accuracy: 0.2596 - loss: 2.5194
Epoch 21/47
30/30 - 0s - 14ms/step - accuracy: 0.2760 - loss: 2.5108
Epoch 22/47
30/30 - 0s - 15ms/step - accuracy: 0.2851 - loss: 2.5049
Epoch 23/47
30/30 - 0s - 15ms/step - accuracy: 0.3065 - loss: 2.4947
Epoch 24/47
30/30 - 0s - 13ms/step - accuracy: 0.3195 - loss: 2.4878
Epoch 25/47
30/30 - 0s - 13ms/step - accuracy: 0.3362 - loss: 2.4767
Epoch 26/47
30/30 - 0s - 13ms/step - accuracy: 0.3595 - loss: 2.4668
Epoch 27/47
30/30 - 0s - 13ms/step - accuracy: 0.3655 - loss: 2.4605
Epoch 28/47
30/30 - 0s - 13ms/step - accuracy: 0.3822 - loss: 2.4514
Epoch 29/47
30/30 - 0s - 12ms/step - accuracy: 0.4027 - loss: 2.4419
Epoch 30/47
30/30 - 0s - 13ms/step - accuracy: 0.4090 - loss: 2.4344
Epoch 31/47
30/30 - 0s - 13ms/step - accuracy: 0.4256 - loss: 2.4252
Epoch 32/47
30/30 - 0s - 13ms/step - accuracy: 0.4381 - loss: 2.4157
Epoch 33/47
30/30 - 0s - 14ms/step - accuracy: 0.4516 - loss: 2.4073
Epoch 34/47
30/30 - 0s - 13ms/step - accuracy: 0.4654 - loss: 2.3967
Epoch 35/47
30/30 - 0s - 14ms/step - accuracy: 0.4761 - loss: 2.3868
Epoch 36/47
30/30 - 0s - 14ms/step - accuracy: 0.4897 - loss: 2.3790
Epoch 37/47
30/30 - 0s - 14ms/step - accuracy: 0.4980 - loss: 2.3703
Epoch 38/47
30/30 - 0s - 15ms/step - accuracy: 0.5114 - loss: 2.3580
Epoch 39/47
30/30 - 0s - 13ms/step - accuracy: 0.5205 - loss: 2.3490
Epoch 40/47
30/30 - 0s - 15ms/step - accuracy: 0.5242 - loss: 2.3417
Epoch 41/47
30/30 - 0s - 14ms/step - accuracy: 0.5377 - loss: 2.3300
Epoch 42/47
30/30 - 0s - 13ms/step - accuracy: 0.5448 - loss: 2.3200
Epoch 43/47
30/30 - 0s - 14ms/step - accuracy: 0.5495 - loss: 2.3108
Epoch 44/47
30/30 - 0s - 13ms/step - accuracy: 0.5582 - loss: 2.3018
Epoch 45/47
30/30 - 0s - 13ms/step - accuracy: 0.5603 - loss: 2.2920
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.5683 - loss: 2.2825
Epoch 47/47
30/30 - 0s - 13ms/step - accuracy: 0.5703 - loss: 2.2740
8/8 - 0s - 24ms/step
Epoch 1/47

C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 72ms/step - accuracy: 0.0164 - loss: 2.8706
Epoch 2/47
30/30 - 0s - 14ms/step - accuracy: 0.0184 - loss: 2.8635
Epoch 3/47
30/30 - 0s - 14ms/step - accuracy: 0.0192 - loss: 2.8580
Epoch 4/47
30/30 - 0s - 16ms/step - accuracy: 0.0192 - loss: 2.8498
Epoch 5/47
30/30 - 0s - 15ms/step - accuracy: 0.0229 - loss: 2.8441
Epoch 6/47
30/30 - 0s - 15ms/step - accuracy: 0.0221 - loss: 2.8371
Epoch 7/47
30/30 - 0s - 14ms/step - accuracy: 0.0203 - loss: 2.8303
Epoch 8/47
30/30 - 0s - 15ms/step - accuracy: 0.0252 - loss: 2.8225
Epoch 9/47
30/30 - 0s - 14ms/step - accuracy: 0.0266 - loss: 2.8136
Epoch 10/47
30/30 - 0s - 14ms/step - accuracy: 0.0282 - loss: 2.8067
Epoch 11/47
30/30 - 0s - 13ms/step - accuracy: 0.0282 - loss: 2.8005
Epoch 12/47
30/30 - 0s - 13ms/step - accuracy: 0.0317 - loss: 2.7901
Epoch 13/47
30/30 - 1s - 21ms/step - accuracy: 0.0335 - loss: 2.7853
Epoch 14/47
30/30 - 1s - 17ms/step - accuracy: 0.0370 - loss: 2.7745
Epoch 15/47
30/30 - 1s - 17ms/step - accuracy: 0.0373 - loss: 2.7686
Epoch 16/47
30/30 - 1s - 20ms/step - accuracy: 0.0397 - loss: 2.7597
Epoch 17/47
30/30 - 1s - 18ms/step - accuracy: 0.0404 - loss: 2.7512
Epoch 18/47
30/30 - 1s - 19ms/step - accuracy: 0.0448 - loss: 2.7423
Epoch 19/47
30/30 - 1s - 17ms/step - accuracy: 0.0486 - loss: 2.7344
Epoch 20/47
30/30 - 1s - 24ms/step - accuracy: 0.0528 - loss: 2.7269
Epoch 21/47
30/30 - 1s - 17ms/step - accuracy: 0.0521 - loss: 2.7176
Epoch 22/47
30/30 - 1s - 19ms/step - accuracy: 0.0595 - loss: 2.7107
Epoch 23/47
30/30 - 0s - 15ms/step - accuracy: 0.0636 - loss: 2.6990
Epoch 24/47
30/30 - 0s - 13ms/step - accuracy: 0.0679 - loss: 2.6907
Epoch 25/47
30/30 - 0s - 14ms/step - accuracy: 0.0746 - loss: 2.6816
Epoch 26/47
30/30 - 0s - 16ms/step - accuracy: 0.0796 - loss: 2.6715
Epoch 27/47
30/30 - 0s - 16ms/step - accuracy: 0.0847 - loss: 2.6633
Epoch 28/47
30/30 - 0s - 14ms/step - accuracy: 0.0902 - loss: 2.6539
Epoch 29/47
30/30 - 0s - 16ms/step - accuracy: 0.0932 - loss: 2.6454
Epoch 30/47
30/30 - 0s - 13ms/step - accuracy: 0.0989 - loss: 2.6374
Epoch 31/47
30/30 - 0s - 12ms/step - accuracy: 0.1070 - loss: 2.6271
Epoch 32/47
30/30 - 0s - 12ms/step - accuracy: 0.1122 - loss: 2.6172
Epoch 33/47
30/30 - 1s - 19ms/step - accuracy: 0.1227 - loss: 2.6075
Epoch 34/47
30/30 - 1s - 19ms/step - accuracy: 0.1306 - loss: 2.5961
Epoch 35/47
30/30 - 1s - 18ms/step - accuracy: 0.1345 - loss: 2.5869
Epoch 36/47
30/30 - 0s - 17ms/step - accuracy: 0.1458 - loss: 2.5801
Epoch 37/47
30/30 - 1s - 21ms/step - accuracy: 0.1556 - loss: 2.5686
Epoch 38/47
30/30 - 1s - 20ms/step - accuracy: 0.1684 - loss: 2.5595
Epoch 39/47
30/30 - 1s - 22ms/step - accuracy: 0.1755 - loss: 2.5488
Epoch 40/47
30/30 - 1s - 21ms/step - accuracy: 0.1850 - loss: 2.5403
Epoch 41/47
30/30 - 1s - 17ms/step - accuracy: 0.1947 - loss: 2.5312
Epoch 42/47
30/30 - 1s - 17ms/step - accuracy: 0.2013 - loss: 2.5216
Epoch 43/47
30/30 - 1s - 19ms/step - accuracy: 0.2168 - loss: 2.5100
Epoch 44/47
30/30 - 1s - 19ms/step - accuracy: 0.2230 - loss: 2.5003
Epoch 45/47
30/30 - 0s - 13ms/step - accuracy: 0.2414 - loss: 2.4899
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.2558 - loss: 2.4795
Epoch 47/47
30/30 - 0s - 13ms/step - accuracy: 0.2640 - loss: 2.4694
8/8 - 0s - 24ms/step
Epoch 1/47

C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 71ms/step - accuracy: 0.0219 - loss: 2.7593
Epoch 2/47
30/30 - 1s - 19ms/step - accuracy: 0.0233 - loss: 2.7543
Epoch 3/47
30/30 - 0s - 15ms/step - accuracy: 0.0242 - loss: 2.7480
Epoch 4/47
30/30 - 0s - 15ms/step - accuracy: 0.0253 - loss: 2.7395
Epoch 5/47
30/30 - 0s - 16ms/step - accuracy: 0.0242 - loss: 2.7338
Epoch 6/47
30/30 - 0s - 16ms/step - accuracy: 0.0248 - loss: 2.7288
Epoch 7/47
30/30 - 0s - 12ms/step - accuracy: 0.0285 - loss: 2.7239
Epoch 8/47
30/30 - 0s - 11ms/step - accuracy: 0.0305 - loss: 2.7161
Epoch 9/47
30/30 - 0s - 11ms/step - accuracy: 0.0314 - loss: 2.7097
Epoch 10/47
30/30 - 1s - 20ms/step - accuracy: 0.0317 - loss: 2.7037
Epoch 11/47
30/30 - 1s - 20ms/step - accuracy: 0.0352 - loss: 2.6960
Epoch 12/47
30/30 - 1s - 18ms/step - accuracy: 0.0358 - loss: 2.6898
Epoch 13/47
30/30 - 1s - 18ms/step - accuracy: 0.0382 - loss: 2.6827
Epoch 14/47
30/30 - 1s - 19ms/step - accuracy: 0.0412 - loss: 2.6744
Epoch 15/47
30/30 - 0s - 17ms/step - accuracy: 0.0410 - loss: 2.6690
Epoch 16/47
30/30 - 0s - 15ms/step - accuracy: 0.0437 - loss: 2.6606
Epoch 17/47
30/30 - 0s - 17ms/step - accuracy: 0.0495 - loss: 2.6528
Epoch 18/47
30/30 - 0s - 16ms/step - accuracy: 0.0513 - loss: 2.6467
Epoch 19/47
30/30 - 0s - 14ms/step - accuracy: 0.0576 - loss: 2.6386
Epoch 20/47
30/30 - 0s - 14ms/step - accuracy: 0.0596 - loss: 2.6299
Epoch 21/47
30/30 - 0s - 14ms/step - accuracy: 0.0635 - loss: 2.6233
Epoch 22/47
30/30 - 0s - 16ms/step - accuracy: 0.0696 - loss: 2.6141
Epoch 23/47
30/30 - 0s - 13ms/step - accuracy: 0.0719 - loss: 2.6073
Epoch 24/47
30/30 - 0s - 15ms/step - accuracy: 0.0852 - loss: 2.5975
Epoch 25/47
30/30 - 0s - 15ms/step - accuracy: 0.0908 - loss: 2.5896
Epoch 26/47
30/30 - 0s - 16ms/step - accuracy: 0.0985 - loss: 2.5823
Epoch 27/47
30/30 - 0s - 15ms/step - accuracy: 0.1020 - loss: 2.5738
Epoch 28/47
30/30 - 0s - 15ms/step - accuracy: 0.1134 - loss: 2.5659
Epoch 29/47
30/30 - 0s - 16ms/step - accuracy: 0.1205 - loss: 2.5564
Epoch 30/47
30/30 - 0s - 15ms/step - accuracy: 0.1330 - loss: 2.5491
Epoch 31/47
30/30 - 0s - 14ms/step - accuracy: 0.1438 - loss: 2.5389
Epoch 32/47
30/30 - 0s - 16ms/step - accuracy: 0.1513 - loss: 2.5314
Epoch 33/47
30/30 - 0s - 15ms/step - accuracy: 0.1678 - loss: 2.5216
Epoch 34/47
30/30 - 0s - 15ms/step - accuracy: 0.1766 - loss: 2.5132
Epoch 35/47
30/30 - 0s - 16ms/step - accuracy: 0.1886 - loss: 2.5044
Epoch 36/47
30/30 - 1s - 17ms/step - accuracy: 0.2060 - loss: 2.4963
Epoch 37/47
30/30 - 0s - 13ms/step - accuracy: 0.2141 - loss: 2.4872
Epoch 38/47
30/30 - 0s - 16ms/step - accuracy: 0.2279 - loss: 2.4777
Epoch 39/47
30/30 - 1s - 17ms/step - accuracy: 0.2432 - loss: 2.4705
Epoch 40/47
30/30 - 1s - 17ms/step - accuracy: 0.2567 - loss: 2.4599
Epoch 41/47
30/30 - 1s - 17ms/step - accuracy: 0.2765 - loss: 2.4497
Epoch 42/47
30/30 - 1s - 18ms/step - accuracy: 0.2871 - loss: 2.4418
Epoch 43/47
30/30 - 0s - 16ms/step - accuracy: 0.3029 - loss: 2.4302
Epoch 44/47
30/30 - 1s - 17ms/step - accuracy: 0.3138 - loss: 2.4227
Epoch 45/47
30/30 - 1s - 18ms/step - accuracy: 0.3367 - loss: 2.4112
Epoch 46/47
30/30 - 1s - 18ms/step - accuracy: 0.3492 - loss: 2.4025
Epoch 47/47
30/30 - 0s - 16ms/step - accuracy: 0.3658 - loss: 2.3920
8/8 - 0s - 56ms/step

C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cschw\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/47
30/30 - 3s - 95ms/step - accuracy: 0.0445 - loss: 2.6697
Epoch 2/47
30/30 - 0s - 13ms/step - accuracy: 0.0497 - loss: 2.6626
Epoch 3/47
30/30 - 0s - 12ms/step - accuracy: 0.0529 - loss: 2.6561
Epoch 4/47
30/30 - 0s - 12ms/step - accuracy: 0.0579 - loss: 2.6483
Epoch 5/47
30/30 - 0s - 11ms/step - accuracy: 0.0645 - loss: 2.6432
Epoch 6/47
30/30 - 0s - 12ms/step - accuracy: 0.0687 - loss: 2.6334
Epoch 7/47
30/30 - 0s - 13ms/step - accuracy: 0.0764 - loss: 2.6270
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.0809 - loss: 2.6210
Epoch 9/47
30/30 - 0s - 14ms/step - accuracy: 0.0911 - loss: 2.6116
Epoch 10/47
30/30 - 0s - 14ms/step - accuracy: 0.0978 - loss: 2.6048
Epoch 11/47
30/30 - 0s - 14ms/step - accuracy: 0.1093 - loss: 2.5972
Epoch 12/47
30/30 - 0s - 16ms/step - accuracy: 0.1168 - loss: 2.5878
Epoch 13/47
30/30 - 1s - 21ms/step - accuracy: 0.1332 - loss: 2.5807
Epoch 14/47
30/30 - 1s - 22ms/step - accuracy: 0.1354 - loss: 2.5731
Epoch 15/47
30/30 - 1s - 17ms/step - accuracy: 0.1519 - loss: 2.5646
Epoch 16/47
30/30 - 1s - 18ms/step - accuracy: 0.1628 - loss: 2.5554
Epoch 17/47
30/30 - 1s - 20ms/step - accuracy: 0.1740 - loss: 2.5479
Epoch 18/47
30/30 - 1s - 18ms/step - accuracy: 0.1919 - loss: 2.5410
Epoch 19/47
30/30 - 0s - 16ms/step - accuracy: 0.2120 - loss: 2.5315
Epoch 20/47
30/30 - 0s - 16ms/step - accuracy: 0.2250 - loss: 2.5213
Epoch 21/47
30/30 - 0s - 16ms/step - accuracy: 0.2377 - loss: 2.5129
Epoch 22/47
30/30 - 1s - 18ms/step - accuracy: 0.2519 - loss: 2.5057
Epoch 23/47
30/30 - 0s - 15ms/step - accuracy: 0.2720 - loss: 2.4954
Epoch 24/47
30/30 - 0s - 17ms/step - accuracy: 0.2815 - loss: 2.4885
Epoch 25/47
30/30 - 1s - 24ms/step - accuracy: 0.3081 - loss: 2.4779
Epoch 26/47
30/30 - 1s - 21ms/step - accuracy: 0.3215 - loss: 2.4676
Epoch 27/47
30/30 - 1s - 25ms/step - accuracy: 0.3419 - loss: 2.4582
Epoch 28/47
30/30 - 1s - 21ms/step - accuracy: 0.3566 - loss: 2.4505
Epoch 29/47
30/30 - 1s - 19ms/step - accuracy: 0.3696 - loss: 2.4405
Epoch 30/47
30/30 - 1s - 19ms/step - accuracy: 0.3846 - loss: 2.4311
Epoch 31/47
30/30 - 1s - 19ms/step - accuracy: 0.4041 - loss: 2.4226
Epoch 32/47
30/30 - 1s - 21ms/step - accuracy: 0.4211 - loss: 2.4114
Epoch 33/47
30/30 - 1s - 19ms/step - accuracy: 0.4340 - loss: 2.4029
Epoch 34/47
30/30 - 1s - 20ms/step - accuracy: 0.4513 - loss: 2.3927
Epoch 35/47
30/30 - 1s - 19ms/step - accuracy: 0.4648 - loss: 2.3829
Epoch 36/47
30/30 - 1s - 20ms/step - accuracy: 0.4783 - loss: 2.3730
Epoch 37/47
30/30 - 1s - 17ms/step - accuracy: 0.4887 - loss: 2.3632
Epoch 38/47
30/30 - 1s - 18ms/step - accuracy: 0.5021 - loss: 2.3535
Epoch 39/47
30/30 - 0s - 14ms/step - accuracy: 0.5150 - loss: 2.3435
Epoch 40/47
30/30 - 1s - 20ms/step - accuracy: 0.5205 - loss: 2.3343
Epoch 41/47
30/30 - 1s - 18ms/step - accuracy: 0.5301 - loss: 2.3228
Epoch 42/47
30/30 - 1s - 23ms/step - accuracy: 0.5420 - loss: 2.3135
Epoch 43/47
30/30 - 1s - 22ms/step - accuracy: 0.5511 - loss: 2.3056
Epoch 44/47
30/30 - 0s - 14ms/step - accuracy: 0.5598 - loss: 2.2945
Epoch 45/47
30/30 - 0s - 13ms/step - accuracy: 0.5702 - loss: 2.2837
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.5717 - loss: 2.2747
Epoch 47/47
30/30 - 0s - 12ms/step - accuracy: 0.5800 - loss: 2.2644
8/8 - 0s - 23ms/step
| 8         | nan       | 2.799     | 460.1     | 0.7296    | 0.1913    | 46.62     | 1.944     | 1.239     | 2.426     | 0.7632    | 60.51     | 0.771     | 3.457     |
Epoch 1/21

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 2s - 90ms/step - accuracy: 0.4825 - loss: 2.0859
Epoch 2/21
26/26 - 0s - 6ms/step - accuracy: 0.6301 - loss: 1.1335
Epoch 3/21
26/26 - 0s - 7ms/step - accuracy: 0.6529 - loss: 1.0279
Epoch 4/21
26/26 - 0s - 7ms/step - accuracy: 0.6717 - loss: 0.9671
Epoch 5/21
26/26 - 0s - 7ms/step - accuracy: 0.6839 - loss: 0.9270
Epoch 6/21
26/26 - 0s - 8ms/step - accuracy: 0.6947 - loss: 0.8949
Epoch 7/21
26/26 - 0s - 8ms/step - accuracy: 0.7044 - loss: 0.8687
Epoch 8/21
26/26 - 0s - 9ms/step - accuracy: 0.7104 - loss: 0.8455
Epoch 9/21
26/26 - 0s - 8ms/step - accuracy: 0.7165 - loss: 0.8265
Epoch 10/21
26/26 - 0s - 8ms/step - accuracy: 0.7222 - loss: 0.8085
Epoch 11/21
26/26 - 0s - 10ms/step - accuracy: 0.7275 - loss: 0.7926
Epoch 12/21
26/26 - 0s - 8ms/step - accuracy: 0.7327 - loss: 0.7779
Epoch 13/21
26/26 - 0s - 10ms/step - accuracy: 0.7354 - loss: 0.7647
Epoch 14/21
26/26 - 0s - 10ms/step - accuracy: 0.7391 - loss: 0.7527
Epoch 15/21
26/26 - 0s - 10ms/step - accuracy: 0.7417 - loss: 0.7417
Epoch 16/21
26/26 - 0s - 10ms/step - accuracy: 0.7441 - loss: 0.7311
Epoch 17/21
26/26 - 0s - 10ms/step - accuracy: 0.7473 - loss: 0.7218
Epoch 18/21
26/26 - 0s - 9ms/step - accuracy: 0.7491 - loss: 0.7128
Epoch 19/21
26/26 - 0s - 9ms/step - accuracy: 0.7523 - loss: 0.7044
Epoch 20/21
26/26 - 0s - 9ms/step - accuracy: 0.7555 - loss: 0.6963
Epoch 21/21
26/26 - 0s - 11ms/step - accuracy: 0.7579 - loss: 0.6889
7/7 - 0s - 24ms/step
Epoch 1/21

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 2s - 77ms/step - accuracy: 0.4786 - loss: 1.8916
Epoch 2/21
26/26 - 0s - 9ms/step - accuracy: 0.6580 - loss: 1.0350
Epoch 3/21
26/26 - 0s - 12ms/step - accuracy: 0.6792 - loss: 0.9514
Epoch 4/21
26/26 - 0s - 9ms/step - accuracy: 0.6904 - loss: 0.9109
Epoch 5/21
26/26 - 0s - 9ms/step - accuracy: 0.7025 - loss: 0.8805
Epoch 6/21
26/26 - 0s - 8ms/step - accuracy: 0.7131 - loss: 0.8559
Epoch 7/21
26/26 - 0s - 9ms/step - accuracy: 0.7180 - loss: 0.8343
Epoch 8/21
26/26 - 0s - 12ms/step - accuracy: 0.7224 - loss: 0.8168
Epoch 9/21
26/26 - 0s - 8ms/step - accuracy: 0.7313 - loss: 0.7963
Epoch 10/21
26/26 - 0s - 9ms/step - accuracy: 0.7362 - loss: 0.7812
Epoch 11/21
26/26 - 0s - 10ms/step - accuracy: 0.7405 - loss: 0.7673
Epoch 12/21
26/26 - 0s - 9ms/step - accuracy: 0.7462 - loss: 0.7534
Epoch 13/21
26/26 - 0s - 9ms/step - accuracy: 0.7484 - loss: 0.7420
Epoch 14/21
26/26 - 0s - 9ms/step - accuracy: 0.7515 - loss: 0.7297
Epoch 15/21
26/26 - 0s - 9ms/step - accuracy: 0.7556 - loss: 0.7199
Epoch 16/21
26/26 - 0s - 9ms/step - accuracy: 0.7587 - loss: 0.7098
Epoch 17/21
26/26 - 0s - 9ms/step - accuracy: 0.7606 - loss: 0.7010
Epoch 18/21
26/26 - 0s - 9ms/step - accuracy: 0.7660 - loss: 0.6942
Epoch 19/21
26/26 - 0s - 9ms/step - accuracy: 0.7664 - loss: 0.6849
Epoch 20/21
26/26 - 0s - 9ms/step - accuracy: 0.7691 - loss: 0.6770
Epoch 21/21
26/26 - 0s - 8ms/step - accuracy: 0.7707 - loss: 0.6710
7/7 - 0s - 23ms/step
Epoch 1/21

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 2s - 63ms/step - accuracy: 0.5819 - loss: 1.4174
Epoch 2/21
26/26 - 0s - 9ms/step - accuracy: 0.6624 - loss: 0.9983
Epoch 3/21
26/26 - 0s - 9ms/step - accuracy: 0.6837 - loss: 0.9331
Epoch 4/21
26/26 - 0s - 9ms/step - accuracy: 0.6918 - loss: 0.9010
Epoch 5/21
26/26 - 0s - 8ms/step - accuracy: 0.6999 - loss: 0.8761
Epoch 6/21
26/26 - 0s - 10ms/step - accuracy: 0.7073 - loss: 0.8576
Epoch 7/21
26/26 - 0s - 10ms/step - accuracy: 0.7124 - loss: 0.8406
Epoch 8/21
26/26 - 0s - 12ms/step - accuracy: 0.7172 - loss: 0.8258
Epoch 9/21
26/26 - 0s - 9ms/step - accuracy: 0.7224 - loss: 0.8114
Epoch 10/21
26/26 - 0s - 9ms/step - accuracy: 0.7271 - loss: 0.7978
Epoch 11/21
26/26 - 0s - 9ms/step - accuracy: 0.7295 - loss: 0.7863
Epoch 12/21
26/26 - 0s - 8ms/step - accuracy: 0.7323 - loss: 0.7752
Epoch 13/21
26/26 - 0s - 10ms/step - accuracy: 0.7383 - loss: 0.7625
Epoch 14/21
26/26 - 0s - 10ms/step - accuracy: 0.7447 - loss: 0.7512
Epoch 15/21
26/26 - 0s - 8ms/step - accuracy: 0.7481 - loss: 0.7405
Epoch 16/21
26/26 - 0s - 8ms/step - accuracy: 0.7494 - loss: 0.7316
Epoch 17/21
26/26 - 0s - 8ms/step - accuracy: 0.7521 - loss: 0.7215
Epoch 18/21
26/26 - 0s - 8ms/step - accuracy: 0.7567 - loss: 0.7143
Epoch 19/21
26/26 - 0s - 11ms/step - accuracy: 0.7586 - loss: 0.7057
Epoch 20/21
26/26 - 0s - 12ms/step - accuracy: 0.7622 - loss: 0.6962
Epoch 21/21
26/26 - 0s - 12ms/step - accuracy: 0.7638 - loss: 0.6886
7/7 - 0s - 50ms/step
Epoch 1/21

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 2s - 94ms/step - accuracy: 0.5957 - loss: 1.4983
Epoch 2/21
26/26 - 0s - 8ms/step - accuracy: 0.6633 - loss: 0.9951
Epoch 3/21
26/26 - 0s - 9ms/step - accuracy: 0.6887 - loss: 0.9317
Epoch 4/21
26/26 - 0s - 9ms/step - accuracy: 0.6964 - loss: 0.8976
Epoch 5/21
26/26 - 0s - 9ms/step - accuracy: 0.7065 - loss: 0.8723
Epoch 6/21
26/26 - 0s - 15ms/step - accuracy: 0.7166 - loss: 0.8526
Epoch 7/21
26/26 - 0s - 8ms/step - accuracy: 0.7233 - loss: 0.8329
Epoch 8/21
26/26 - 0s - 8ms/step - accuracy: 0.7312 - loss: 0.8157
Epoch 9/21
26/26 - 0s - 8ms/step - accuracy: 0.7366 - loss: 0.7994
Epoch 10/21
26/26 - 0s - 8ms/step - accuracy: 0.7427 - loss: 0.7860
Epoch 11/21
26/26 - 0s - 9ms/step - accuracy: 0.7463 - loss: 0.7732
Epoch 12/21
26/26 - 0s - 8ms/step - accuracy: 0.7519 - loss: 0.7608
Epoch 13/21
26/26 - 0s - 9ms/step - accuracy: 0.7527 - loss: 0.7517
Epoch 14/21
26/26 - 0s - 8ms/step - accuracy: 0.7550 - loss: 0.7425
Epoch 15/21
26/26 - 0s - 9ms/step - accuracy: 0.7609 - loss: 0.7322
Epoch 16/21
26/26 - 0s - 8ms/step - accuracy: 0.7611 - loss: 0.7236
Epoch 17/21
26/26 - 0s - 9ms/step - accuracy: 0.7633 - loss: 0.7141
Epoch 18/21
26/26 - 0s - 8ms/step - accuracy: 0.7679 - loss: 0.7061
Epoch 19/21
26/26 - 0s - 7ms/step - accuracy: 0.7677 - loss: 0.6991
Epoch 20/21
26/26 - 0s - 7ms/step - accuracy: 0.7711 - loss: 0.6913
Epoch 21/21
26/26 - 0s - 8ms/step - accuracy: 0.7722 - loss: 0.6847
7/7 - 0s - 21ms/step
Epoch 1/21

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 1s - 50ms/step - accuracy: 0.5942 - loss: 1.4397
Epoch 2/21
26/26 - 0s - 6ms/step - accuracy: 0.6755 - loss: 0.9925
Epoch 3/21
26/26 - 0s - 6ms/step - accuracy: 0.6922 - loss: 0.9337
Epoch 4/21
26/26 - 0s - 6ms/step - accuracy: 0.7023 - loss: 0.9003
Epoch 5/21
26/26 - 0s - 7ms/step - accuracy: 0.7092 - loss: 0.8766
Epoch 6/21
26/26 - 0s - 7ms/step - accuracy: 0.7151 - loss: 0.8571
Epoch 7/21
26/26 - 0s - 6ms/step - accuracy: 0.7209 - loss: 0.8395
Epoch 8/21
26/26 - 0s - 7ms/step - accuracy: 0.7260 - loss: 0.8221
Epoch 9/21
26/26 - 0s - 6ms/step - accuracy: 0.7305 - loss: 0.8084
Epoch 10/21
26/26 - 0s - 7ms/step - accuracy: 0.7357 - loss: 0.7944
Epoch 11/21
26/26 - 0s - 8ms/step - accuracy: 0.7379 - loss: 0.7820
Epoch 12/21
26/26 - 0s - 6ms/step - accuracy: 0.7432 - loss: 0.7699
Epoch 13/21
26/26 - 0s - 6ms/step - accuracy: 0.7468 - loss: 0.7592
Epoch 14/21
26/26 - 0s - 7ms/step - accuracy: 0.7492 - loss: 0.7498
Epoch 15/21
26/26 - 0s - 7ms/step - accuracy: 0.7520 - loss: 0.7398
Epoch 16/21
26/26 - 0s - 8ms/step - accuracy: 0.7535 - loss: 0.7333
Epoch 17/21
26/26 - 0s - 7ms/step - accuracy: 0.7568 - loss: 0.7244
Epoch 18/21
26/26 - 0s - 6ms/step - accuracy: 0.7584 - loss: 0.7144
Epoch 19/21
26/26 - 0s - 7ms/step - accuracy: 0.7582 - loss: 0.7093
Epoch 20/21
26/26 - 0s - 8ms/step - accuracy: 0.7636 - loss: 0.7009
Epoch 21/21
26/26 - 0s - 7ms/step - accuracy: 0.7638 - loss: 0.6921
7/7 - 0s - 20ms/step
| 9         | 0.7634    | 4.705     | 542.0     | 0.02542   | 0.03237   | 20.94     | 2.273     | 1.629     | 2.017     | 0.9085    | 32.44     | 0.4104    | 5.289     |
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 2s - 30ms/step - accuracy: 0.0011 - loss: 2.8104
Epoch 2/48
53/53 - 0s - 8ms/step - accuracy: 0.3304 - loss: 1.7172
Epoch 3/48
53/53 - 0s - 9ms/step - accuracy: 0.6437 - loss: 1.3927
Epoch 4/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.2849
Epoch 5/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.2379
Epoch 6/48
53/53 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.2113
Epoch 7/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.1935
Epoch 8/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1802
Epoch 9/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1692
Epoch 10/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1595
Epoch 11/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1507
Epoch 12/48
53/53 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1424
Epoch 13/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1345
Epoch 14/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1268
Epoch 15/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1192
Epoch 16/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1124
Epoch 17/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1056
Epoch 18/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0991
Epoch 19/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0930
Epoch 20/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0877
Epoch 21/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0831
Epoch 22/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0787
Epoch 23/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0748
Epoch 24/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.0712
Epoch 25/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0676
Epoch 26/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0649
Epoch 27/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0626
Epoch 28/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0599
Epoch 29/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0572
Epoch 30/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0552
Epoch 31/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0528
Epoch 32/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0508
Epoch 33/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0486
Epoch 34/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0466
Epoch 35/48
53/53 - 0s - 8ms/step - accuracy: 0.6441 - loss: 1.0447
Epoch 36/48
53/53 - 0s - 7ms/step - accuracy: 0.6441 - loss: 1.0424
Epoch 37/48
53/53 - 0s - 7ms/step - accuracy: 0.6444 - loss: 1.0411
Epoch 38/48
53/53 - 0s - 7ms/step - accuracy: 0.6448 - loss: 1.0387
Epoch 39/48
53/53 - 0s - 8ms/step - accuracy: 0.6449 - loss: 1.0369
Epoch 40/48
53/53 - 0s - 8ms/step - accuracy: 0.6457 - loss: 1.0355
Epoch 41/48
53/53 - 0s - 9ms/step - accuracy: 0.6464 - loss: 1.0330
Epoch 42/48
53/53 - 0s - 8ms/step - accuracy: 0.6462 - loss: 1.0318
Epoch 43/48
53/53 - 0s - 9ms/step - accuracy: 0.6467 - loss: 1.0298
Epoch 44/48
53/53 - 0s - 8ms/step - accuracy: 0.6479 - loss: 1.0281
Epoch 45/48
53/53 - 0s - 8ms/step - accuracy: 0.6497 - loss: 1.0263
Epoch 46/48
53/53 - 1s - 12ms/step - accuracy: 0.6491 - loss: 1.0241
Epoch 47/48
53/53 - 0s - 8ms/step - accuracy: 0.6510 - loss: 1.0228
Epoch 48/48
53/53 - 0s - 8ms/step - accuracy: 0.6520 - loss: 1.0207
14/14 - 0s - 17ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 2s - 31ms/step - accuracy: 0.5247 - loss: 1.6768
Epoch 2/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.2905
Epoch 3/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.2275
Epoch 4/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.2018
Epoch 5/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1876
Epoch 6/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1781
Epoch 7/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1711
Epoch 8/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 9/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1606
Epoch 10/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1563
Epoch 11/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.1525
Epoch 12/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1489
Epoch 13/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1455
Epoch 14/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1423
Epoch 15/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1390
Epoch 16/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1360
Epoch 17/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1330
Epoch 18/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1300
Epoch 19/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1270
Epoch 20/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1239
Epoch 21/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1210
Epoch 22/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1178
Epoch 23/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1147
Epoch 24/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1117
Epoch 25/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1084
Epoch 26/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.1053
Epoch 27/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1022
Epoch 28/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0992
Epoch 29/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0959
Epoch 30/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0929
Epoch 31/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0898
Epoch 32/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0867
Epoch 33/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0838
Epoch 34/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0810
Epoch 35/48
53/53 - 0s - 8ms/step - accuracy: 0.6441 - loss: 1.0782
Epoch 36/48
53/53 - 0s - 8ms/step - accuracy: 0.6441 - loss: 1.0754
Epoch 37/48
53/53 - 0s - 8ms/step - accuracy: 0.6445 - loss: 1.0727
Epoch 38/48
53/53 - 0s - 8ms/step - accuracy: 0.6451 - loss: 1.0704
Epoch 39/48
53/53 - 0s - 7ms/step - accuracy: 0.6454 - loss: 1.0678
Epoch 40/48
53/53 - 1s - 13ms/step - accuracy: 0.6458 - loss: 1.0656
Epoch 41/48
53/53 - 0s - 8ms/step - accuracy: 0.6459 - loss: 1.0634
Epoch 42/48
53/53 - 0s - 7ms/step - accuracy: 0.6470 - loss: 1.0614
Epoch 43/48
53/53 - 0s - 8ms/step - accuracy: 0.6484 - loss: 1.0589
Epoch 44/48
53/53 - 0s - 8ms/step - accuracy: 0.6481 - loss: 1.0574
Epoch 45/48
53/53 - 0s - 8ms/step - accuracy: 0.6494 - loss: 1.0553
Epoch 46/48
53/53 - 0s - 8ms/step - accuracy: 0.6485 - loss: 1.0534
Epoch 47/48
53/53 - 0s - 8ms/step - accuracy: 0.6496 - loss: 1.0520
Epoch 48/48
53/53 - 0s - 8ms/step - accuracy: 0.6496 - loss: 1.0502
14/14 - 0s - 18ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 2s - 43ms/step - accuracy: 0.0000e+00 - loss: 3.4467
Epoch 2/48
53/53 - 0s - 8ms/step - accuracy: 0.1400 - loss: 2.1802
Epoch 3/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.6245
Epoch 4/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.3834
Epoch 5/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.2817
Epoch 6/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.2323
Epoch 7/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.2031
Epoch 8/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1828
Epoch 9/48
53/53 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1678
Epoch 10/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1555
Epoch 11/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1454
Epoch 12/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1366
Epoch 13/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1287
Epoch 14/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1217
Epoch 15/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1154
Epoch 16/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1093
Epoch 17/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1042
Epoch 18/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0989
Epoch 19/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0944
Epoch 20/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0901
Epoch 21/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0864
Epoch 22/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0823
Epoch 23/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0790
Epoch 24/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0758
Epoch 25/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0728
Epoch 26/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0700
Epoch 27/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0671
Epoch 28/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0651
Epoch 29/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.0629
Epoch 30/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0607
Epoch 31/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0586
Epoch 32/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0567
Epoch 33/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0549
Epoch 34/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0532
Epoch 35/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0516
Epoch 36/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0495
Epoch 37/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0483
Epoch 38/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0464
Epoch 39/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0447
Epoch 40/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0433
Epoch 41/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0419
Epoch 42/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0407
Epoch 43/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0389
Epoch 44/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0384
Epoch 45/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0364
Epoch 46/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0351
Epoch 47/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0342
Epoch 48/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.0327
14/14 - 0s - 22ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 2s - 29ms/step - accuracy: 0.2564 - loss: 2.3822
Epoch 2/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.5235
Epoch 3/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.3032
Epoch 4/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.2349
Epoch 5/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.2042
Epoch 6/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1860
Epoch 7/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1732
Epoch 8/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1633
Epoch 9/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1551
Epoch 10/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1481
Epoch 11/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1416
Epoch 12/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1357
Epoch 13/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1304
Epoch 14/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1252
Epoch 15/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1203
Epoch 16/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1156
Epoch 17/48
53/53 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.1113
Epoch 18/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1071
Epoch 19/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1029
Epoch 20/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0990
Epoch 21/48
53/53 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.0950
Epoch 22/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0916
Epoch 23/48
53/53 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.0881
Epoch 24/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0848
Epoch 25/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0819
Epoch 26/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0786
Epoch 27/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0761
Epoch 28/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0737
Epoch 29/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0708
Epoch 30/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.0688
Epoch 31/48
53/53 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0667
Epoch 32/48
53/53 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0641
Epoch 33/48
53/53 - 1s - 10ms/step - accuracy: 0.6440 - loss: 1.0622
Epoch 34/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0605
Epoch 35/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0590
Epoch 36/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0570
Epoch 37/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0552
Epoch 38/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0542
Epoch 39/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0523
Epoch 40/48
53/53 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0511
Epoch 41/48
53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0501
Epoch 42/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0483
Epoch 43/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0468
Epoch 44/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0459
Epoch 45/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0448
Epoch 46/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0435
Epoch 47/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0426
Epoch 48/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0415
14/14 - 0s - 16ms/step
Epoch 1/48

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 1s - 26ms/step - accuracy: 0.4947 - loss: 1.7537
Epoch 2/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.3391
Epoch 3/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.2488
Epoch 4/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.2140
Epoch 5/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1951
Epoch 6/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1825
Epoch 7/48
53/53 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1734
Epoch 8/48
53/53 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.1661
Epoch 9/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1597
Epoch 10/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1541
Epoch 11/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1488
Epoch 12/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1440
Epoch 13/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.1392
Epoch 14/48
53/53 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1346
Epoch 15/48
53/53 - 1s - 13ms/step - accuracy: 0.6439 - loss: 1.1298
Epoch 16/48
53/53 - 1s - 12ms/step - accuracy: 0.6439 - loss: 1.1250
Epoch 17/48
53/53 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1204
Epoch 18/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1159
Epoch 19/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1113
Epoch 20/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.1069
Epoch 21/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1026
Epoch 22/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0986
Epoch 23/48
53/53 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0948
Epoch 24/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.0911
Epoch 25/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.0879
Epoch 26/48
53/53 - 1s - 10ms/step - accuracy: 0.6439 - loss: 1.0842
Epoch 27/48
53/53 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0812
Epoch 28/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0787
Epoch 29/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0764
Epoch 30/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0740
Epoch 31/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0722
Epoch 32/48
53/53 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0702
Epoch 33/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0685
Epoch 34/48
53/53 - 0s - 7ms/step - accuracy: 0.6438 - loss: 1.0670
Epoch 35/48
53/53 - 0s - 7ms/step - accuracy: 0.6442 - loss: 1.0658
Epoch 36/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0638
Epoch 37/48
53/53 - 0s - 7ms/step - accuracy: 0.6434 - loss: 1.0625
Epoch 38/48
53/53 - 0s - 8ms/step - accuracy: 0.6431 - loss: 1.0614
Epoch 39/48
53/53 - 0s - 7ms/step - accuracy: 0.6431 - loss: 1.0602
Epoch 40/48
53/53 - 0s - 7ms/step - accuracy: 0.6433 - loss: 1.0590
Epoch 41/48
53/53 - 0s - 6ms/step - accuracy: 0.6438 - loss: 1.0574
Epoch 42/48
53/53 - 0s - 7ms/step - accuracy: 0.6435 - loss: 1.0569
Epoch 43/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0560
Epoch 44/48
53/53 - 0s - 7ms/step - accuracy: 0.6439 - loss: 1.0549
Epoch 45/48
53/53 - 0s - 7ms/step - accuracy: 0.6447 - loss: 1.0539
Epoch 46/48
53/53 - 0s - 7ms/step - accuracy: 0.6442 - loss: 1.0529
Epoch 47/48
53/53 - 0s - 7ms/step - accuracy: 0.6442 - loss: 1.0522
Epoch 48/48
53/53 - 0s - 7ms/step - accuracy: 0.6450 - loss: 1.0512
14/14 - 0s - 15ms/step
| 10        | 0.6484    | 2.059     | 261.6     | 0.2898    | 0.04837   | 47.89     | 2.616     | 2.267     | 2.743     | 0.8056    | 26.79     | 0.8926    | 3.775     |
Epoch 1/27

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 89ms/step - accuracy: 0.6151 - loss: nan
Epoch 2/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 48ms/step
Epoch 1/27

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 88ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 72ms/step
Epoch 1/27

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 133ms/step - accuracy: 0.6140 - loss: nan
Epoch 2/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
4/4 - 0s - 53ms/step
Epoch 1/27

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 2s - 101ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 1s - 42ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 25ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 23ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 52ms/step
Epoch 1/27

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 87ms/step - accuracy: 0.6050 - loss: nan
Epoch 2/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/27
16/16 - 0s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/27
16/16 - 0s - 24ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/27
16/16 - 0s - 25ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
4/4 - 0s - 58ms/step
| 11        | 0.644     | 7.267     | 916.9     | 0.318     | 0.03302   | 26.84     | 1.854     | 2.636     | 2.721     | 0.01688   | 55.97     | 0.4174    | 1.555     |
Epoch 1/36

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 49ms/step - accuracy: 0.6223 - loss: 1.3516
Epoch 2/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1692
Epoch 3/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 4/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 5/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 6/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1670
Epoch 7/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 8/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1661
Epoch 9/36
30/30 - 0s - 11ms/step - accuracy: 0.6440 - loss: 1.1634
Epoch 10/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1652
Epoch 11/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1641
Epoch 12/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 13/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1641
Epoch 14/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1631
Epoch 15/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1635
Epoch 16/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1623
Epoch 17/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1614
Epoch 18/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1601
Epoch 19/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1566
Epoch 20/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1496
Epoch 21/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1316
Epoch 22/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1022
Epoch 23/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0688
Epoch 24/36
30/30 - 0s - 9ms/step - accuracy: 0.6420 - loss: 1.0427
Epoch 25/36
30/30 - 0s - 10ms/step - accuracy: 0.6432 - loss: 1.0269
Epoch 26/36
30/30 - 0s - 11ms/step - accuracy: 0.6391 - loss: 1.0160
Epoch 27/36
30/30 - 0s - 11ms/step - accuracy: 0.6404 - loss: 1.0033
Epoch 28/36
30/30 - 0s - 12ms/step - accuracy: 0.6388 - loss: 0.9945
Epoch 29/36
30/30 - 0s - 11ms/step - accuracy: 0.6406 - loss: 0.9813
Epoch 30/36
30/30 - 0s - 11ms/step - accuracy: 0.6400 - loss: 0.9702
Epoch 31/36
30/30 - 0s - 12ms/step - accuracy: 0.6370 - loss: 0.9607
Epoch 32/36
30/30 - 0s - 10ms/step - accuracy: 0.6419 - loss: 0.9488
Epoch 33/36
30/30 - 0s - 9ms/step - accuracy: 0.6419 - loss: 0.9372
Epoch 34/36
30/30 - 0s - 9ms/step - accuracy: 0.6504 - loss: 0.9264
Epoch 35/36
30/30 - 0s - 8ms/step - accuracy: 0.6581 - loss: 0.9167
Epoch 36/36
30/30 - 0s - 9ms/step - accuracy: 0.6654 - loss: 0.9052
8/8 - 0s - 23ms/step
Epoch 1/36

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 57ms/step - accuracy: 0.6235 - loss: 1.3221
Epoch 2/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1681
Epoch 3/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1659
Epoch 4/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 5/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1665
Epoch 6/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1647
Epoch 7/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1647
Epoch 8/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1641
Epoch 9/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1648
Epoch 10/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1645
Epoch 11/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1648
Epoch 12/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1650
Epoch 13/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1639
Epoch 14/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1635
Epoch 15/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1641
Epoch 16/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1629
Epoch 17/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1632
Epoch 18/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1616
Epoch 19/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1614
Epoch 20/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1568
Epoch 21/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1491
Epoch 22/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1325
Epoch 23/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.0984
Epoch 24/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0635
Epoch 25/36
30/30 - 0s - 9ms/step - accuracy: 0.6412 - loss: 1.0433
Epoch 26/36
30/30 - 0s - 8ms/step - accuracy: 0.6400 - loss: 1.0316
Epoch 27/36
30/30 - 0s - 8ms/step - accuracy: 0.6411 - loss: 1.0222
Epoch 28/36
30/30 - 0s - 9ms/step - accuracy: 0.6427 - loss: 1.0125
Epoch 29/36
30/30 - 0s - 8ms/step - accuracy: 0.6399 - loss: 1.0060
Epoch 30/36
30/30 - 0s - 9ms/step - accuracy: 0.6392 - loss: 0.9962
Epoch 31/36
30/30 - 0s - 9ms/step - accuracy: 0.6417 - loss: 0.9887
Epoch 32/36
30/30 - 0s - 8ms/step - accuracy: 0.6406 - loss: 0.9801
Epoch 33/36
30/30 - 0s - 9ms/step - accuracy: 0.6420 - loss: 0.9720
Epoch 34/36
30/30 - 0s - 9ms/step - accuracy: 0.6390 - loss: 0.9644
Epoch 35/36
30/30 - 0s - 9ms/step - accuracy: 0.6416 - loss: 0.9583
Epoch 36/36
30/30 - 0s - 9ms/step - accuracy: 0.6430 - loss: 0.9478
8/8 - 0s - 22ms/step
Epoch 1/36

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 2s - 56ms/step - accuracy: 0.6227 - loss: 1.3171
Epoch 2/36
30/30 - 0s - 11ms/step - accuracy: 0.6439 - loss: 1.1683
Epoch 3/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1658
Epoch 4/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1673
Epoch 5/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1655
Epoch 6/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1645
Epoch 7/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 8/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1641
Epoch 9/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 10/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1660
Epoch 11/36
30/30 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.1637
Epoch 12/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1656
Epoch 13/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1642
Epoch 14/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1630
Epoch 15/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1643
Epoch 16/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1637
Epoch 17/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1634
Epoch 18/36
30/30 - 0s - 11ms/step - accuracy: 0.6439 - loss: 1.1621
Epoch 19/36
30/30 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.1608
Epoch 20/36
30/30 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.1586
Epoch 21/36
30/30 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.1523
Epoch 22/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1380
Epoch 23/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1059
Epoch 24/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0663
Epoch 25/36
30/30 - 0s - 9ms/step - accuracy: 0.6399 - loss: 1.0446
Epoch 26/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.0276
Epoch 27/36
30/30 - 0s - 9ms/step - accuracy: 0.6398 - loss: 1.0184
Epoch 28/36
30/30 - 0s - 9ms/step - accuracy: 0.6405 - loss: 1.0065
Epoch 29/36
30/30 - 0s - 8ms/step - accuracy: 0.6419 - loss: 0.9974
Epoch 30/36
30/30 - 0s - 9ms/step - accuracy: 0.6429 - loss: 0.9865
Epoch 31/36
30/30 - 0s - 8ms/step - accuracy: 0.6423 - loss: 0.9777
Epoch 32/36
30/30 - 0s - 9ms/step - accuracy: 0.6423 - loss: 0.9700
Epoch 33/36
30/30 - 0s - 9ms/step - accuracy: 0.6428 - loss: 0.9621
Epoch 34/36
30/30 - 0s - 9ms/step - accuracy: 0.6423 - loss: 0.9517
Epoch 35/36
30/30 - 0s - 9ms/step - accuracy: 0.6437 - loss: 0.9429
Epoch 36/36
30/30 - 0s - 9ms/step - accuracy: 0.6436 - loss: 0.9330
8/8 - 0s - 21ms/step
Epoch 1/36

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 41ms/step - accuracy: 0.5969 - loss: 1.3714
Epoch 2/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1683
Epoch 3/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1665
Epoch 4/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1653
Epoch 5/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1650
Epoch 6/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1653
Epoch 7/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1650
Epoch 8/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 9/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 10/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1636
Epoch 11/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 12/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 13/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1646
Epoch 14/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 15/36
30/30 - 0s - 8ms/step - accuracy: 0.6440 - loss: 1.1644
Epoch 16/36
30/30 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.1633
Epoch 17/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1622
Epoch 18/36
30/30 - 0s - 11ms/step - accuracy: 0.6440 - loss: 1.1614
Epoch 19/36
30/30 - 0s - 11ms/step - accuracy: 0.6440 - loss: 1.1588
Epoch 20/36
30/30 - 0s - 11ms/step - accuracy: 0.6440 - loss: 1.1544
Epoch 21/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1464
Epoch 22/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.1251
Epoch 23/36
30/30 - 0s - 11ms/step - accuracy: 0.6440 - loss: 1.0911
Epoch 24/36
30/30 - 0s - 10ms/step - accuracy: 0.6440 - loss: 1.0542
Epoch 25/36
30/30 - 0s - 10ms/step - accuracy: 0.6437 - loss: 1.0362
Epoch 26/36
30/30 - 0s - 9ms/step - accuracy: 0.6438 - loss: 1.0210
Epoch 27/36
30/30 - 0s - 8ms/step - accuracy: 0.6405 - loss: 1.0108
Epoch 28/36
30/30 - 0s - 8ms/step - accuracy: 0.6430 - loss: 1.0002
Epoch 29/36
30/30 - 0s - 10ms/step - accuracy: 0.6425 - loss: 0.9899
Epoch 30/36
30/30 - 0s - 11ms/step - accuracy: 0.6421 - loss: 0.9795
Epoch 31/36
30/30 - 0s - 10ms/step - accuracy: 0.6386 - loss: 0.9709
Epoch 32/36
30/30 - 0s - 8ms/step - accuracy: 0.6397 - loss: 0.9615
Epoch 33/36
30/30 - 0s - 8ms/step - accuracy: 0.6391 - loss: 0.9528
Epoch 34/36
30/30 - 0s - 9ms/step - accuracy: 0.6394 - loss: 0.9430
Epoch 35/36
30/30 - 0s - 9ms/step - accuracy: 0.6397 - loss: 0.9326
Epoch 36/36
30/30 - 0s - 8ms/step - accuracy: 0.6492 - loss: 0.9228
8/8 - 0s - 21ms/step
Epoch 1/36

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 41ms/step - accuracy: 0.5920 - loss: 1.3436
Epoch 2/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1677
Epoch 3/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1674
Epoch 4/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1656
Epoch 5/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1655
Epoch 6/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1658
Epoch 7/36
30/30 - 0s - 10ms/step - accuracy: 0.6439 - loss: 1.1640
Epoch 8/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1653
Epoch 9/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 10/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 11/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 12/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1647
Epoch 13/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 14/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 15/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1651
Epoch 16/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1647
Epoch 17/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1639
Epoch 18/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1642
Epoch 19/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1644
Epoch 20/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1639
Epoch 21/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1642
Epoch 22/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1641
Epoch 23/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1629
Epoch 24/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1621
Epoch 25/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1594
Epoch 26/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1578
Epoch 27/36
30/30 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.1517
Epoch 28/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1363
Epoch 29/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.1084
Epoch 30/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0744
Epoch 31/36
30/30 - 0s - 9ms/step - accuracy: 0.6439 - loss: 1.0525
Epoch 32/36
30/30 - 0s - 9ms/step - accuracy: 0.6434 - loss: 1.0403
Epoch 33/36
30/30 - 0s - 8ms/step - accuracy: 0.6433 - loss: 1.0313
Epoch 34/36
30/30 - 0s - 9ms/step - accuracy: 0.6433 - loss: 1.0230
Epoch 35/36
30/30 - 0s - 10ms/step - accuracy: 0.6428 - loss: 1.0168
Epoch 36/36
30/30 - 0s - 11ms/step - accuracy: 0.6436 - loss: 1.0093
8/8 - 0s - 29ms/step
| 12        | 0.6465    | 1.079     | 470.1     | 0.9429    | 0.09696   | 35.56     | 2.406     | 1.727     | 2.944     | 0.9628    | 32.66     | 0.4972    | 2.106     |
Epoch 1/22

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 2s - 30ms/step - accuracy: 0.6465 - loss: 1.1741
Epoch 2/22
60/60 - 1s - 9ms/step - accuracy: 0.7131 - loss: 0.8359
Epoch 3/22
60/60 - 0s - 8ms/step - accuracy: 0.7430 - loss: 0.7501
Epoch 4/22
60/60 - 0s - 8ms/step - accuracy: 0.7641 - loss: 0.6863
Epoch 5/22
60/60 - 0s - 8ms/step - accuracy: 0.7760 - loss: 0.6445
Epoch 6/22
60/60 - 0s - 8ms/step - accuracy: 0.7882 - loss: 0.6098
Epoch 7/22
60/60 - 0s - 8ms/step - accuracy: 0.7954 - loss: 0.5807
Epoch 8/22
60/60 - 0s - 8ms/step - accuracy: 0.8072 - loss: 0.5533
Epoch 9/22
60/60 - 0s - 8ms/step - accuracy: 0.8147 - loss: 0.5285
Epoch 10/22
60/60 - 1s - 8ms/step - accuracy: 0.8205 - loss: 0.5110
Epoch 11/22
60/60 - 0s - 8ms/step - accuracy: 0.8257 - loss: 0.4876
Epoch 12/22
60/60 - 0s - 8ms/step - accuracy: 0.8335 - loss: 0.4741
Epoch 13/22
60/60 - 0s - 8ms/step - accuracy: 0.8359 - loss: 0.4618
Epoch 14/22
60/60 - 0s - 8ms/step - accuracy: 0.8420 - loss: 0.4421
Epoch 15/22
60/60 - 1s - 9ms/step - accuracy: 0.8450 - loss: 0.4335
Epoch 16/22
60/60 - 1s - 9ms/step - accuracy: 0.8539 - loss: 0.4201
Epoch 17/22
60/60 - 1s - 9ms/step - accuracy: 0.8534 - loss: 0.4145
Epoch 18/22
60/60 - 1s - 9ms/step - accuracy: 0.8552 - loss: 0.4045
Epoch 19/22
60/60 - 1s - 8ms/step - accuracy: 0.8613 - loss: 0.3948
Epoch 20/22
60/60 - 1s - 8ms/step - accuracy: 0.8601 - loss: 0.3922
Epoch 21/22
60/60 - 1s - 8ms/step - accuracy: 0.8600 - loss: 0.3891
Epoch 22/22
60/60 - 1s - 9ms/step - accuracy: 0.8688 - loss: 0.3737
15/15 - 0s - 16ms/step
Epoch 1/22

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 2s - 38ms/step - accuracy: 0.6480 - loss: 1.1660
Epoch 2/22
60/60 - 1s - 11ms/step - accuracy: 0.7341 - loss: 0.7991
Epoch 3/22
60/60 - 1s - 10ms/step - accuracy: 0.7635 - loss: 0.7108
Epoch 4/22
60/60 - 1s - 10ms/step - accuracy: 0.7786 - loss: 0.6567
Epoch 5/22
60/60 - 1s - 10ms/step - accuracy: 0.7891 - loss: 0.6145
Epoch 6/22
60/60 - 1s - 9ms/step - accuracy: 0.7956 - loss: 0.5877
Epoch 7/22
60/60 - 1s - 9ms/step - accuracy: 0.8027 - loss: 0.5654
Epoch 8/22
60/60 - 1s - 9ms/step - accuracy: 0.8041 - loss: 0.5469
Epoch 9/22
60/60 - 1s - 9ms/step - accuracy: 0.8118 - loss: 0.5297
Epoch 10/22
60/60 - 1s - 8ms/step - accuracy: 0.8175 - loss: 0.5118
Epoch 11/22
60/60 - 1s - 9ms/step - accuracy: 0.8220 - loss: 0.4993
Epoch 12/22
60/60 - 0s - 8ms/step - accuracy: 0.8250 - loss: 0.4834
Epoch 13/22
60/60 - 1s - 8ms/step - accuracy: 0.8295 - loss: 0.4755
Epoch 14/22
60/60 - 1s - 8ms/step - accuracy: 0.8335 - loss: 0.4589
Epoch 15/22
60/60 - 0s - 8ms/step - accuracy: 0.8359 - loss: 0.4520
Epoch 16/22
60/60 - 0s - 8ms/step - accuracy: 0.8385 - loss: 0.4382
Epoch 17/22
60/60 - 1s - 9ms/step - accuracy: 0.8449 - loss: 0.4287
Epoch 18/22
60/60 - 1s - 9ms/step - accuracy: 0.8527 - loss: 0.4123
Epoch 19/22
60/60 - 0s - 8ms/step - accuracy: 0.8535 - loss: 0.4029
Epoch 20/22
60/60 - 0s - 8ms/step - accuracy: 0.8572 - loss: 0.3948
Epoch 21/22
60/60 - 1s - 8ms/step - accuracy: 0.8581 - loss: 0.3870
Epoch 22/22
60/60 - 1s - 9ms/step - accuracy: 0.8640 - loss: 0.3768
15/15 - 0s - 17ms/step
Epoch 1/22

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 2s - 25ms/step - accuracy: 0.6585 - loss: 1.1143
Epoch 2/22
60/60 - 0s - 8ms/step - accuracy: 0.7200 - loss: 0.8063
Epoch 3/22
60/60 - 0s - 8ms/step - accuracy: 0.7517 - loss: 0.7240
Epoch 4/22
60/60 - 0s - 8ms/step - accuracy: 0.7696 - loss: 0.6662
Epoch 5/22
60/60 - 0s - 8ms/step - accuracy: 0.7872 - loss: 0.6179
Epoch 6/22
60/60 - 0s - 8ms/step - accuracy: 0.7944 - loss: 0.5862
Epoch 7/22
60/60 - 1s - 9ms/step - accuracy: 0.8055 - loss: 0.5583
Epoch 8/22
60/60 - 1s - 10ms/step - accuracy: 0.8065 - loss: 0.5414
Epoch 9/22
60/60 - 1s - 10ms/step - accuracy: 0.8153 - loss: 0.5218
Epoch 10/22
60/60 - 1s - 10ms/step - accuracy: 0.8211 - loss: 0.5018
Epoch 11/22
60/60 - 1s - 9ms/step - accuracy: 0.8306 - loss: 0.4865
Epoch 12/22
60/60 - 0s - 8ms/step - accuracy: 0.8317 - loss: 0.4723
Epoch 13/22
60/60 - 0s - 8ms/step - accuracy: 0.8370 - loss: 0.4627
Epoch 14/22
60/60 - 1s - 9ms/step - accuracy: 0.8420 - loss: 0.4483
Epoch 15/22
60/60 - 0s - 8ms/step - accuracy: 0.8458 - loss: 0.4340
Epoch 16/22
60/60 - 0s - 8ms/step - accuracy: 0.8479 - loss: 0.4285
Epoch 17/22
60/60 - 1s - 8ms/step - accuracy: 0.8528 - loss: 0.4160
Epoch 18/22
60/60 - 0s - 8ms/step - accuracy: 0.8556 - loss: 0.4041
Epoch 19/22
60/60 - 1s - 9ms/step - accuracy: 0.8600 - loss: 0.3961
Epoch 20/22
60/60 - 0s - 8ms/step - accuracy: 0.8624 - loss: 0.3908
Epoch 21/22
60/60 - 1s - 9ms/step - accuracy: 0.8623 - loss: 0.3799
Epoch 22/22
60/60 - 0s - 8ms/step - accuracy: 0.8694 - loss: 0.3731
15/15 - 0s - 16ms/step
Epoch 1/22

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 2s - 25ms/step - accuracy: 0.6455 - loss: 1.1638
Epoch 2/22
60/60 - 0s - 8ms/step - accuracy: 0.7222 - loss: 0.8067
Epoch 3/22
60/60 - 0s - 8ms/step - accuracy: 0.7538 - loss: 0.7243
Epoch 4/22
60/60 - 0s - 8ms/step - accuracy: 0.7715 - loss: 0.6681
Epoch 5/22
60/60 - 0s - 8ms/step - accuracy: 0.7857 - loss: 0.6244
Epoch 6/22
60/60 - 0s - 8ms/step - accuracy: 0.7975 - loss: 0.5901
Epoch 7/22
60/60 - 0s - 8ms/step - accuracy: 0.8034 - loss: 0.5652
Epoch 8/22
60/60 - 0s - 8ms/step - accuracy: 0.8125 - loss: 0.5408
Epoch 9/22
60/60 - 0s - 8ms/step - accuracy: 0.8153 - loss: 0.5265
Epoch 10/22
60/60 - 0s - 8ms/step - accuracy: 0.8222 - loss: 0.5097
Epoch 11/22
60/60 - 0s - 8ms/step - accuracy: 0.8264 - loss: 0.4931
Epoch 12/22
60/60 - 1s - 9ms/step - accuracy: 0.8331 - loss: 0.4754
Epoch 13/22
60/60 - 0s - 8ms/step - accuracy: 0.8341 - loss: 0.4659
Epoch 14/22
60/60 - 1s - 9ms/step - accuracy: 0.8390 - loss: 0.4533
Epoch 15/22
60/60 - 1s - 9ms/step - accuracy: 0.8426 - loss: 0.4395
Epoch 16/22
60/60 - 1s - 10ms/step - accuracy: 0.8442 - loss: 0.4341
Epoch 17/22
60/60 - 1s - 10ms/step - accuracy: 0.8484 - loss: 0.4206
Epoch 18/22
60/60 - 1s - 10ms/step - accuracy: 0.8529 - loss: 0.4075
Epoch 19/22
60/60 - 0s - 8ms/step - accuracy: 0.8547 - loss: 0.4009
Epoch 20/22
60/60 - 0s - 8ms/step - accuracy: 0.8589 - loss: 0.3918
Epoch 21/22
60/60 - 0s - 8ms/step - accuracy: 0.8656 - loss: 0.3777
Epoch 22/22
60/60 - 0s - 8ms/step - accuracy: 0.8656 - loss: 0.3775
15/15 - 0s - 16ms/step
Epoch 1/22

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 25ms/step - accuracy: 0.6460 - loss: 1.1795
Epoch 2/22
60/60 - 0s - 8ms/step - accuracy: 0.7194 - loss: 0.8159
Epoch 3/22
60/60 - 0s - 8ms/step - accuracy: 0.7544 - loss: 0.7142
Epoch 4/22
60/60 - 0s - 8ms/step - accuracy: 0.7763 - loss: 0.6506
Epoch 5/22
60/60 - 0s - 8ms/step - accuracy: 0.7909 - loss: 0.6066
Epoch 6/22
60/60 - 0s - 8ms/step - accuracy: 0.7996 - loss: 0.5770
Epoch 7/22
60/60 - 0s - 8ms/step - accuracy: 0.8073 - loss: 0.5505
Epoch 8/22
60/60 - 0s - 8ms/step - accuracy: 0.8121 - loss: 0.5325
Epoch 9/22
60/60 - 1s - 9ms/step - accuracy: 0.8179 - loss: 0.5121
Epoch 10/22
60/60 - 0s - 8ms/step - accuracy: 0.8282 - loss: 0.4891
Epoch 11/22
60/60 - 0s - 8ms/step - accuracy: 0.8305 - loss: 0.4781
Epoch 12/22
60/60 - 0s - 8ms/step - accuracy: 0.8376 - loss: 0.4624
Epoch 13/22
60/60 - 1s - 9ms/step - accuracy: 0.8418 - loss: 0.4459
Epoch 14/22
60/60 - 0s - 8ms/step - accuracy: 0.8442 - loss: 0.4361
Epoch 15/22
60/60 - 0s - 8ms/step - accuracy: 0.8510 - loss: 0.4259
Epoch 16/22
60/60 - 0s - 8ms/step - accuracy: 0.8505 - loss: 0.4156
Epoch 17/22
60/60 - 0s - 8ms/step - accuracy: 0.8530 - loss: 0.4042
Epoch 18/22
60/60 - 0s - 8ms/step - accuracy: 0.8571 - loss: 0.3932
Epoch 19/22
60/60 - 0s - 8ms/step - accuracy: 0.8646 - loss: 0.3874
Epoch 20/22
60/60 - 0s - 8ms/step - accuracy: 0.8666 - loss: 0.3748
Epoch 21/22
60/60 - 1s - 9ms/step - accuracy: 0.8659 - loss: 0.3728
Epoch 22/22
60/60 - 1s - 10ms/step - accuracy: 0.8717 - loss: 0.3624
15/15 - 0s - 18ms/step
| 13        | 0.8395    | 2.564     | 229.5     | 0.6096    | 0.1508    | 21.54     | 1.557     | 2.817     | 1.479     | 0.1534    | 54.05     | 0.9857    | 1.694     |
Epoch 1/31

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 2s - 108ms/step - accuracy: 0.6056 - loss: 1.2654
Epoch 2/31
18/18 - 1s - 29ms/step - accuracy: 0.6937 - loss: 0.8935
Epoch 3/31
18/18 - 1s - 30ms/step - accuracy: 0.7231 - loss: 0.8098
Epoch 4/31
18/18 - 1s - 31ms/step - accuracy: 0.7455 - loss: 0.7494
Epoch 5/31
18/18 - 1s - 32ms/step - accuracy: 0.7600 - loss: 0.7127
Epoch 6/31
18/18 - 1s - 32ms/step - accuracy: 0.7643 - loss: 0.6892
Epoch 7/31
18/18 - 1s - 32ms/step - accuracy: 0.7767 - loss: 0.6487
Epoch 8/31
18/18 - 1s - 32ms/step - accuracy: 0.7786 - loss: 0.6446
Epoch 9/31
18/18 - 1s - 32ms/step - accuracy: 0.7847 - loss: 0.6222
Epoch 10/31
18/18 - 1s - 32ms/step - accuracy: 0.7914 - loss: 0.5982
Epoch 11/31
18/18 - 1s - 32ms/step - accuracy: 0.7913 - loss: 0.5910
Epoch 12/31
18/18 - 1s - 32ms/step - accuracy: 0.7985 - loss: 0.5741
Epoch 13/31
18/18 - 1s - 32ms/step - accuracy: 0.7945 - loss: 0.5711
Epoch 14/31
18/18 - 1s - 31ms/step - accuracy: 0.8005 - loss: 0.5594
Epoch 15/31
18/18 - 1s - 30ms/step - accuracy: 0.8083 - loss: 0.5327
Epoch 16/31
18/18 - 1s - 30ms/step - accuracy: 0.8094 - loss: 0.5267
Epoch 17/31
18/18 - 1s - 30ms/step - accuracy: 0.8128 - loss: 0.5181
Epoch 18/31
18/18 - 1s - 30ms/step - accuracy: 0.7979 - loss: 0.5563
Epoch 19/31
18/18 - 1s - 32ms/step - accuracy: 0.8114 - loss: 0.5251
Epoch 20/31
18/18 - 1s - 31ms/step - accuracy: 0.8290 - loss: 0.4774
Epoch 21/31
18/18 - 1s - 30ms/step - accuracy: 0.8380 - loss: 0.4531
Epoch 22/31
18/18 - 1s - 29ms/step - accuracy: 0.8286 - loss: 0.4780
Epoch 23/31
18/18 - 1s - 30ms/step - accuracy: 0.8352 - loss: 0.4576
Epoch 24/31
18/18 - 1s - 31ms/step - accuracy: 0.8460 - loss: 0.4367
Epoch 25/31
18/18 - 1s - 31ms/step - accuracy: 0.8301 - loss: 0.4637
Epoch 26/31
18/18 - 1s - 32ms/step - accuracy: 0.8464 - loss: 0.4242
Epoch 27/31
18/18 - 1s - 32ms/step - accuracy: 0.8575 - loss: 0.3983
Epoch 28/31
18/18 - 1s - 31ms/step - accuracy: 0.8545 - loss: 0.3930
Epoch 29/31
18/18 - 1s - 33ms/step - accuracy: 0.8574 - loss: 0.4017
Epoch 30/31
18/18 - 1s - 32ms/step - accuracy: 0.8534 - loss: 0.4009
Epoch 31/31
18/18 - 1s - 32ms/step - accuracy: 0.8634 - loss: 0.3799
5/5 - 0s - 35ms/step
Epoch 1/31

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 2s - 101ms/step - accuracy: 0.6214 - loss: 1.2762
Epoch 2/31
18/18 - 1s - 29ms/step - accuracy: 0.6794 - loss: 0.9623
Epoch 3/31
18/18 - 1s - 31ms/step - accuracy: 0.7186 - loss: 0.8582
Epoch 4/31
18/18 - 1s - 29ms/step - accuracy: 0.7359 - loss: 0.7948
Epoch 5/31
18/18 - 1s - 30ms/step - accuracy: 0.7364 - loss: 0.7766
Epoch 6/31
18/18 - 1s - 30ms/step - accuracy: 0.7579 - loss: 0.7146
Epoch 7/31
18/18 - 1s - 30ms/step - accuracy: 0.7663 - loss: 0.6861
Epoch 8/31
18/18 - 1s - 30ms/step - accuracy: 0.7744 - loss: 0.6670
Epoch 9/31
18/18 - 1s - 30ms/step - accuracy: 0.7807 - loss: 0.6375
Epoch 10/31
18/18 - 1s - 30ms/step - accuracy: 0.7870 - loss: 0.6132
Epoch 11/31
18/18 - 1s - 30ms/step - accuracy: 0.7921 - loss: 0.6021
Epoch 12/31
18/18 - 1s - 30ms/step - accuracy: 0.7908 - loss: 0.5960
Epoch 13/31
18/18 - 1s - 29ms/step - accuracy: 0.7834 - loss: 0.6048
Epoch 14/31
18/18 - 1s - 30ms/step - accuracy: 0.7988 - loss: 0.5714
Epoch 15/31
18/18 - 1s - 30ms/step - accuracy: 0.8050 - loss: 0.5507
Epoch 16/31
18/18 - 1s - 30ms/step - accuracy: 0.8096 - loss: 0.5373
Epoch 17/31
18/18 - 1s - 29ms/step - accuracy: 0.7990 - loss: 0.5499
Epoch 18/31
18/18 - 1s - 31ms/step - accuracy: 0.8026 - loss: 0.5458
Epoch 19/31
18/18 - 1s - 32ms/step - accuracy: 0.8130 - loss: 0.5224
Epoch 20/31
18/18 - 1s - 32ms/step - accuracy: 0.8131 - loss: 0.5149
Epoch 21/31
18/18 - 1s - 32ms/step - accuracy: 0.8283 - loss: 0.4784
Epoch 22/31
18/18 - 1s - 32ms/step - accuracy: 0.8300 - loss: 0.4725
Epoch 23/31
18/18 - 1s - 32ms/step - accuracy: 0.8306 - loss: 0.4666
Epoch 24/31
18/18 - 1s - 32ms/step - accuracy: 0.8335 - loss: 0.4642
Epoch 25/31
18/18 - 1s - 32ms/step - accuracy: 0.8364 - loss: 0.4521
Epoch 26/31
18/18 - 1s - 32ms/step - accuracy: 0.8449 - loss: 0.4259
Epoch 27/31
18/18 - 1s - 32ms/step - accuracy: 0.8459 - loss: 0.4229
Epoch 28/31
18/18 - 1s - 32ms/step - accuracy: 0.8448 - loss: 0.4246
Epoch 29/31
18/18 - 1s - 30ms/step - accuracy: 0.8476 - loss: 0.4216
Epoch 30/31
18/18 - 1s - 30ms/step - accuracy: 0.8540 - loss: 0.4004
Epoch 31/31
18/18 - 1s - 30ms/step - accuracy: 0.8574 - loss: 0.3897
5/5 - 0s - 39ms/step
Epoch 1/31

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 2s - 99ms/step - accuracy: 0.5614 - loss: 1.5264
Epoch 2/31
18/18 - 1s - 31ms/step - accuracy: 0.6845 - loss: 0.9352
Epoch 3/31
18/18 - 1s - 30ms/step - accuracy: 0.7075 - loss: 0.8554
Epoch 4/31
18/18 - 1s - 30ms/step - accuracy: 0.7179 - loss: 0.8089
Epoch 5/31
18/18 - 1s - 30ms/step - accuracy: 0.7372 - loss: 0.7649
Epoch 6/31
18/18 - 1s - 30ms/step - accuracy: 0.7511 - loss: 0.7233
Epoch 7/31
18/18 - 1s - 30ms/step - accuracy: 0.7540 - loss: 0.7061
Epoch 8/31
18/18 - 1s - 30ms/step - accuracy: 0.7537 - loss: 0.7009
Epoch 9/31
18/18 - 1s - 30ms/step - accuracy: 0.7759 - loss: 0.6496
Epoch 10/31
18/18 - 1s - 30ms/step - accuracy: 0.7794 - loss: 0.6345
Epoch 11/31
18/18 - 1s - 30ms/step - accuracy: 0.7854 - loss: 0.6166
Epoch 12/31
18/18 - 1s - 30ms/step - accuracy: 0.7882 - loss: 0.5992
Epoch 13/31
18/18 - 1s - 31ms/step - accuracy: 0.7890 - loss: 0.5915
Epoch 14/31
18/18 - 1s - 32ms/step - accuracy: 0.8004 - loss: 0.5660
Epoch 15/31
18/18 - 1s - 32ms/step - accuracy: 0.7935 - loss: 0.5759
Epoch 16/31
18/18 - 1s - 31ms/step - accuracy: 0.7992 - loss: 0.5573
Epoch 17/31
18/18 - 1s - 32ms/step - accuracy: 0.8007 - loss: 0.5484
Epoch 18/31
18/18 - 1s - 32ms/step - accuracy: 0.8114 - loss: 0.5263
Epoch 19/31
18/18 - 1s - 32ms/step - accuracy: 0.8108 - loss: 0.5221
Epoch 20/31
18/18 - 1s - 32ms/step - accuracy: 0.8166 - loss: 0.5088
Epoch 21/31
18/18 - 1s - 32ms/step - accuracy: 0.8120 - loss: 0.5146
Epoch 22/31
18/18 - 1s - 32ms/step - accuracy: 0.8237 - loss: 0.4919
Epoch 23/31
18/18 - 1s - 32ms/step - accuracy: 0.8222 - loss: 0.4958
Epoch 24/31
18/18 - 1s - 30ms/step - accuracy: 0.8028 - loss: 0.5362
Epoch 25/31
18/18 - 1s - 30ms/step - accuracy: 0.8182 - loss: 0.4958
Epoch 26/31
18/18 - 1s - 30ms/step - accuracy: 0.8362 - loss: 0.4569
Epoch 27/31
18/18 - 1s - 30ms/step - accuracy: 0.8350 - loss: 0.4531
Epoch 28/31
18/18 - 1s - 30ms/step - accuracy: 0.8354 - loss: 0.4537
Epoch 29/31
18/18 - 1s - 30ms/step - accuracy: 0.8392 - loss: 0.4476
Epoch 30/31
18/18 - 1s - 30ms/step - accuracy: 0.8461 - loss: 0.4280
Epoch 31/31
18/18 - 1s - 30ms/step - accuracy: 0.8434 - loss: 0.4271
5/5 - 0s - 40ms/step
Epoch 1/31

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 2s - 100ms/step - accuracy: 0.6104 - loss: 1.2793
Epoch 2/31
18/18 - 1s - 29ms/step - accuracy: 0.6959 - loss: 0.9165
Epoch 3/31
18/18 - 1s - 29ms/step - accuracy: 0.7285 - loss: 0.8205
Epoch 4/31
18/18 - 1s - 29ms/step - accuracy: 0.7447 - loss: 0.7650
Epoch 5/31
18/18 - 1s - 30ms/step - accuracy: 0.7553 - loss: 0.7292
Epoch 6/31
18/18 - 1s - 30ms/step - accuracy: 0.7646 - loss: 0.6996
Epoch 7/31
18/18 - 1s - 30ms/step - accuracy: 0.7672 - loss: 0.6860
Epoch 8/31
18/18 - 1s - 31ms/step - accuracy: 0.7747 - loss: 0.6598
Epoch 9/31
18/18 - 1s - 32ms/step - accuracy: 0.7799 - loss: 0.6373
Epoch 10/31
18/18 - 1s - 31ms/step - accuracy: 0.7879 - loss: 0.6105
Epoch 11/31
18/18 - 1s - 32ms/step - accuracy: 0.7851 - loss: 0.6124
Epoch 12/31
18/18 - 1s - 32ms/step - accuracy: 0.7909 - loss: 0.5948
Epoch 13/31
18/18 - 1s - 31ms/step - accuracy: 0.7937 - loss: 0.5825
Epoch 14/31
18/18 - 1s - 32ms/step - accuracy: 0.8005 - loss: 0.5666
Epoch 15/31
18/18 - 1s - 31ms/step - accuracy: 0.7961 - loss: 0.5651
Epoch 16/31
18/18 - 1s - 32ms/step - accuracy: 0.8028 - loss: 0.5505
Epoch 17/31
18/18 - 1s - 31ms/step - accuracy: 0.8126 - loss: 0.5327
Epoch 18/31
18/18 - 1s - 31ms/step - accuracy: 0.8135 - loss: 0.5252
Epoch 19/31
18/18 - 1s - 32ms/step - accuracy: 0.8204 - loss: 0.5040
Epoch 20/31
18/18 - 1s - 30ms/step - accuracy: 0.8243 - loss: 0.4955
Epoch 21/31
18/18 - 1s - 30ms/step - accuracy: 0.8285 - loss: 0.4905
Epoch 22/31
18/18 - 1s - 33ms/step - accuracy: 0.8136 - loss: 0.5082
Epoch 23/31
18/18 - 1s - 31ms/step - accuracy: 0.8236 - loss: 0.4887
Epoch 24/31
18/18 - 1s - 31ms/step - accuracy: 0.8320 - loss: 0.4735
Epoch 25/31
18/18 - 1s - 31ms/step - accuracy: 0.8373 - loss: 0.4524
Epoch 26/31
18/18 - 1s - 31ms/step - accuracy: 0.8373 - loss: 0.4468
Epoch 27/31
18/18 - 1s - 31ms/step - accuracy: 0.8320 - loss: 0.4638
Epoch 28/31
18/18 - 1s - 31ms/step - accuracy: 0.8428 - loss: 0.4317
Epoch 29/31
18/18 - 1s - 31ms/step - accuracy: 0.8455 - loss: 0.4259
Epoch 30/31
18/18 - 1s - 30ms/step - accuracy: 0.8481 - loss: 0.4172
Epoch 31/31
18/18 - 1s - 30ms/step - accuracy: 0.8536 - loss: 0.4044
5/5 - 0s - 39ms/step
Epoch 1/31

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 2s - 100ms/step - accuracy: 0.5690 - loss: 1.3742
Epoch 2/31
18/18 - 1s - 31ms/step - accuracy: 0.6765 - loss: 0.9484
Epoch 3/31
18/18 - 1s - 32ms/step - accuracy: 0.7001 - loss: 0.8784
Epoch 4/31
18/18 - 1s - 32ms/step - accuracy: 0.7280 - loss: 0.8067
Epoch 5/31
18/18 - 1s - 33ms/step - accuracy: 0.7336 - loss: 0.7798
Epoch 6/31
18/18 - 1s - 34ms/step - accuracy: 0.7512 - loss: 0.7292
Epoch 7/31
18/18 - 1s - 34ms/step - accuracy: 0.7636 - loss: 0.6989
Epoch 8/31
18/18 - 1s - 32ms/step - accuracy: 0.7659 - loss: 0.6769
Epoch 9/31
18/18 - 1s - 31ms/step - accuracy: 0.7733 - loss: 0.6601
Epoch 10/31
18/18 - 1s - 31ms/step - accuracy: 0.7813 - loss: 0.6281
Epoch 11/31
18/18 - 1s - 32ms/step - accuracy: 0.7841 - loss: 0.6177
Epoch 12/31
18/18 - 1s - 32ms/step - accuracy: 0.7886 - loss: 0.6111
Epoch 13/31
18/18 - 1s - 32ms/step - accuracy: 0.7960 - loss: 0.5819
Epoch 14/31
18/18 - 1s - 33ms/step - accuracy: 0.8000 - loss: 0.5710
Epoch 15/31
18/18 - 1s - 32ms/step - accuracy: 0.8033 - loss: 0.5689
Epoch 16/31
18/18 - 1s - 33ms/step - accuracy: 0.8055 - loss: 0.5468
Epoch 17/31
18/18 - 1s - 32ms/step - accuracy: 0.8117 - loss: 0.5328
Epoch 18/31
18/18 - 1s - 32ms/step - accuracy: 0.8070 - loss: 0.5305
Epoch 19/31
18/18 - 1s - 31ms/step - accuracy: 0.8182 - loss: 0.5136
Epoch 20/31
18/18 - 1s - 32ms/step - accuracy: 0.8148 - loss: 0.5107
Epoch 21/31
18/18 - 1s - 32ms/step - accuracy: 0.8180 - loss: 0.5006
Epoch 22/31
18/18 - 1s - 33ms/step - accuracy: 0.8113 - loss: 0.5142
Epoch 23/31
18/18 - 1s - 33ms/step - accuracy: 0.8329 - loss: 0.4727
Epoch 24/31
18/18 - 1s - 32ms/step - accuracy: 0.8325 - loss: 0.4634
Epoch 25/31
18/18 - 1s - 30ms/step - accuracy: 0.8184 - loss: 0.4871
Epoch 26/31
18/18 - 1s - 30ms/step - accuracy: 0.8324 - loss: 0.4631
Epoch 27/31
18/18 - 1s - 32ms/step - accuracy: 0.8317 - loss: 0.4683
Epoch 28/31
18/18 - 1s - 44ms/step - accuracy: 0.8384 - loss: 0.4483
Epoch 29/31
18/18 - 1s - 32ms/step - accuracy: 0.8415 - loss: 0.4355
Epoch 30/31
18/18 - 1s - 32ms/step - accuracy: 0.8436 - loss: 0.4250
Epoch 31/31
18/18 - 1s - 32ms/step - accuracy: 0.8314 - loss: 0.4491
5/5 - 0s - 54ms/step
| 14        | 0.8288    | 6.049     | 809.3     | 0.2376    | 0.2185    | 31.03     | 2.265     | 2.267     | 2.072     | 0.09939   | 85.18     | 0.3208    | 1.306     |
Epoch 1/35

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 3s - 142ms/step - accuracy: 0.4881 - loss: 1.6687
Epoch 2/35
21/21 - 0s - 15ms/step - accuracy: 0.6432 - loss: 1.0195
Epoch 3/35
21/21 - 0s - 17ms/step - accuracy: 0.6774 - loss: 0.9150
Epoch 4/35
21/21 - 0s - 14ms/step - accuracy: 0.7082 - loss: 0.8452
Epoch 5/35
21/21 - 0s - 14ms/step - accuracy: 0.7257 - loss: 0.7952
Epoch 6/35
21/21 - 0s - 13ms/step - accuracy: 0.7374 - loss: 0.7567
Epoch 7/35
21/21 - 0s - 16ms/step - accuracy: 0.7527 - loss: 0.7226
Epoch 8/35
21/21 - 0s - 17ms/step - accuracy: 0.7588 - loss: 0.6883
Epoch 9/35
21/21 - 0s - 16ms/step - accuracy: 0.7723 - loss: 0.6516
Epoch 10/35
21/21 - 0s - 17ms/step - accuracy: 0.7820 - loss: 0.6222
Epoch 11/35
21/21 - 0s - 20ms/step - accuracy: 0.7900 - loss: 0.5943
Epoch 12/35
21/21 - 0s - 19ms/step - accuracy: 0.7980 - loss: 0.5671
Epoch 13/35
21/21 - 0s - 15ms/step - accuracy: 0.8099 - loss: 0.5364
Epoch 14/35
21/21 - 0s - 15ms/step - accuracy: 0.8180 - loss: 0.5099
Epoch 15/35
21/21 - 0s - 14ms/step - accuracy: 0.8246 - loss: 0.4928
Epoch 16/35
21/21 - 0s - 14ms/step - accuracy: 0.8309 - loss: 0.4715
Epoch 17/35
21/21 - 0s - 13ms/step - accuracy: 0.8396 - loss: 0.4482
Epoch 18/35
21/21 - 0s - 12ms/step - accuracy: 0.8475 - loss: 0.4259
Epoch 19/35
21/21 - 0s - 14ms/step - accuracy: 0.8571 - loss: 0.4081
Epoch 20/35
21/21 - 0s - 15ms/step - accuracy: 0.8632 - loss: 0.3897
Epoch 21/35
21/21 - 0s - 13ms/step - accuracy: 0.8658 - loss: 0.3763
Epoch 22/35
21/21 - 0s - 13ms/step - accuracy: 0.8706 - loss: 0.3627
Epoch 23/35
21/21 - 0s - 15ms/step - accuracy: 0.8697 - loss: 0.3646
Epoch 24/35
21/21 - 0s - 14ms/step - accuracy: 0.8802 - loss: 0.3454
Epoch 25/35
21/21 - 0s - 14ms/step - accuracy: 0.8828 - loss: 0.3307
Epoch 26/35
21/21 - 0s - 13ms/step - accuracy: 0.8883 - loss: 0.3234
Epoch 27/35
21/21 - 0s - 14ms/step - accuracy: 0.8917 - loss: 0.3085
Epoch 28/35
21/21 - 0s - 16ms/step - accuracy: 0.8937 - loss: 0.3046
Epoch 29/35
21/21 - 0s - 14ms/step - accuracy: 0.8983 - loss: 0.2961
Epoch 30/35
21/21 - 0s - 16ms/step - accuracy: 0.9090 - loss: 0.2728
Epoch 31/35
21/21 - 0s - 18ms/step - accuracy: 0.9036 - loss: 0.2728
Epoch 32/35
21/21 - 0s - 15ms/step - accuracy: 0.9041 - loss: 0.2776
Epoch 33/35
21/21 - 0s - 15ms/step - accuracy: 0.9081 - loss: 0.2694
Epoch 34/35
21/21 - 0s - 13ms/step - accuracy: 0.9117 - loss: 0.2587
Epoch 35/35
21/21 - 0s - 14ms/step - accuracy: 0.9141 - loss: 0.2537
6/6 - 0s - 31ms/step

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/35
21/21 - 2s - 117ms/step - accuracy: 0.5469 - loss: 1.4979
Epoch 2/35
21/21 - 0s - 14ms/step - accuracy: 0.6510 - loss: 1.0038
Epoch 3/35
21/21 - 0s - 14ms/step - accuracy: 0.6866 - loss: 0.9010
Epoch 4/35
21/21 - 0s - 14ms/step - accuracy: 0.7105 - loss: 0.8312
Epoch 5/35
21/21 - 0s - 13ms/step - accuracy: 0.7314 - loss: 0.7791
Epoch 6/35
21/21 - 0s - 14ms/step - accuracy: 0.7449 - loss: 0.7403
Epoch 7/35
21/21 - 0s - 14ms/step - accuracy: 0.7537 - loss: 0.7077
Epoch 8/35
21/21 - 0s - 14ms/step - accuracy: 0.7634 - loss: 0.6771
Epoch 9/35
21/21 - 0s - 13ms/step - accuracy: 0.7730 - loss: 0.6488
Epoch 10/35
21/21 - 0s - 14ms/step - accuracy: 0.7834 - loss: 0.6190
Epoch 11/35
21/21 - 0s - 14ms/step - accuracy: 0.7926 - loss: 0.5897
Epoch 12/35
21/21 - 0s - 14ms/step - accuracy: 0.8007 - loss: 0.5592
Epoch 13/35
21/21 - 0s - 13ms/step - accuracy: 0.8142 - loss: 0.5258
Epoch 14/35
21/21 - 0s - 13ms/step - accuracy: 0.8194 - loss: 0.4998
Epoch 15/35
21/21 - 0s - 11ms/step - accuracy: 0.8300 - loss: 0.4709
Epoch 16/35
21/21 - 0s - 13ms/step - accuracy: 0.8417 - loss: 0.4418
Epoch 17/35
21/21 - 0s - 14ms/step - accuracy: 0.8489 - loss: 0.4200
Epoch 18/35
21/21 - 0s - 15ms/step - accuracy: 0.8553 - loss: 0.4059
Epoch 19/35
21/21 - 0s - 15ms/step - accuracy: 0.8627 - loss: 0.3879
Epoch 20/35
21/21 - 0s - 13ms/step - accuracy: 0.8682 - loss: 0.3717
Epoch 21/35
21/21 - 0s - 15ms/step - accuracy: 0.8688 - loss: 0.3649
Epoch 22/35
21/21 - 0s - 14ms/step - accuracy: 0.8761 - loss: 0.3521
Epoch 23/35
21/21 - 0s - 13ms/step - accuracy: 0.8812 - loss: 0.3373
Epoch 24/35
21/21 - 0s - 16ms/step - accuracy: 0.8863 - loss: 0.3240
Epoch 25/35
21/21 - 0s - 15ms/step - accuracy: 0.8887 - loss: 0.3138
Epoch 26/35
21/21 - 0s - 13ms/step - accuracy: 0.8957 - loss: 0.3018
Epoch 27/35
21/21 - 0s - 13ms/step - accuracy: 0.8969 - loss: 0.2993
Epoch 28/35
21/21 - 0s - 14ms/step - accuracy: 0.8998 - loss: 0.2875
Epoch 29/35
21/21 - 0s - 16ms/step - accuracy: 0.9028 - loss: 0.2819
Epoch 30/35
21/21 - 0s - 16ms/step - accuracy: 0.9042 - loss: 0.2710
Epoch 31/35
21/21 - 0s - 14ms/step - accuracy: 0.9075 - loss: 0.2683
Epoch 32/35
21/21 - 0s - 17ms/step - accuracy: 0.9110 - loss: 0.2545
Epoch 33/35
21/21 - 0s - 14ms/step - accuracy: 0.9126 - loss: 0.2541
Epoch 34/35
21/21 - 0s - 14ms/step - accuracy: 0.9186 - loss: 0.2416
Epoch 35/35
21/21 - 0s - 13ms/step - accuracy: 0.9191 - loss: 0.2345
6/6 - 0s - 28ms/step
Epoch 1/35

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 2s - 93ms/step - accuracy: 0.5326 - loss: 1.6055
Epoch 2/35
21/21 - 0s - 18ms/step - accuracy: 0.6586 - loss: 1.0309
Epoch 3/35
21/21 - 0s - 13ms/step - accuracy: 0.6796 - loss: 0.9299
Epoch 4/35
21/21 - 0s - 11ms/step - accuracy: 0.7038 - loss: 0.8610
Epoch 5/35
21/21 - 0s - 12ms/step - accuracy: 0.7276 - loss: 0.8080
Epoch 6/35
21/21 - 0s - 12ms/step - accuracy: 0.7445 - loss: 0.7659
Epoch 7/35
21/21 - 0s - 14ms/step - accuracy: 0.7538 - loss: 0.7288
Epoch 8/35
21/21 - 0s - 23ms/step - accuracy: 0.7595 - loss: 0.7011
Epoch 9/35
21/21 - 0s - 16ms/step - accuracy: 0.7714 - loss: 0.6652
Epoch 10/35
21/21 - 0s - 14ms/step - accuracy: 0.7809 - loss: 0.6344
Epoch 11/35
21/21 - 0s - 15ms/step - accuracy: 0.7931 - loss: 0.5954
Epoch 12/35
21/21 - 0s - 13ms/step - accuracy: 0.8039 - loss: 0.5637
Epoch 13/35
21/21 - 0s - 15ms/step - accuracy: 0.8145 - loss: 0.5326
Epoch 14/35
21/21 - 0s - 15ms/step - accuracy: 0.8235 - loss: 0.5025
Epoch 15/35
21/21 - 0s - 14ms/step - accuracy: 0.8307 - loss: 0.4765
Epoch 16/35
21/21 - 0s - 15ms/step - accuracy: 0.8397 - loss: 0.4475
Epoch 17/35
21/21 - 0s - 13ms/step - accuracy: 0.8473 - loss: 0.4308
Epoch 18/35
21/21 - 0s - 14ms/step - accuracy: 0.8485 - loss: 0.4158
Epoch 19/35
21/21 - 0s - 14ms/step - accuracy: 0.8590 - loss: 0.3948
Epoch 20/35
21/21 - 0s - 14ms/step - accuracy: 0.8668 - loss: 0.3779
Epoch 21/35
21/21 - 0s - 16ms/step - accuracy: 0.8739 - loss: 0.3601
Epoch 22/35
21/21 - 0s - 15ms/step - accuracy: 0.8768 - loss: 0.3490
Epoch 23/35
21/21 - 0s - 17ms/step - accuracy: 0.8818 - loss: 0.3393
Epoch 24/35
21/21 - 0s - 18ms/step - accuracy: 0.8882 - loss: 0.3211
Epoch 25/35
21/21 - 0s - 15ms/step - accuracy: 0.8922 - loss: 0.3149
Epoch 26/35
21/21 - 0s - 19ms/step - accuracy: 0.8923 - loss: 0.3101
Epoch 27/35
21/21 - 0s - 19ms/step - accuracy: 0.8927 - loss: 0.3026
Epoch 28/35
21/21 - 0s - 20ms/step - accuracy: 0.9002 - loss: 0.2883
Epoch 29/35
21/21 - 0s - 15ms/step - accuracy: 0.9017 - loss: 0.2820
Epoch 30/35
21/21 - 0s - 17ms/step - accuracy: 0.9031 - loss: 0.2805
Epoch 31/35
21/21 - 0s - 16ms/step - accuracy: 0.9092 - loss: 0.2653
Epoch 32/35
21/21 - 0s - 13ms/step - accuracy: 0.9114 - loss: 0.2591
Epoch 33/35
21/21 - 0s - 14ms/step - accuracy: 0.9157 - loss: 0.2477
Epoch 34/35
21/21 - 0s - 13ms/step - accuracy: 0.9168 - loss: 0.2420
Epoch 35/35
21/21 - 0s - 12ms/step - accuracy: 0.9174 - loss: 0.2434
6/6 - 0s - 30ms/step
Epoch 1/35

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 2s - 94ms/step - accuracy: 0.5666 - loss: 1.4843
Epoch 2/35
21/21 - 0s - 12ms/step - accuracy: 0.6810 - loss: 0.9575
Epoch 3/35
21/21 - 0s - 12ms/step - accuracy: 0.7043 - loss: 0.8662
Epoch 4/35
21/21 - 0s - 14ms/step - accuracy: 0.7235 - loss: 0.8022
Epoch 5/35
21/21 - 0s - 14ms/step - accuracy: 0.7378 - loss: 0.7533
Epoch 6/35
21/21 - 0s - 15ms/step - accuracy: 0.7460 - loss: 0.7208
Epoch 7/35
21/21 - 0s - 13ms/step - accuracy: 0.7568 - loss: 0.6884
Epoch 8/35
21/21 - 0s - 14ms/step - accuracy: 0.7671 - loss: 0.6571
Epoch 9/35
21/21 - 0s - 16ms/step - accuracy: 0.7797 - loss: 0.6228
Epoch 10/35
21/21 - 0s - 15ms/step - accuracy: 0.7893 - loss: 0.5912
Epoch 11/35
21/21 - 0s - 17ms/step - accuracy: 0.8002 - loss: 0.5594
Epoch 12/35
21/21 - 0s - 14ms/step - accuracy: 0.8095 - loss: 0.5197
Epoch 13/35
21/21 - 0s - 13ms/step - accuracy: 0.8253 - loss: 0.4801
Epoch 14/35
21/21 - 0s - 18ms/step - accuracy: 0.8418 - loss: 0.4434
Epoch 15/35
21/21 - 0s - 21ms/step - accuracy: 0.8528 - loss: 0.4091
Epoch 16/35
21/21 - 0s - 22ms/step - accuracy: 0.8633 - loss: 0.3867
Epoch 17/35
21/21 - 1s - 28ms/step - accuracy: 0.8723 - loss: 0.3632
Epoch 18/35
21/21 - 0s - 19ms/step - accuracy: 0.8817 - loss: 0.3372
Epoch 19/35
21/21 - 1s - 32ms/step - accuracy: 0.8882 - loss: 0.3184
Epoch 20/35
21/21 - 0s - 17ms/step - accuracy: 0.8914 - loss: 0.3081
Epoch 21/35
21/21 - 0s - 16ms/step - accuracy: 0.8987 - loss: 0.2885
Epoch 22/35
21/21 - 0s - 15ms/step - accuracy: 0.9037 - loss: 0.2718
Epoch 23/35
21/21 - 0s - 11ms/step - accuracy: 0.9127 - loss: 0.2548
Epoch 24/35
21/21 - 0s - 10ms/step - accuracy: 0.9159 - loss: 0.2435
Epoch 25/35
21/21 - 0s - 10ms/step - accuracy: 0.9141 - loss: 0.2486
Epoch 26/35
21/21 - 0s - 10ms/step - accuracy: 0.9151 - loss: 0.2405
Epoch 27/35
21/21 - 0s - 10ms/step - accuracy: 0.9197 - loss: 0.2265
Epoch 28/35
21/21 - 0s - 10ms/step - accuracy: 0.9233 - loss: 0.2246
Epoch 29/35
21/21 - 0s - 11ms/step - accuracy: 0.9301 - loss: 0.2067
Epoch 30/35
21/21 - 0s - 11ms/step - accuracy: 0.9291 - loss: 0.2048
Epoch 31/35
21/21 - 0s - 13ms/step - accuracy: 0.9269 - loss: 0.2101
Epoch 32/35
21/21 - 0s - 12ms/step - accuracy: 0.9349 - loss: 0.1890
Epoch 33/35
21/21 - 0s - 11ms/step - accuracy: 0.9362 - loss: 0.1833
Epoch 34/35
21/21 - 0s - 11ms/step - accuracy: 0.9402 - loss: 0.1725
Epoch 35/35
21/21 - 0s - 10ms/step - accuracy: 0.9406 - loss: 0.1726
6/6 - 0s - 24ms/step
Epoch 1/35

C:\Users\cschw\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 3s - 121ms/step - accuracy: 0.5894 - loss: 1.5448
Epoch 2/35
21/21 - 0s - 15ms/step - accuracy: 0.6633 - loss: 1.0024
Epoch 3/35
21/21 - 0s - 16ms/step - accuracy: 0.6744 - loss: 0.9391
Epoch 4/35
21/21 - 0s - 14ms/step - accuracy: 0.6851 - loss: 0.8903
Epoch 5/35
21/21 - 0s - 16ms/step - accuracy: 0.7073 - loss: 0.8320
Epoch 6/35
21/21 - 0s - 16ms/step - accuracy: 0.7240 - loss: 0.7806
Epoch 7/35
21/21 - 0s - 14ms/step - accuracy: 0.7354 - loss: 0.7456
Epoch 8/35
21/21 - 0s - 16ms/step - accuracy: 0.7449 - loss: 0.7180
Epoch 9/35
21/21 - 0s - 13ms/step - accuracy: 0.7497 - loss: 0.6942
Epoch 10/35
21/21 - 0s - 14ms/step - accuracy: 0.7604 - loss: 0.6653
Epoch 11/35
21/21 - 0s - 15ms/step - accuracy: 0.7670 - loss: 0.6420
Epoch 12/35
21/21 - 0s - 13ms/step - accuracy: 0.7788 - loss: 0.6065
Epoch 13/35
21/21 - 0s - 13ms/step - accuracy: 0.7859 - loss: 0.5799
Epoch 14/35
21/21 - 0s - 17ms/step - accuracy: 0.7998 - loss: 0.5480
Epoch 15/35
21/21 - 0s - 16ms/step - accuracy: 0.8107 - loss: 0.5201
Epoch 16/35
21/21 - 0s - 15ms/step - accuracy: 0.8168 - loss: 0.4967
Epoch 17/35
21/21 - 0s - 17ms/step - accuracy: 0.8279 - loss: 0.4716
Epoch 18/35
21/21 - 0s - 13ms/step - accuracy: 0.8352 - loss: 0.4520
Epoch 19/35
21/21 - 0s - 14ms/step - accuracy: 0.8375 - loss: 0.4404
Epoch 20/35
21/21 - 0s - 15ms/step - accuracy: 0.8505 - loss: 0.4136
Epoch 21/35
21/21 - 0s - 14ms/step - accuracy: 0.8537 - loss: 0.4000
Epoch 22/35
21/21 - 0s - 16ms/step - accuracy: 0.8593 - loss: 0.3866
Epoch 23/35
21/21 - 0s - 14ms/step - accuracy: 0.8651 - loss: 0.3733
Epoch 24/35
21/21 - 0s - 14ms/step - accuracy: 0.8658 - loss: 0.3692
Epoch 25/35
21/21 - 0s - 14ms/step - accuracy: 0.8728 - loss: 0.3588
Epoch 26/35
21/21 - 0s - 15ms/step - accuracy: 0.8824 - loss: 0.3367
Epoch 27/35
21/21 - 0s - 14ms/step - accuracy: 0.8866 - loss: 0.3231
Epoch 28/35
21/21 - 0s - 14ms/step - accuracy: 0.8878 - loss: 0.3185
Epoch 29/35
21/21 - 0s - 14ms/step - accuracy: 0.8930 - loss: 0.3027
Epoch 30/35
21/21 - 0s - 13ms/step - accuracy: 0.8949 - loss: 0.2970
Epoch 31/35
21/21 - 0s - 13ms/step - accuracy: 0.8978 - loss: 0.2911
Epoch 32/35
21/21 - 0s - 13ms/step - accuracy: 0.9016 - loss: 0.2850
Epoch 33/35
21/21 - 0s - 16ms/step - accuracy: 0.8995 - loss: 0.2842
Epoch 34/35
21/21 - 0s - 18ms/step - accuracy: 0.9045 - loss: 0.2700
Epoch 35/35
21/21 - 0s - 16ms/step - accuracy: 0.9098 - loss: 0.2569
6/6 - 0s - 32ms/step
| 15        | 0.8842    | 0.367     | 672.7     | 0.6776    | 0.004976  | 35.36     | 1.453     | 2.29      | 1.349     | 0.694     | 44.81     | 0.9367    | 0.9626    |

ValueError: Input y contains NaN.

In [53]:
optimum = nn_opt.max['params']
learning_rate = optimum['learning_rate']

activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu', 'elu', 'exponential', LeakyReLU, 'relu']
optimum['activation'] = activationL[round(optimum['activation'])]

optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])

optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl', 'Adam']
optimizerD = {
    'Adam': Adam(learning_rate=learning_rate),
    'SGD': SGD(learning_rate=learning_rate),
    'RMSprop': RMSprop(learning_rate=learning_rate),
    'Adadelta': Adadelta(learning_rate=learning_rate),
    'Adagrad': Adagrad(learning_rate=learning_rate),
    'Adamax': Adamax(learning_rate=learning_rate),
    'Nadam': Nadam(learning_rate=learning_rate),
    'Ftrl': Ftrl(learning_rate=learning_rate)
}
optimum['optimizer'] = optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'activation': 'softsign',
 'batch_size': 460,
 'dropout': 0.7296061783380641,
 'dropout_rate': 0.19126724140656393,
 'epochs': 47,
 'kernel': 1.9444298503238986,
 'layers1': 1,
 'layers2': 2,
 'learning_rate': 0.7631771981307285,
 'neurons': 61,
 'normalization': 0.770967179954561,
 'optimizer': <keras.src.optimizers.adadelta.Adadelta at 0x22fa4a25190>}

### Creating CNN Model

In [56]:
# Set the model with optimized hyperparameters

epochs = 47
batch_size = 460

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15

layers1 = 1
layers2 = 2
activation = 'softsign'
kernel = int(round(1.9444298503238986))  # Rounded kernel size for Conv1D
neurons = 61
normalization = 0.77096719954561
dropout =0.7296061783380641
dropout_rate =0.19126724140656393
optimizer = Adadelta(learning_rate=0.7631771981307285)  # Instantiate RMSprop with learning rate

model = Sequential()
model.add(Conv1D(neurons, kernel_size=kernel, activation=activation, input_shape=(timesteps, input_dim)))

if normalization > 0.5:
    model.add(BatchNormalization())

for i in range(layers1):
    model.add(Dense(neurons, activation=activation))

if dropout > 0.5:
    model.add(Dropout(dropout_rate))

for i in range(layers2):
    model.add(Dense(neurons, activation=activation))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softsign')) 

model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

C:\Users\cschw\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [59]:
model.summary()

Model: "sequential_75"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_75 (Conv1D)              │ (None, 14, 61)         │         1,159 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_30          │ (None, 14, 61)         │           244 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_380 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_45 (Dropout)            │ (None, 14, 61)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_381 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_382 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_75 (MaxPooling1D) │ (None, 7, 61)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_75 (Flatten)            │ (None, 427)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_383 (Dense)               │ (None, 15)             │         6,420 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,169 (74.88 KB)

 Trainable params: 19,047 (74.40 KB)

 Non-trainable params: 122 (488.00 B)

In [62]:
# Put the y_test set back into a one-hot configuration

y_train_one_hot = to_categorical(y_train, num_classes=15)

In [65]:
# Check shapes

print(f'X_train shape: {X_train.shape}')
print(f'y_train_one_hot shape: {y_train_one_hot.shape}')

X_train shape: (17212, 15, 9)
y_train_one_hot shape: (17212, 15)

In [68]:
# Compile the model with categorical_crossentropy

model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

### Running CNN Model Attempt #1

In [51]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [72]:
# Fit the model to the data

model.fit(X_train, y_train_one_hot, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/47
38/38 - 2s - 62ms/step - accuracy: 0.1750 - loss: 9.4933
Epoch 2/47
38/38 - 0s - 13ms/step - accuracy: 0.0813 - loss: 9.6944
Epoch 3/47
38/38 - 0s - 11ms/step - accuracy: 0.0531 - loss: 8.8211
Epoch 4/47
38/38 - 1s - 14ms/step - accuracy: 0.0250 - loss: 8.9244
Epoch 5/47
38/38 - 0s - 13ms/step - accuracy: 0.0220 - loss: 9.0323
Epoch 6/47
38/38 - 0s - 12ms/step - accuracy: 0.0214 - loss: 9.2146
Epoch 7/47
38/38 - 0s - 12ms/step - accuracy: 0.0242 - loss: 9.3896
Epoch 8/47
38/38 - 0s - 12ms/step - accuracy: 0.0167 - loss: 9.2597
Epoch 9/47
38/38 - 0s - 12ms/step - accuracy: 0.0171 - loss: 9.3680
Epoch 10/47
38/38 - 0s - 12ms/step - accuracy: 0.0174 - loss: 9.3880
Epoch 11/47
38/38 - 0s - 12ms/step - accuracy: 0.0158 - loss: 9.4860
Epoch 12/47
38/38 - 0s - 12ms/step - accuracy: 0.0146 - loss: 9.4566
Epoch 13/47
38/38 - 0s - 11ms/step - accuracy: 0.0147 - loss: 9.3031
Epoch 14/47
38/38 - 0s - 11ms/step - accuracy: 0.0139 - loss: 9.3875
Epoch 15/47
38/38 - 0s - 12ms/step - accuracy: 0.0148 - loss: 9.5391
Epoch 16/47
38/38 - 0s - 11ms/step - accuracy: 0.0153 - loss: 9.4170
Epoch 17/47
38/38 - 0s - 11ms/step - accuracy: 0.0127 - loss: 9.0547
Epoch 18/47
38/38 - 0s - 11ms/step - accuracy: 0.0150 - loss: 9.2494
Epoch 19/47
38/38 - 0s - 11ms/step - accuracy: 0.0150 - loss: 9.6816
Epoch 20/47
38/38 - 0s - 11ms/step - accuracy: 0.0148 - loss: 10.0809
Epoch 21/47
38/38 - 0s - 11ms/step - accuracy: 0.0130 - loss: 9.3642
Epoch 22/47
38/38 - 0s - 11ms/step - accuracy: 0.0120 - loss: 8.9896
Epoch 23/47
38/38 - 0s - 12ms/step - accuracy: 0.0098 - loss: 9.0372
Epoch 24/47
38/38 - 0s - 12ms/step - accuracy: 0.0101 - loss: 8.6703
Epoch 25/47
38/38 - 0s - 11ms/step - accuracy: 0.0115 - loss: 8.4595
Epoch 26/47
38/38 - 0s - 11ms/step - accuracy: 0.0125 - loss: 8.5962
Epoch 27/47
38/38 - 0s - 11ms/step - accuracy: 0.0115 - loss: 8.6559
Epoch 28/47
38/38 - 0s - 11ms/step - accuracy: 0.0120 - loss: 8.4623
Epoch 29/47
38/38 - 0s - 11ms/step - accuracy: 0.0112 - loss: 8.5946
Epoch 30/47
38/38 - 0s - 11ms/step - accuracy: 0.0102 - loss: 8.4240
Epoch 31/47
38/38 - 0s - 11ms/step - accuracy: 0.0148 - loss: 8.3400
Epoch 32/47
38/38 - 0s - 11ms/step - accuracy: 0.0234 - loss: 8.9075
Epoch 33/47
38/38 - 0s - 11ms/step - accuracy: 0.0205 - loss: 9.0770
Epoch 34/47
38/38 - 0s - 12ms/step - accuracy: 0.0189 - loss: 9.0292
Epoch 35/47
38/38 - 0s - 11ms/step - accuracy: 0.0144 - loss: 8.7999
Epoch 36/47
38/38 - 0s - 11ms/step - accuracy: 0.0183 - loss: 8.4851
Epoch 37/47
38/38 - 0s - 11ms/step - accuracy: 0.0141 - loss: 8.5863
Epoch 38/47
38/38 - 0s - 12ms/step - accuracy: 0.0147 - loss: 8.4189
Epoch 39/47
38/38 - 0s - 11ms/step - accuracy: 0.0145 - loss: 8.3411
Epoch 40/47
38/38 - 0s - 12ms/step - accuracy: 0.0141 - loss: 8.5280
Epoch 41/47
38/38 - 0s - 12ms/step - accuracy: 0.0138 - loss: 8.6366
Epoch 42/47
38/38 - 0s - 12ms/step - accuracy: 0.0134 - loss: 8.5995
Epoch 43/47
38/38 - 0s - 12ms/step - accuracy: 0.0132 - loss: 8.4335
Epoch 44/47
38/38 - 0s - 12ms/step - accuracy: 0.0141 - loss: 8.2163
Epoch 45/47
38/38 - 0s - 12ms/step - accuracy: 0.0138 - loss: 8.3898
Epoch 46/47
38/38 - 0s - 12ms/step - accuracy: 0.0146 - loss: 8.4699
Epoch 47/47
38/38 - 0s - 12ms/step - accuracy: 0.0138 - loss: 8.4878

In [75]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'}

In [82]:
def confusion_matrix(y_true, y_pred, stations):
    # Check if y_true and y_pred are one-hot encoded or already class indices
    if y_true.ndim == 1:
        y_true_labels = y_true
    else:
        y_true_labels = np.argmax(y_true, axis=1)
    
    if y_pred.ndim == 1:
        y_pred_labels = y_pred
    else:
        y_pred_labels = np.argmax(y_pred, axis=1)
        
    # Map numeric labels to activity names
    y_true_series = pd.Series([stations[y] for y in y_true_labels])
    y_pred_series = pd.Series([stations[y] for y in y_pred_labels])
    
    return pd.crosstab(y_true_series, y_pred_series, rownames=['True'], colnames=['Pred'])

In [85]:
y_pred = model.predict(X_test)

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [88]:
# Evaluate

print(confusion_matrix(y_test, y_pred, stations))

Pred        BASEL  BELGRADE  DEBILT  DUSSELDORF  HEATHROW  LJUBLJANA  \
True
BASEL           9        20    2238         293        11        984
BELGRADE        0         5     784          57         2        237
BUDAPEST        0         1     142          32         0         37
DEBILT          1         0      63           6         0         10
DUSSELDORF      0         0      18           5         0          4
HEATHROW        1         0      61           7         1         10
KASSEL          0         0      10           0         0          1
LJUBLJANA       0         0      52           2         0          7
MAASTRICHT      0         0       9           0         0          0
MADRID          3         0     302          71         1         78
MUNCHENB        0         0       7           0         0          1
OSLO            0         0       2           0         0          3
STOCKHOLM       0         0       2           0         0          2
VALENTIA        0         0       1           0         0          0

Pred        SONNBLICK  VALENTIA
True
BASEL              48        79
BELGRADE            0         7
BUDAPEST            0         2
DEBILT              0         2
DUSSELDORF          0         2
HEATHROW            0         2
KASSEL              0         0
LJUBLJANA           0         0
MAASTRICHT          0         0
MADRID              0         3
MUNCHENB            0         0
OSLO                0         0
STOCKHOLM           0         0
VALENTIA            0         0