# Machine Learning 2.2 Part 1

### Import Libraries & Data

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [4]:
# Set display options to show all columns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
# Set path
path = r"C:\Users\cschw\OneDrive\Desktop\Machine Learning"

In [6]:
# Load unscaled data
unscaled= pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-weather-prediction-dataset-processed.csv'))

In [7]:
# Check head
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,8,0.91,0.00,0,0.8,-0.3,1.6,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,3,2.6,0.73,1.0152,7.1,7.8,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,3.8,0.76,1.0169,1.54,0.44,10.0,7.8,12.2,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,8,0.93,0.08,0,1.6,0.9,2.2,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,3,2.6,0.73,1.0152,7.1,12.2,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,3.8,0.76,1.0169,1.54,0.71,9.5,7.0,12.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.94,0.15,0,0.7,0.4,1.7,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,3,2.6,0.73,1.0152,7.1,10.2,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,3.8,0.76,1.0169,1.54,0.10,10.3,9.0,11.6,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,7,0.91,0.00,0,-0.1,-0.9,2.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,3,2.6,0.73,1.0152,7.1,10.8,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,3.8,0.76,1.0169,1.54,0.10,11.2,9.9,12.6,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,7,0.94,0.17,0,0.4,-1.7,1.5,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,3,2.6,0.73,1.0152,7.1,9.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3.8,0.76,1.0169,1.54,0.00,11.4,10.7,12.0,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [8]:
# Load pleasant weather predictions
prediction= pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

In [9]:
# Check head
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
# check shape of unscaled
unscaled.shape

(22950, 170)

In [11]:
# check shape of prediction
prediction.shape

(22950, 16)

### Data Wrangling

In [13]:
# Remove weather stations not included in "pleasant weather" answers
unscaled = unscaled.drop(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max',
                        'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean',
                        'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'], axis=1)

In [14]:
# check shape to confirm
unscaled.shape

(22950, 149)

In [15]:
# check for null values
unscaled.isnull().sum()

DATE                           0
MONTH                          0
BASEL_cloud_cover              0
BASEL_wind_speed               0
BASEL_humidity                 0
BASEL_pressure                 0
BASEL_global_radiation         0
BASEL_precipitation            0
BASEL_snow_depth               0
BASEL_sunshine                 0
BASEL_temp_mean                0
BASEL_temp_min                 0
BASEL_temp_max                 0
BELGRADE_cloud_cover           0
BELGRADE_humidity              0
BELGRADE_pressure              0
BELGRADE_global_radiation      0
BELGRADE_precipitation         0
BELGRADE_sunshine              0
BELGRADE_temp_mean             0
BELGRADE_temp_min              0
BELGRADE_temp_max              0
BUDAPEST_cloud_cover           0
BUDAPEST_humidity              0
BUDAPEST_pressure              0
BUDAPEST_global_radiation      0
BUDAPEST_precipitation         0
BUDAPEST_sunshine              0
BUDAPEST_temp_mean             0
BUDAPEST_temp_min              0
BUDAPEST_temp_max              0
DEBILT_cloud_cover             0
DEBILT_wind_speed              0
DEBILT_humidity                0
DEBILT_pressure                0
DEBILT_global_radiation        0
DEBILT_precipitation           0
DEBILT_sunshine                0
DEBILT_temp_mean               0
DEBILT_temp_min                0
DEBILT_temp_max                0
DUSSELDORF_cloud_cover         0
DUSSELDORF_wind_speed          0
DUSSELDORF_humidity            0
DUSSELDORF_pressure            0
DUSSELDORF_global_radiation    0
DUSSELDORF_precipitation       0
DUSSELDORF_snow_depth          0
DUSSELDORF_sunshine            0
DUSSELDORF_temp_mean           0
DUSSELDORF_temp_min            0
DUSSELDORF_temp_max            0
HEATHROW_cloud_cover           0
HEATHROW_humidity              0
HEATHROW_pressure              0
HEATHROW_global_radiation      0
HEATHROW_precipitation         0
HEATHROW_snow_depth            0
HEATHROW_sunshine              0
HEATHROW_temp_mean             0
HEATHROW_temp_min              0
HEATHROW_temp_max              0
KASSEL_wind_speed              0
KASSEL_humidity                0
KASSEL_pressure                0
KASSEL_global_radiation        0
KASSEL_precipitation           0
KASSEL_sunshine                0
KASSEL_temp_mean               0
KASSEL_temp_min                0
KASSEL_temp_max                0
LJUBLJANA_cloud_cover          0
LJUBLJANA_wind_speed           0
LJUBLJANA_humidity             0
LJUBLJANA_pressure             0
LJUBLJANA_global_radiation     0
LJUBLJANA_precipitation        0
LJUBLJANA_sunshine             0
LJUBLJANA_temp_mean            0
LJUBLJANA_temp_min             0
LJUBLJANA_temp_max             0
MAASTRICHT_cloud_cover         0
MAASTRICHT_wind_speed          0
MAASTRICHT_humidity            0
MAASTRICHT_pressure            0
MAASTRICHT_global_radiation    0
MAASTRICHT_precipitation       0
MAASTRICHT_sunshine            0
MAASTRICHT_temp_mean           0
MAASTRICHT_temp_min            0
MAASTRICHT_temp_max            0
MADRID_cloud_cover             0
MADRID_wind_speed              0
MADRID_humidity                0
MADRID_pressure                0
MADRID_global_radiation        0
MADRID_precipitation           0
MADRID_sunshine                0
MADRID_temp_mean               0
MADRID_temp_min                0
MADRID_temp_max                0
MUNCHENB_cloud_cover           0
MUNCHENB_humidity              0
MUNCHENB_global_radiation      0
MUNCHENB_precipitation         0
MUNCHENB_snow_depth            0
MUNCHENB_sunshine              0
MUNCHENB_temp_mean             0
MUNCHENB_temp_min              0
MUNCHENB_temp_max              0
OSLO_cloud_cover               0
OSLO_wind_speed                0
OSLO_humidity                  0
OSLO_pressure                  0
OSLO_global_radiation          0
OSLO_precipitation             0
OSLO_snow_depth                0
OSLO_sunshine                  0
OSLO_temp_mean                 0
OSLO_temp_min                  0
OSLO_temp_max                  0
SONNBLICK_cloud_cover          0
SONNBLICK_wind_speed           0
SONNBLICK_humidity             0
SONNBLICK_pressure             0
SONNBLICK_global_radiation     0
SONNBLICK_precipitation        0
SONNBLICK_sunshine             0
SONNBLICK_temp_mean            0
SONNBLICK_temp_min             0
SONNBLICK_temp_max             0
STOCKHOLM_cloud_cover          0
STOCKHOLM_pressure             0
STOCKHOLM_global_radiation     0
STOCKHOLM_precipitation        0
STOCKHOLM_sunshine             0
STOCKHOLM_temp_mean            0
STOCKHOLM_temp_min             0
STOCKHOLM_temp_max             0
VALENTIA_cloud_cover           0
VALENTIA_humidity              0
VALENTIA_pressure              0
VALENTIA_global_radiation      0
VALENTIA_precipitation         0
VALENTIA_snow_depth            0
VALENTIA_sunshine              0
VALENTIA_temp_mean             0
VALENTIA_temp_min              0
VALENTIA_temp_max              0
dtype: int64

In [16]:
# Extract the different observation types

observation_types = ['cloud_cover', 'wind_speed', 'humidity', 'pressure',
                     'global_radiation', 'precipitation', 'snow_depth', 
                     'sunshine', 'temp_mean', 'temp_min', 'temp_max']

In [17]:
# Create a dictionary to store the count of stations for each observation type
station_counts = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Count the number of stations (i.e., the number of columns) for the current observation type
    station_counts[obs] = len(columns)

# Print the count of stations for each observation type
print("Number of stations covered by each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Number of stations covered by each observation type:
cloud_cover: 14 stations
wind_speed: 9 stations
humidity: 14 stations
pressure: 14 stations
global_radiation: 15 stations
precipitation: 15 stations
snow_depth: 6 stations
sunshine: 15 stations
temp_mean: 15 stations
temp_min: 15 stations
temp_max: 15 stations

In [18]:
# Get a list of columns containing 'wind_speed' or 'snow_depth'
cols_to_drop = [col for col in unscaled.columns if '_wind_speed' in col or '_snow_depth' in col]

# Drop the columns
unscaled = unscaled.drop(cols_to_drop, axis=1)

In [19]:
unscaled.shape # Expecation is to have 15 columns less

(22950, 134)

In [20]:
# Find the stations with the above entries missing
# Get all column names
all_columns = unscaled.columns.tolist()
# Exclude 'DATE' and 'MONTH' columns
all_columns = [col for col in all_columns if col not in ['DATE', 'MONTH']]  
# Extract unique weather station names
weather_stations = set()  # Use a set to automatically store only unique values
for col in all_columns:
    station_name = col.split('_')[0]  # Split the column name at the underscore and take the first part
    weather_stations.add(station_name)

# Print the list of weather stations
print(weather_stations)

{'HEATHROW', 'MAASTRICHT', 'LJUBLJANA', 'MADRID', 'BASEL', 'KASSEL', 'DUSSELDORF', 'OSLO', 'BUDAPEST', 'SONNBLICK', 'BELGRADE', 'STOCKHOLM', 'MUNCHENB', 'DEBILT', 'VALENTIA'}

In [21]:
# Find stations missing observation types
observation_types = ['cloud_cover', 'humidity', 'pressure']

missing_stations_by_observation = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Extract station names by removing the observation type from the column names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identify stations that are in all_stations but missing from the current observation type
    missing_stations = weather_stations - station_names
    
    # Store the missing station names in the dictionary
    missing_stations_by_observation[obs] = missing_stations

# Print the missing station names for each observation type
for obs, missing_stations in missing_stations_by_observation.items():
    print(f"\nStations missing from {obs}:")
    if missing_stations:
        for station in missing_stations:
            print(station)
    else:
        print("None")

Stations missing from cloud_cover:
KASSEL

Stations missing from humidity:
STOCKHOLM

Stations missing from pressure:
MUNCHENB

In [22]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [23]:
# Cloud cover is the start of a stations data, Kassel is next to Heathrow, find the position of Heathrow_temp_max for the insertion of Kassel_cloud_cover
unscaled.columns.get_loc('HEATHROW_temp_max')

55

In [24]:
# Find the position for insertion of Stockholm humidity
unscaled.columns.get_loc('STOCKHOLM_cloud_cover') #humidity is 1 after cloud cover so (result +1)

117

In [25]:
# Find position for Munchenb pressure
unscaled.columns.get_loc('MUNCHENB_cloud_cover') # pressure is 2 after cloud cover so (result +2)

91

In [26]:
# Insert new columns into "unscaled" at specific positions.
# The data for these new columns is taken from weather stations they are close to

unscaled.insert(56,'KASSEL_cloud_cover', unscaled['DUSSELDORF_cloud_cover'])
unscaled.insert(119, 'STOCKHOLM_humidity', unscaled['OSLO_humidity'])
unscaled.insert(94,'MUNCHENB_pressure',unscaled['BASEL_pressure'])

In [27]:
unscaled.columns.tolist()

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_cloud_cover',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_pressure',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_humidity',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [28]:
unscaled.shape

(22950, 137)

In [29]:
# Export cleaned dataset with date & month columns
unscaled.to_csv(os.path.join(path, 'Data Sets', 'weather_cleaned_with_date.csv'), index=False)

In [30]:
# Drop unnecessary columns
unscaled.drop(['DATE', 'MONTH'], axis=1, inplace=True)

In [31]:
# confirm drop
unscaled.shape

(22950, 135)

In [32]:

prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [33]:
# drop unneeded column from second dataset
prediction.drop(columns = 'DATE', inplace = True)

In [34]:
prediction.shape

(22950, 15)

In [35]:
# Export cleaned dataset
unscaled.to_csv(os.path.join(path, 'Data Sets', 'weather_cleaned.csv'), index=False)

### Data Reshaping

In [37]:
# Creat an 'X' matrix by reloading and naming our data 'X'
X=pd.read_csv(os.path.join(path, 'Data Sets', 'weather_cleaned.csv'), index_col=False)

In [38]:
X.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.018,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.018,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.018,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.018,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.018,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [39]:
y=prediction

In [40]:
X.shape

(22950, 135)

In [41]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [42]:
X = X.reshape(-1,15,9)

In [43]:
# Verify Shape
X.shape

(22950, 15, 9)

In [44]:
# Verify Shape
y.shape

(22950, 15)

In [45]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [46]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

### Creating CNN Model

In [48]:
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [49]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 14, 32)         │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 14, 16)         │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,831 (11.06 KB)

 Trainable params: 2,831 (11.06 KB)

 Non-trainable params: 0 (0.00 B)

### Running CNN Model Attempt #1

In [51]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [52]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 5s - 4ms/step - accuracy: 0.0850 - loss: 3136.0300
Epoch 2/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1181 - loss: 32246.7227
Epoch 3/30
1076/1076 - 3s - 2ms/step - accuracy: 0.1269 - loss: 110833.1328
Epoch 4/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1389 - loss: 247328.7500
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1370 - loss: 436793.1875
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1382 - loss: 696269.1875
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1381 - loss: 1015222.9375
Epoch 8/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1308 - loss: 1443156.7500
Epoch 9/30
1076/1076 - 3s - 2ms/step - accuracy: 0.1345 - loss: 1953175.0000
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1340 - loss: 2549794.7500
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1301 - loss: 3221012.5000
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1280 - loss: 4033628.0000
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1332 - loss: 4942935.0000
Epoch 14/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1296 - loss: 5956521.5000
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1285 - loss: 7083808.5000
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1285 - loss: 8385659.0000
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1289 - loss: 9719609.0000
Epoch 18/30
1076/1076 - 3s - 2ms/step - accuracy: 0.1307 - loss: 11297678.0000
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1342 - loss: 13092275.0000
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1302 - loss: 15018727.0000
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1329 - loss: 16981590.0000
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1319 - loss: 19212776.0000
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1288 - loss: 21460878.0000
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1286 - loss: 24250084.0000
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1339 - loss: 26885688.0000
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1290 - loss: 29937920.0000
Epoch 27/30
1076/1076 - 3s - 2ms/step - accuracy: 0.1272 - loss: 33357302.0000
Epoch 28/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1289 - loss: 36606516.0000
Epoch 29/30
1076/1076 - 5s - 4ms/step - accuracy: 0.1333 - loss: 40355984.0000
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1324 - loss: 43925840.0000

In [53]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'}

In [54]:
# Create confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [55]:
# Print Matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL          19        30      1090      13          14       549     295
BELGRADE        0         8       602       0           0        40      99
BUDAPEST        0         0       104       0           0        16      22
DEBILT          0         0        28       0           0         6      14
DUSSELDORF      0         0         3       0           0         5       5
HEATHROW        0         0        12       0           0        11       8
KASSEL          0         0         6       0           0         0       2
LJUBLJANA       0         0        23       0           0         5       1
MAASTRICHT      0         0         5       0           0         0       2
MADRID          0         1        88       0           0        59      20
MUNCHENB        0         0         7       0           0         0       0
OSLO            0         0         3       0           0         0       0
STOCKHOLM       0         0         3       0           0         0       0
VALENTIA        0         0         0       0           0         0       1

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL             242           2     385       680   119         12
BELGRADE            5           0      67       192     2          0
BUDAPEST            0           0      24        30     1          0
DEBILT              0           0       4        20     0          0
DUSSELDORF          0           0       6         6     0          0
HEATHROW            0           0      25        10     0          0
KASSEL              0           0       0         2     0          0
LJUBLJANA           3           0      20         5     0          0
MAASTRICHT          1           0       1         0     0          0
MADRID             11           1     194        45     4          0
MUNCHENB            0           0       0         0     0          0
OSLO                0           0       1         0     0          0
STOCKHOLM           0           0       0         0     0          0
VALENTIA            0           0       0         0     0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL             197        35
BELGRADE           77         0
BUDAPEST           17         0
DEBILT             10         0
DUSSELDORF          4         0
HEATHROW           16         0
KASSEL              1         0
LJUBLJANA           4         0
MAASTRICHT          0         0
MADRID             35         0
MUNCHENB            1         0
OSLO                1         0
STOCKHOLM           1         0
VALENTIA            0         0

### CNN Attempt #2

In [57]:
epochs = 30
batch_size = 16
n_hidden = 16 ### decreased from 32 to 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='relu')) # Options: sigmoid, tanh, softmax, relu ## Switched to relu

In [58]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 16)         │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 14, 16)         │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,271 (8.87 KB)

 Trainable params: 2,271 (8.87 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [60]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1649 - loss: nan
Epoch 2/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 30/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan

In [61]:
# Create confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [62]:
# Print Matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1

### CNN Attempt #3

In [64]:
epochs = 30
batch_size = 16
n_hidden = 24 ## increased from 16 to 24

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='relu')) # Options: sigmoid, tanh, softmax, relu ## Kept as relu

In [65]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 14, 24)         │           456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 14, 16)         │           400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,551 (9.96 KB)

 Trainable params: 2,551 (9.96 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [67]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 4s - 3ms/step - accuracy: 0.0851 - loss: 23.5164
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5875 - loss: nan
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan

In [68]:
# Create confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [69]:
# Print Matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1

### CNN Attempt #4

In [71]:
epochs = 30
batch_size = 16
n_hidden = 36 ## increased from 24 to 36

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='relu')) # Options: sigmoid, tanh, softmax, relu

In [72]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 14, 36)         │           684 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 14, 16)         │           592 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,971 (11.61 KB)

 Trainable params: 2,971 (11.61 KB)

 Non-trainable params: 0 (0.00 B)

In [73]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 4s - 4ms/step - accuracy: 0.1420 - loss: 19.5006
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5320 - loss: nan
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/30
1076/1076 - 4s - 4ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/30
1076/1076 - 6s - 5ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: nan

In [75]:
# Create confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [76]:
# Print Matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1